#include "gpu/UiMask.h"

#include <algorithm>
#include <cstring>

#include "gpu/Shaders/UiMaskBlend.cs.h"   // generated by dxc at build time

using Microsoft::WRL::ComPtr;

namespace sidecar {
namespace {

constexpr uint32_t kUploadAlignment = D3D12_TEXTURE_DATA_PITCH_ALIGNMENT;  // 256

uint32_t AlignUp(uint32_t value, uint32_t alignment) {
  return (value + alignment - 1) & ~(alignment - 1);
}

}  // namespace

std::unique_ptr<UiMask> UiMask::Create(ID3D12Device* device,
                                       uint32_t width, uint32_t height) {
  if (!device || width == 0 || height == 0) return nullptr;

  std::unique_ptr<UiMask> m(new UiMask());
  m->device_ = device;
  m->width_ = width;
  m->height_ = height;
  m->rowPitch_ = AlignUp(width, kUploadAlignment);

  // Three SRVs -- original, neural, mask -- and one UAV.
  D3D12_DESCRIPTOR_RANGE ranges[2]{};
  ranges[0].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
  ranges[0].NumDescriptors = 3;
  ranges[0].BaseShaderRegister = 0;
  ranges[1].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
  ranges[1].NumDescriptors = 1;
  ranges[1].BaseShaderRegister = 0;
  ranges[1].OffsetInDescriptorsFromTableStart = 3;

  D3D12_ROOT_PARAMETER params[2]{};
  params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
  params[0].DescriptorTable.NumDescriptorRanges = 2;
  params[0].DescriptorTable.pDescriptorRanges = ranges;
  params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
  params[1].Constants.Num32BitValues = 2;
  params[1].Constants.ShaderRegister = 0;

  D3D12_ROOT_SIGNATURE_DESC rsd{};
  rsd.NumParameters = 2;
  rsd.pParameters = params;

  ComPtr<ID3DBlob> blob, error;
  if (FAILED(D3D12SerializeRootSignature(&rsd, D3D_ROOT_SIGNATURE_VERSION_1,
                                         &blob, &error))) {
    return nullptr;
  }
  if (FAILED(device->CreateRootSignature(0, blob->GetBufferPointer(),
                                         blob->GetBufferSize(),
                                         IID_PPV_ARGS(&m->rootSignature_)))) {
    return nullptr;
  }

  D3D12_COMPUTE_PIPELINE_STATE_DESC psd{};
  psd.pRootSignature = m->rootSignature_.Get();
  psd.CS.pShaderBytecode = g_UiMaskBlendCS;
  psd.CS.BytecodeLength = sizeof(g_UiMaskBlendCS);
  if (FAILED(device->CreateComputePipelineState(&psd, IID_PPV_ARGS(&m->pipeline_)))) {
    return nullptr;
  }

  D3D12_DESCRIPTOR_HEAP_DESC hd{};
  hd.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
  hd.NumDescriptors = 4;
  hd.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
  if (FAILED(device->CreateDescriptorHeap(&hd, IID_PPV_ARGS(&m->heap_)))) {
    return nullptr;
  }
  m->descriptorSize_ =
      device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);

  // The mask itself. Sampled by the blend, and potentially handed to NGX as the
  // bias-current-colour mask, so it starts in COMMON: D3D12 requires COMMON for
  // cross-queue access and will not promote into it implicitly.
  D3D12_HEAP_PROPERTIES heap{};
  heap.Type = D3D12_HEAP_TYPE_DEFAULT;
  D3D12_RESOURCE_DESC rd{};
  rd.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
  rd.Width = width;
  rd.Height = height;
  rd.DepthOrArraySize = 1;
  rd.MipLevels = 1;
  rd.Format = DXGI_FORMAT_R8_UNORM;
  rd.SampleDesc.Count = 1;
  if (FAILED(device->CreateCommittedResource(&heap, D3D12_HEAP_FLAG_NONE, &rd,
                                             D3D12_RESOURCE_STATE_COMMON, nullptr,
                                             IID_PPV_ARGS(&m->mask_)))) {
    return nullptr;
  }

  D3D12_HEAP_PROPERTIES uploadHeap{};
  uploadHeap.Type = D3D12_HEAP_TYPE_UPLOAD;
  D3D12_RESOURCE_DESC ud{};
  ud.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
  ud.Width = static_cast<uint64_t>(m->rowPitch_) * height;
  ud.Height = 1;
  ud.DepthOrArraySize = 1;
  ud.MipLevels = 1;
  ud.Format = DXGI_FORMAT_UNKNOWN;
  ud.SampleDesc.Count = 1;
  ud.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
  if (FAILED(device->CreateCommittedResource(&uploadHeap, D3D12_HEAP_FLAG_NONE, &ud,
                                             D3D12_RESOURCE_STATE_GENERIC_READ, nullptr,
                                             IID_PPV_ARGS(&m->upload_)))) {
    return nullptr;
  }

  m->staging_.assign(static_cast<size_t>(m->rowPitch_) * height, 0);
  return m;
}

void UiMask::Rasterise(ID3D12GraphicsCommandList* cl,
                       const std::vector<MaskRect>& rects,
                       uint32_t sourceWidth, uint32_t sourceHeight,
                       int32_t feather) {
  if (!cl) return;

  // Scale from the resolution the operator calibrated at, then clamp. Doing it
  // once here keeps the per-pixel loop below free of both concerns.
  std::vector<MaskRect> scaled;
  scaled.reserve(rects.size());
  for (const auto& r : rects) {
    const MaskRect s = ScaleRect(r, static_cast<int32_t>(sourceWidth),
                                 static_cast<int32_t>(sourceHeight),
                                 static_cast<int32_t>(width_),
                                 static_cast<int32_t>(height_));
    const MaskRect clamped = ClampToFrame(s, static_cast<int32_t>(width_),
                                          static_cast<int32_t>(height_));
    if (!IsEmpty(clamped)) scaled.push_back(clamped);
  }

  std::fill(staging_.begin(), staging_.end(), static_cast<uint8_t>(0));
  for (uint32_t y = 0; y < height_; ++y) {
    uint8_t* row = staging_.data() + static_cast<size_t>(y) * rowPitch_;
    for (uint32_t x = 0; x < width_; ++x) {
      const float coverage = CoverageAtAny(scaled, static_cast<int32_t>(x),
                                           static_cast<int32_t>(y), feather);
      // Round rather than truncate, so full coverage reaches exactly 255 and the
      // blend restores the original pixel bit-for-bit.
      row[x] = static_cast<uint8_t>(coverage * 255.0f + 0.5f);
    }
  }

  void* mapped = nullptr;
  D3D12_RANGE noRead{0, 0};
  if (FAILED(upload_->Map(0, &noRead, &mapped)) || !mapped) return;
  std::memcpy(mapped, staging_.data(), staging_.size());
  upload_->Unmap(0, nullptr);

  D3D12_RESOURCE_BARRIER toCopy{};
  toCopy.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
  toCopy.Transition.pResource = mask_.Get();
  toCopy.Transition.StateBefore = D3D12_RESOURCE_STATE_COMMON;
  toCopy.Transition.StateAfter = D3D12_RESOURCE_STATE_COPY_DEST;
  toCopy.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
  cl->ResourceBarrier(1, &toCopy);

  D3D12_TEXTURE_COPY_LOCATION dst{};
  dst.pResource = mask_.Get();
  dst.Type = D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;
  dst.SubresourceIndex = 0;

  D3D12_TEXTURE_COPY_LOCATION src{};
  src.pResource = upload_.Get();
  src.Type = D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;
  src.PlacedFootprint.Offset = 0;
  src.PlacedFootprint.Footprint.Format = DXGI_FORMAT_R8_UNORM;
  src.PlacedFootprint.Footprint.Width = width_;
  src.PlacedFootprint.Footprint.Height = height_;
  src.PlacedFootprint.Footprint.Depth = 1;
  src.PlacedFootprint.Footprint.RowPitch = rowPitch_;
  cl->CopyTextureRegion(&dst, 0, 0, 0, &src, nullptr);

  D3D12_RESOURCE_BARRIER toCommon = toCopy;
  toCommon.Transition.StateBefore = D3D12_RESOURCE_STATE_COPY_DEST;
  toCommon.Transition.StateAfter = D3D12_RESOURCE_STATE_COMMON;
  cl->ResourceBarrier(1, &toCommon);

  hasMask_ = true;
}

void UiMask::Record(ID3D12GraphicsCommandList* cl,
                    ID3D12Resource* original,
                    ID3D12Resource* neural,
                    ID3D12Resource* dst) {
  if (!cl || !original || !neural || !dst || !hasMask_) return;

  auto cpu = heap_->GetCPUDescriptorHandleForHeapStart();

  D3D12_SHADER_RESOURCE_VIEW_DESC srv{};
  srv.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
  srv.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
  srv.Texture2D.MipLevels = 1;

  // Formats come from the resources themselves: this pass sits after the neural
  // pass, whose working format is RGBA16F, but it is also useful on the raw
  // BGRA8 capture, and hard-coding either would silently mis-decode the other.
  srv.Format = original->GetDesc().Format;
  device_->CreateShaderResourceView(original, &srv, cpu);

  cpu.ptr += descriptorSize_;
  srv.Format = neural->GetDesc().Format;
  device_->CreateShaderResourceView(neural, &srv, cpu);

  cpu.ptr += descriptorSize_;
  srv.Format = DXGI_FORMAT_R8_UNORM;
  device_->CreateShaderResourceView(mask_.Get(), &srv, cpu);

  cpu.ptr += descriptorSize_;
  D3D12_UNORDERED_ACCESS_VIEW_DESC uav{};
  uav.Format = dst->GetDesc().Format;
  uav.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
  device_->CreateUnorderedAccessView(dst, nullptr, &uav, cpu);

  ID3D12DescriptorHeap* heaps[] = {heap_.Get()};
  cl->SetDescriptorHeaps(1, heaps);
  cl->SetComputeRootSignature(rootSignature_.Get());
  cl->SetPipelineState(pipeline_.Get());
  cl->SetComputeRootDescriptorTable(0, heap_->GetGPUDescriptorHandleForHeapStart());
  const uint32_t dims[2] = {width_, height_};
  cl->SetComputeRoot32BitConstants(1, 2, dims, 0);
  cl->Dispatch((width_ + 7) / 8, (height_ + 7) / 8, 1);
}

}  // namespace sidecar
