#include "core/I18nTable.h"

// Spanish interface text. Generated by tools/gen_translation_table.py;
// the conventions are the Russian table's (I18nRu.cpp): keys are the English
// source text exactly, format specifiers keep their order, and file names,
// add-on key names and the log are never translated.

namespace sidecar {

const TranslationPair kSpanishTable[] = {
    {"Interface mode",
     "Modo de interfaz"},
    {"Easy",
     "Fácil"},
    {"All controls and diagnostics.",
     "Todos los controles y diagnósticos."},
    {"Everyday controls. Settings are preserved.",
     "Controles cotidianos. Se conservan los ajustes."},
    {"Your next adventure",
     "Tu próxima aventura"},
    {"Choose a look. Check your setup. Start playing.",
     "Elige un estilo. Revisa la configuración. Empieza a jugar."},
    {"Discard changes",
     "Descartar cambios"},
    {"Settings saved.",
     "Ajustes guardados."},
    {"Could not save settings. Check folder permissions and try again.",
     "No se pudieron guardar los ajustes. Comprueba los permisos de la carpeta e inténtalo de nuevo."},
    {"Cancel",
     "Cancelar"},
    {"Status",
     "Estado"},
    {"Setup",
     "Instalación"},
    {"Checks",
     "Comprobaciones"},
    {"Tuning",
     "Ajustes"},
    {"Log",
     "Registro"},
    {"Neural rendering for World of Warcraft, from outside the game process",
     "Renderizado neuronal para World of Warcraft, desde fuera del proceso del "
     "juego"},
    {"Stop overlay",
     "Detener overlay"},
    {"Start overlay",
     "Iniciar overlay"},
    {"Before you use this",
     "Antes de usar esto"},
    {"This sidecar never loads code into Wow.exe. That is what makes it safe, and "
     "it is checked automatically every time it is built.\n\nReShade placed next "
     "to Wow.exe is a different thing entirely, and Blizzard bans accounts for "
     "it. This tool will refuse to install there and will refuse to run if it "
     "finds an injector in your WoW folder.\n\nNo third-party tool can promise "
     "you will never be banned. What this one can promise is that it does not do "
     "any of the things Blizzard bans people for.",
     "Este sidecar nunca carga código en Wow.exe. Eso es lo que lo hace seguro, y "
     "se comprueba automáticamente cada vez que se compila.\n\nReShade colocado "
     "junto a Wow.exe es algo completamente distinto, y Blizzard banea cuentas "
     "por ello. Esta herramienta se negará a instalarse ahí y se negará a "
     "ejecutarse si encuentra un inyector en tu carpeta de WoW.\n\nNinguna "
     "herramienta de terceros puede prometer que nunca te banearán. Lo que esta "
     "sí puede prometer es que no hace nada de lo que Blizzard castiga con un "
     "baneo."},
    {"I understand",
     "Entendido"},
    {"Live",
     "En directo"},
    {"OVERLAY FPS",
     "FPS DEL OVERLAY"},
    {"LATENCY p50",
     "LATENCIA p50"},
    {"LATENCY p99",
     "LATENCIA p99"},
    {"CAPTURED FPS",
     "FPS CAPTURADOS"},
    {"WoW: borderless",
     "WoW: ventana sin bordes"},
    {"WoW: not borderless",
     "WoW: no está sin bordes"},
    {"WoW: not running",
     "WoW: no se está ejecutando"},
    {"Overlay: running",
     "Overlay: en marcha"},
    {"Overlay: stopped",
     "Overlay: detenido"},
    {"READY",
     "LISTO"},
    {"CHECK",
     "REVISAR"},
    {"BLOCKED",
     "BLOQUEADO"},
    {"Hide overlay (A/B compare)",
     "Ocultar overlay (comparar A/B)"},
    {"Show overlay",
     "Mostrar overlay"},
    {"Hide HUD",
     "Ocultar HUD"},
    {"Show HUD",
     "Mostrar HUD"},
    {"Hiding the overlay uncovers the untouched game without stopping capture.",
     "Ocultar el overlay descubre el juego sin procesar sin detener la captura."},
    {"GPU MEMORY USED BY THE SIDECAR",
     "MEMORIA DE GPU USADA POR EL SIDECAR"},
    {"  --  SPILLING",
     "  —  DESBORDANDO"},
    {"This is the sidecar's own share, not the whole card. More of it would not "
     "be faster -- the pass allocates what it needs. The number that matters is "
     "whether any has spilled.",
     "Esta es la parte del propio sidecar, no la de toda la tarjeta. Tener más no "
     "lo haría más rápido: el pase reserva lo que necesita. Lo que importa es si "
     "algo se ha desbordado."},
    {"WHERE THE FRAME GOES",
     "A DÓNDE VA EL FOTOGRAMA"},
    {"Frames",
     "Fotogramas"},
    {"%llu presented, %llu dropped",
     "%llu mostrados, %llu descartados"},
    {"Pass",
     "Pase"},
    {"Verdict",
     "Veredicto"},
    {"playable",
     "jugable"},
    {"marginal",
     "al límite"},
    {"too slow",
     "demasiado lento"},
    {"The overlay is starting. Numbers appear after the first few frames.",
     "El overlay está arrancando. Los números aparecen tras los primeros "
     "fotogramas."},
    {"Nothing running.",
     "Nada en marcha."},
    {"The card is full, so the driver is moving resources to system memory and "
     "every frame waits on the PCIe bus. It shows below as a huge GPU wait with "
     "the GPU nearly idle, which is easy to mistake for a slow neural "
     "pass.\n\nClose what else is using the card -- browsers, streaming and "
     "capture tools, anything compositing a second monitor -- and lower the "
     "game's texture quality. Nothing in this tool can make room.",
     "La tarjeta está llena, así que el controlador está moviendo recursos a la "
     "memoria del sistema y cada fotograma espera al bus PCIe. Abajo aparece como "
     "una espera de GPU enorme con la GPU casi inactiva, algo fácil de confundir "
     "con un pase neuronal lento.\n\nCierra lo que más esté usando la tarjeta "
     "—navegadores, herramientas de streaming y captura, cualquier cosa que "
     "componga un segundo monitor— y baja la calidad de texturas del juego. Nada "
     "en esta herramienta puede hacer sitio."},
    {"This is the desktop compositor's rate, not the sidecar's and not the game's "
     "-- the game may well be running far faster. It is usually set by your "
     "monitor's refresh rate and, on a multi-monitor setup with mismatched "
     "refresh rates, by the slowest one. Nothing in this tool can raise it.",
     "Esta es la tasa del compositor del escritorio, no la del sidecar ni la del "
     "juego: el juego puede ir mucho más rápido. Normalmente la fija la "
     "frecuencia de tu monitor y, con varios monitores de frecuencias distintas, "
     "el más lento. Nada en esta herramienta puede subirla."},
    {"The game is competing for the GPU. Measured on the development machine, the "
     "same scene ran at 11.7 fps with the game focused and 35.2 fps with it in "
     "the background, purely because an unfocused game throttles itself and hands "
     "the card back.\n\nCap the game's frame rate. This costs nothing: the "
     "overlay can never show more than the capture rate above, so every frame the "
     "game renders beyond that is discarded before it reaches here.",
     "El juego compite por la GPU. Medido en la máquina de desarrollo, la misma "
     "escena iba a 11,7 fps con el juego en primer plano y a 35,2 fps con él en "
     "segundo plano, solo porque un juego sin foco se limita a sí mismo y "
     "devuelve la tarjeta.\n\nLimita los FPS del juego. No cuesta nada: el "
     "overlay nunca puede mostrar más que la tasa de captura de arriba, así que "
     "cada fotograma que el juego renderiza por encima se descarta antes de "
     "llegar aquí."},
    {"The overlay is presenting close to every frame Windows hands it, and there "
     "is memory to spare. Nothing to fix here.",
     "El overlay muestra casi todos los fotogramas que Windows le entrega, y "
     "sobra memoria. Aquí no hay nada que arreglar."},
    {"Some checks are failing. Open Checks to see what.",
     "Algunas comprobaciones fallan. Abre Comprobaciones para ver cuáles."},
    {"Files are missing. Open Setup to install them.",
     "Faltan archivos. Abre Instalación para instalarlos."},
    {"Start World of Warcraft in borderless windowed mode, then press Start "
     "overlay.",
     "Inicia World of Warcraft en modo ventana sin bordes y pulsa Iniciar overlay."},
    {"Press Start overlay.",
     "Pulsa Iniciar overlay."},
    {"Playing with the overlay up",
     "Jugar con el overlay activo"},
    {"The overlay covers the game completely and passes every click straight "
     "through to it, so play normally. It never takes focus, so whatever had the "
     "keyboard keeps it -- if the game is not responding, alt-tab to World of "
     "Warcraft once.\n\nCtrl+Alt+Backspace takes the overlay down from anywhere, "
     "without needing this window.",
     "El overlay cubre el juego por completo y deja pasar cada clic directamente "
     "a él, así que juega con normalidad. Nunca toma el foco, así que lo que "
     "tuviera el teclado lo conserva: si el juego no responde, cambia a World of "
     "Warcraft una vez con Alt+Tab.\n\nCtrl+Alt+Retroceso quita el overlay desde "
     "cualquier parte, sin necesidad de esta ventana."},
    {"Required files",
     "Archivos necesarios"},
    {"Three files have to sit next to the sidecar. None of them is ours to "
     "redistribute and nothing here downloads anything -- neither binary in this "
     "project can reach the network at all. Fetch them yourself, then point this "
     "at them.",
     "Tres archivos tienen que estar junto al sidecar. Ninguno es nuestro para "
     "redistribuirlo y aquí no se descarga nada: ningún ejecutable de este "
     "proyecto puede acceder a la red. Consíguelos tú y luego indícale aquí dónde "
     "están."},
    {"INSTALLED",
     "INSTALADO"},
    {"MISSING",
     "FALTA"},
    {"OPTIONAL",
     "OPCIONAL"},
    {"Wanted as %s   |   Source: %s",
     "Se espera como %s   |   Origen: %s"},
    {"Replace...",
     "Reemplazar..."},
    {"Choose file...",
     "Elegir archivo..."},
    {"Remove",
     "Quitar"},
    {"Deletes the files listed above from this folder, and nothing else. It never "
     "touches a WoW installation. The sidecar's own two executables stay; delete "
     "the folder to be rid of them.",
     "Borra de esta carpeta los archivos de la lista de arriba, y nada más. Nunca "
     "toca una instalación de WoW. Los dos ejecutables del sidecar se quedan; "
     "borra la carpeta para deshacerte de ellos."},
    {"Also remove settings and logs",
     "Quitar también ajustes y registros"},
    {"Yes, remove them",
     "Sí, quitarlos"},
    {"Remove installed files",
     "Quitar archivos instalados"},
    {"Stop the overlay first -- the files are in use.",
     "Detén primero el overlay: los archivos están en uso."},
    {"%zu file(s) would go.",
     "Se quitarían %zu archivo(s)."},
    {"That file no longer exists.",
     "Ese archivo ya no existe."},
    {"That is not a file.",
     "Eso no es un archivo."},
    {"Already installed.",
     "Ya está instalado."},
    {"Could not copy it in: ",
     "No se pudo copiar: "},
    {"Installed ",
     "Instalado "},
    {"Could not remove ",
     "No se pudo quitar "},
    {". Stop the overlay and close anything using it, then try again.",
     ". Detén el overlay y cierra lo que lo esté usando, y vuelve a intentarlo."},
    {"Removed ",
     "Quitados "},
    {" file(s).",
     " archivo(s)."},
    {"DLSS 5 neural rendering runtime",
     "Runtime de renderizado neuronal DLSS 5"},
    {"The neural network itself. On an RTX 40 card this must be a build patched "
     "for Ada; the stock runtime is Blackwell-only and fails at feature creation "
     "with no diagnostic.",
     "La red neuronal en sí. En una tarjeta RTX 40 debe ser una compilación "
     "parcheada para Ada; el runtime original es solo para Blackwell y falla al "
     "crear la función sin ningún diagnóstico."},
    {"ReShade, with add-on support",
     "ReShade, con soporte de complementos"},
    {"Hosts the add-on inside the sidecar's own process. The add-on-enabled build "
     "is required; the plain one loads no add-ons at all.",
     "Aloja el complemento dentro del propio proceso del sidecar. Se necesita la "
     "versión con complementos; la normal no carga ninguno."},
    {"RenoDX DLSS 5 add-on",
     "Complemento RenoDX DLSS 5"},
    {"Detours the sidecar's own NGX calls and substitutes neural-rendered output. "
     "This is what makes the pass neural rather than a plain DLAA.",
     "Desvía las propias llamadas NGX del sidecar y sustituye la salida por la "
     "renderizada neuronalmente. Es lo que convierte el pase en neuronal y no en "
     "un simple DLAA."},
    {"DLSS upscaling runtime",
     "Runtime de escalado DLSS"},
    {"Optional. Only consulted if the add-on's work-in-progress upscaling path is "
     "switched on; neural rendering itself does not need it.",
     "Opcional. Solo se usa si activas el escalado experimental del complemento; "
     "el renderizado neuronal no lo necesita."},
    {"System checks",
     "Comprobaciones del sistema"},
    {"Nothing here opens, reads, writes or hooks the game process. The import "
     "table of every binary is checked against that claim at build time.",
     "Nada de esto abre, lee, escribe ni engancha el proceso del juego. La tabla "
     "de importaciones de cada ejecutable se comprueba contra esa afirmación al "
     "compilar."},
    {"WoW folder (used only to scan filenames for injectors)",
     "Carpeta de WoW (solo para buscar inyectores por nombre de archivo)"},
    {"Browse...",
     "Examinar..."},
    {"Detect",
     "Detectar"},
    {"Re-run checks",
     "Repetir comprobaciones"},
    {"Detected from Battle.net's own uninstall entry. Point this at the folder "
     "Wow.exe sits in, not its parent: an injector has to be next to the "
     "executable to be loaded by it. Nothing inside is opened -- only the file "
     "names are read.",
     "Detectada a partir de la entrada de desinstalación de Battle.net. Apunta a "
     "la carpeta donde está Wow.exe, no a la superior: un inyector tiene que "
     "estar junto al ejecutable para que este lo cargue. No se abre nada dentro; "
     "solo se leen los nombres de archivo."},
    {"Graphics adapter",
     "Adaptador gráfico"},
    {"No NVIDIA adapter found.",
     "No se encontró ningún adaptador NVIDIA."},
    {"This sidecar needs an NVIDIA RTX 40 or RTX 50 card.",
     "Este sidecar necesita una tarjeta NVIDIA RTX 40 o RTX 50."},
    {"RTX 40 (Ada) or RTX 50 (Blackwell) is required. Older cards are refused "
     "rather than run badly.",
     "Se necesita una RTX 40 (Ada) o RTX 50 (Blackwell). Las tarjetas más "
     "antiguas se rechazan en lugar de funcionar mal."},
    {"Display driver",
     "Controlador de pantalla"},
    {"No NVIDIA adapter to query.",
     "No hay adaptador NVIDIA que consultar."},
    {"Install an NVIDIA RTX 40 or RTX 50 card.",
     "Instala una tarjeta NVIDIA RTX 40 o RTX 50."},
    {"User-mode driver ",
     "Controlador en modo usuario "},
    {"Could not read the driver version.",
     "No se pudo leer la versión del controlador."},
    {"Not fatal. Update to a current NVIDIA driver if capture misbehaves.",
     "No es grave. Actualiza a un controlador NVIDIA reciente si la captura falla."},
    {"Windows version",
     "Versión de Windows"},
    {"Could not read the Windows build number.",
     "No se pudo leer el número de compilación de Windows."},
    {"Not fatal, but this project is only supported on Windows 11.",
     "No es grave, pero este proyecto solo es compatible con Windows 11."},
    {"Build ",
     "Compilación "},
    {"Windows 11 is required: the overlay depends on compositor behaviour that "
     "Windows 10 does not provide.",
     "Se necesita Windows 11: el overlay depende de un comportamiento del "
     "compositor que Windows 10 no ofrece."},
    {"Display refresh rate",
     "Frecuencia de la pantalla"},
    {"Could not read the current display mode.",
     "No se pudo leer el modo de pantalla actual."},
    {"Not fatal. Check your monitor settings if pacing looks wrong.",
     "No es grave. Revisa la configuración del monitor si el ritmo de fotogramas "
     "parece raro."},
    {"Below 120 Hz the overlay's added latency is a larger share of the frame. It "
     "will still run.",
     "Por debajo de 120 Hz, la latencia añadida por el overlay es una parte mayor "
     "del fotograma. Funcionará igualmente."},
    {"Neural runtime",
     "Runtime neuronal"},
    {"nvngx_dlssnr.dll not found next to the sidecar.",
     "No se encontró nvngx_dlssnr.dll junto al sidecar."},
    {"Optional until the neural pass ships. Without it the pipeline runs the "
     "passthrough pass.",
     "Opcional hasta que llegue el pase neuronal. Sin él, el pipeline usa el pase "
     "directo."},
    {"Check the file is not locked by another process, and that the sidecar has "
     "permission to read it.",
     "Comprueba que el archivo no esté bloqueado por otro proceso y que el "
     "sidecar tenga permiso para leerlo."},
    {"Supply a runtime built for this GPU, or the neural pass will fall back to "
     "passthrough.",
     "Aporta un runtime compilado para esta GPU o el pase neuronal volverá al "
     "modo directo."},
    {"The pass will still try this build. If it fails, quote the SHA-256 above "
     "when reporting it.",
     "El pase lo intentará igualmente con esta compilación. Si falla, indica el "
     "SHA-256 de arriba al informar."},
    {"ReShade host (optional)",
     "Host ReShade (opcional)"},
    {"No ReShade host alongside the sidecar.",
     "No hay host ReShade junto al sidecar."},
    {"Only needed for the ReShade-hosted neural pass. Install ReShade against the "
     "sidecar so it lands as dxgi.dll. Never place ReShade next to Wow.exe.",
     "Solo hace falta para el pase neuronal alojado en ReShade. Instala ReShade "
     "sobre el sidecar para que quede como dxgi.dll. Nunca pongas ReShade junto a "
     "Wow.exe."},
    {"World of Warcraft window",
     "Ventana de World of Warcraft"},
    {"WoW is not running.",
     "WoW no se está ejecutando."},
    {"Start the game, then run the probes again.",
     "Inicia el juego y vuelve a lanzar las comprobaciones."},
    {" borderless windowed",
     " ventana sin bordes"},
    {" windowed with a border, or exclusive fullscreen",
     " ventana con borde o pantalla completa exclusiva"},
    {"Set WoW to borderless windowed. Exclusive fullscreen has no compositor "
     "surface to capture and yields black frames.",
     "Pon WoW en ventana sin bordes. La pantalla completa exclusiva no tiene "
     "superficie del compositor que capturar y da fotogramas en negro."},
    {"Injector scan of the WoW folder",
     "Búsqueda de inyectores en la carpeta de WoW"},
    {"No WoW folder set, so nothing was scanned.",
     "No hay carpeta de WoW, así que no se ha revisado nada."},
    {"Point the manager at your WoW folder so it can check for injectors before "
     "launching.",
     "Indica al gestor tu carpeta de WoW para que busque inyectores antes de "
     "iniciar."},
    {"No injector loaders found.",
     "No se encontraron cargadores inyectores."},
    {"Found: ",
     "Encontrado: "},
    {"Remove these from your WoW folder. Blizzard bans accounts for in-process "
     "injectors, and this tool refuses to run alongside one.",
     "Quítalos de tu carpeta de WoW. Blizzard banea cuentas por inyectores dentro "
     "del proceso, y esta herramienta se niega a funcionar junto a uno."},
    {"Sidecar install location",
     "Ubicación de instalación del sidecar"},
    {"Move the sidecar outside your WoW folder. Anything sitting next to Wow.exe "
     "looks like an injector, which is the one thing this design exists to avoid.",
     "Mueve el sidecar fuera de tu carpeta de WoW. Cualquier cosa junto a Wow.exe "
     "parece un inyector, que es justo lo que este diseño quiere evitar."},
    {" is the ",
     " es el runtime "},
    {" runtime, version ",
     ", versión "},
    {" could not be read, so it has no digest.",
     " no se pudo leer, así que no tiene resumen."},
    {" is not a build this manifest knows. Its SHA-256 is ",
     " no es una compilación conocida por este manifiesto. Su SHA-256 es "},
    {" -- quote that when reporting it.",
     ": indícalo al informar."},
    {"This GPU (",
     "Esta GPU ("},
    {") is outside the supported matrix; neural rendering needs Ada or Blackwell.",
     ") está fuera de la matriz compatible; el renderizado neuronal necesita Ada "
     "o Blackwell."},
    {"This is the stock runtime, which is built for Blackwell. On an Ada card "
     "neural-rendering feature creation fails with no explanation. An "
     "Ada-compatible build of nvngx_dlssnr.dll is required.",
     "Este es el runtime original, compilado para Blackwell. En una tarjeta Ada, "
     "la creación de la función de renderizado neuronal falla sin explicación. Se "
     "necesita una compilación de nvngx_dlssnr.dll compatible con Ada."},
    {"The ",
     "El runtime "},
    {" runtime does not run on ",
     " no funciona en "},
    {"Choose a look",
     "Elige un estilo"},
    {"IN USE",
     "EN USO"},
    {"Custom -- your settings do not match any preset.",
     "Personalizado: tus ajustes no coinciden con ningún preajuste."},
    {"Click one above to go back to a tested combination. Nothing is selected "
     "because the individual settings below have been moved away from all four.",
     "Haz clic en uno de arriba para volver a una combinación probada. No hay "
     "ninguno marcado porque los ajustes individuales de abajo se han alejado de "
     "los cuatro."},
    {"Pick one. Every setting below is chosen for you, and the combinations here "
     "are ones that have actually been run -- unlike most of the arrangements you "
     "can reach by moving sliders individually.",
     "Elige uno. Cada ajuste de abajo se elige por ti, y estas combinaciones son "
     "las que se han probado de verdad, a diferencia de la mayoría de las que "
     "puedes obtener moviendo controles sueltos."},
    {"Recommended",
     "Recomendado"},
    {"The tuned default. Start here.",
     "El valor ajustado por defecto. Empieza aquí."},
    {"Full neural intensity with the CNN F render preset, which clamps temporal "
     "history hard -- the right choice when motion vectors are estimated from "
     "colour rather than rendered by the game.",
     "Intensidad neuronal completa con el preajuste de renderizado CNN F, que "
     "limita con fuerza el historial temporal: la elección correcta cuando los "
     "vectores de movimiento se estiman a partir del color en vez de venir del "
     "juego."},
    {"Softer",
     "Más suave"},
    {"Half strength. Use if the picture looks over-processed.",
     "Media intensidad. Úsalo si la imagen parece sobreprocesada."},
    {"The same pipeline with the neural result mixed in at 60%. Cheaper on the "
     "eyes for interface-heavy scenes, and the first thing to try if faces or "
     "text look waxy.",
     "El mismo pipeline con el resultado neuronal mezclado al 60%. Más agradable "
     "en escenas con mucha interfaz, y lo primero que probar si caras o texto "
     "parecen de cera."},
    {"Most stable",
     "Más estable"},
    {"For smearing, or flicker on flames and lights.",
     "Para borrones o parpadeo en llamas y luces."},
    {"Switches to CNN E, which clamps temporal history hardest, and eases the "
     "intensity. This is the preset for when motion looks smeared -- the "
     "estimated motion vectors are being confidently wrong and this contains them.",
     "Cambia a CNN E, que limita el historial temporal al máximo, y suaviza la "
     "intensidad. Es el preajuste para cuando el movimiento se ve emborronado: "
     "los vectores de movimiento estimados se equivocan con seguridad y esto lo "
     "contiene."},
    {"Off (A/B baseline)",
     "Apagado (referencia A/B)"},
    {"Capture and present, untouched.",
     "Captura y muestra, sin tocar."},
    {"No neural work at all, on the same capture and present path. This is the "
     "honest comparison: whatever you see here is what the overlay costs you "
     "before any neural rendering happens.",
     "Ningún trabajo neuronal, con la misma captura y presentación. Es la "
     "comparación honesta: lo que ves aquí es lo que te cuesta el overlay antes "
     "de cualquier renderizado neuronal."},
    {"Save settings",
     "Guardar ajustes"},
    {"Changes are not saved yet.",
     "Los cambios aún no se han guardado."},
    {"Restart the overlay to apply.",
     "Reinicia el overlay para aplicarlo."},
    {"Every individual setting",
     "Todos los ajustes individuales"},
    {"Nothing in here is needed for normal use.",
     "Nada de esto es necesario para un uso normal."},
    {"These are written to sidecar.toml, and the neural ones are projected into "
     "ReShade.ini where the add-on reads them. The add-on reads that file once, "
     "when it loads, so a change reaches the picture at the overlay's next start "
     "-- not while it runs.",
     "Se escriben en sidecar.toml, y los neuronales se trasladan a ReShade.ini, "
     "donde los lee el complemento. El complemento lee ese archivo una sola vez, "
     "al cargarse, así que un cambio llega a la imagen en el siguiente inicio del "
     "overlay, no mientras funciona."},
    {"Neural pass",
     "Pase neuronal"},
    {"passthrough -- capture and present, untouched",
     "passthrough — captura y muestra, sin tocar"},
    {"reshade -- DLSS 5 neural rendering",
     "reshade — renderizado neuronal DLSS 5"},
    {"Passthrough is the honest A/B baseline: the same capture and present path "
     "with no neural work in it at all.",
     "El pase directo es la referencia A/B honesta: la misma captura y "
     "presentación sin ningún trabajo neuronal."},
    {"DLSS preset",
     "Preajuste DLSS"},
    {"Optical flow grid",
     "Rejilla de flujo óptico"},
    {"1 -- finest, most expensive",
     "1 — la más fina, la más costosa"},
    {"4 -- default",
     "4 — por defecto"},
    {"Pixels per estimated motion vector. Finer costs more and is not obviously "
     "better: the vectors are estimated from colour, so a finer grid can sharpen "
     "the estimate or the error equally.",
     "Píxeles por vector de movimiento estimado. Más fino cuesta más y no es "
     "claramente mejor: los vectores se estiman a partir del color, así que una "
     "rejilla más fina puede afinar tanto la estimación como el error."},
    {"Synthetic depth",
     "Profundidad sintética"},
    {"There is no real depth buffer to capture out of the composited frame, so a "
     "constant plane is bound instead. It costs temporal stability under motion "
     "rather than preventing NR from running; this dial is worth a try if motion "
     "smears.",
     "No hay un búfer de profundidad real que capturar del fotograma compuesto, "
     "así que se usa un plano constante. Cuesta estabilidad temporal en "
     "movimiento en vez de impedir que funcione NR; vale la pena probar este "
     "control si el movimiento se emborrona."},
    {"Neural rendering strength",
     "Intensidad del renderizado neuronal"},
    {"Passed straight through to the RenoDX add-on. The add-on owns what these "
     "mean; we only carry them.",
     "Se pasan tal cual al complemento RenoDX. El complemento decide qué "
     "significan; nosotros solo los transmitimos."},
    {"Intensity",
     "Intensidad"},
    {"How much of the neural result is mixed in. Start here.",
     "Cuánto del resultado neuronal se mezcla. Empieza por aquí."},
    {"Add-on preset",
     "Preajuste del complemento"},
    {"Style",
     "Estilo"},
    {"Colour strength",
     "Intensidad del color"},
    {"At zero the add-on's colour handling collapses to black, so this is not a "
     "subtle dial.",
     "A cero, el manejo del color del complemento se vuelve negro, así que este "
     "control no es sutil."},
    {"HDR transfer strength",
     "Intensidad de transferencia HDR"},
    {"Paper-white scale",
     "Escala de blanco de papel"},
    {"Both only matter on an HDR display. The sidecar captures SDR today, so "
     "leave them at 1.00 unless you are experimenting.",
     "Ambos solo importan en una pantalla HDR. El sidecar captura en SDR por "
     "ahora, así que déjalos en 1.00 salvo que estés experimentando."},
    {"These three have no documented default, so they are written only once you "
     "move them. Clearing the box returns them to untouched, which leaves "
     "whatever the add-on does by itself.",
     "Estos tres no tienen un valor por defecto documentado, así que solo se "
     "escriben cuando los mueves. Vaciar la casilla los devuelve a sin tocar, lo "
     "que deja lo que el complemento haga por sí mismo."},
    {"Enable the add-on's upscaling (work in progress)",
     "Activar el escalado del complemento (experimental)"},
    {"The add-on marks this unfinished, and the sidecar feeds it a "
     "native-resolution DLAA contract, so it usually reports that it fell back to "
     "native. Off is the tested path.",
     "El complemento lo marca como inacabado, y el sidecar le da un contrato DLAA "
     "a resolución nativa, así que normalmente informa de que volvió a la nativa. "
     "Apagado es el camino probado."},
    {"Hook mode",
     "Modo de enganche"},
    {"0 turns neural rendering off entirely, 1 adds Streamline hooks, 2 is NGX "
     "only. Two is what this sidecar wants: it makes the NGX calls itself and "
     "there is no Streamline in the process.",
     "0 apaga por completo el renderizado neuronal, 1 añade enganches de "
     "Streamline, 2 es solo NGX. Dos es lo que quiere este sidecar: hace las "
     "llamadas NGX él mismo y no hay Streamline en el proceso."},
    {"Advanced",
     "Avanzado"},
    {"Local structure",
     "Estructura local"},
    {"How hard the model works on fine surface detail -- stonework, cloth weave, "
     "wood grain. Raising it sharpens texture and also sharpens whatever the "
     "model got wrong about it.",
     "Cuánto trabaja el modelo el detalle fino de las superficies: piedra, "
     "tejido, veta de la madera. Subirlo afila la textura y también lo que el "
     "modelo haya interpretado mal."},
    {"Local tone",
     "Tono local"},
    {"Local contrast: how far the model pushes light against dark within a small "
     "area. This is the dial most likely to change the mood of a scene rather "
     "than its detail.",
     "Contraste local: cuánto empuja el modelo la luz contra la sombra en una "
     "zona pequeña. Es el control que más probablemente cambie el ambiente de una "
     "escena y no su detalle."},
    {"Skin structure",
     "Estructura de la piel"},
    {"Faces and skin specifically. The one people reach for after watching a "
     "comparison video, and the one most likely to look wrong when overdone -- "
     "skin is where anybody spots a mistake.",
     "Caras y piel en concreto. El que todos buscan tras ver un vídeo "
     "comparativo, y el que más probablemente quede mal si se exagera: en la piel "
     "cualquiera nota un error."},
    {"The strip of numbers the overlay draws in its own top-left corner: frame "
     "rate, latency, which pass is running and how many frames were dropped. It "
     "is drawn by the overlay, not by the game, so it never reaches a screenshot "
     "the game takes.",
     "La franja de números que el overlay dibuja en su esquina superior "
     "izquierda: FPS, latencia, qué pase está activo y cuántos fotogramas se "
     "descartaron. La dibuja el overlay, no el juego, así que nunca sale en una "
     "captura del juego."},
    {"Whether the overlay covers the game the moment it launches. Off starts it "
     "hidden, which is the honest way to look at the untouched frame first and "
     "then bring the neural pass in over the top of it.",
     "Si el overlay cubre el juego en cuanto arranca. Apagado lo inicia oculto, "
     "que es la forma honesta de ver primero el fotograma sin tocar y luego poner "
     "el pase neuronal encima."},
    {"CNN F. The default here: clamps history hard, which suits estimated motion "
     "vectors.",
     "CNN F. El valor por defecto aquí: limita el historial con fuerza, lo que va "
     "bien con vectores de movimiento estimados."},
    {"CNN E. Clamps hardest. Try this first if motion smears or flames and lights "
     "flicker.",
     "CNN E. El que más limita. Pruébalo primero si el movimiento se emborrona o "
     "parpadean llamas y luces."},
    {"Transformer K. The SDK default for DLAA. Sharpest when the vectors are "
     "trustworthy.",
     "Transformer K. El valor del SDK para DLAA. El más nítido cuando los "
     "vectores son fiables."},
    {"Transformer J. The older transformer preset.",
     "Transformer J. El preajuste transformer anterior."},
    {"Whatever the runtime picks for itself.",
     "Lo que el runtime elija por sí mismo."},
    {"Show the HUD",
     "Mostrar el HUD"},
    {"Show the overlay on start",
     "Mostrar el overlay al iniciar"},
    {"Reset to defaults",
     "Restablecer valores"},
    {"%llu earlier line(s) dropped",
     "%llu línea(s) anteriores descartadas"},
    {"Last error",
     "Último error"},
    {"The overlay (sidecar.log)",
     "El overlay (sidecar.log)"},
    {"This manager",
     "Este gestor"},
    {"The overlay has not written anything yet.",
     "El overlay aún no ha escrito nada."},
    {"Window class not found.",
     "No se encontró la clase de ventana."},
    {"World of Warcraft is not running.",
     "World of Warcraft no se está ejecutando."},
    {"World of Warcraft must run in borderless windowed mode.\nExclusive "
     "fullscreen has no compositor surface to capture.",
     "World of Warcraft debe ejecutarse en modo ventana sin bordes.\nLa pantalla "
     "completa exclusiva no tiene superficie del compositor que capturar."},
    {"%hs is not supported. RTX 40 or RTX 50 required.",
     "%hs no es compatible. Se necesita RTX 40 o RTX 50."},
    {"Failed to create the pipeline.",
     "No se pudo crear el pipeline."},
    {"An overlay is already running.\nStop it from the manager before starting "
     "another.",
     "Ya hay un overlay en marcha.\nDetenlo desde el gestor antes de iniciar otro."},
    {"The graphics device was reset and could not be rebuilt.",
     "El dispositivo gráfico se reinició y no se pudo reconstruir."},
    {"Hotkeys",
     "Atajos de teclado"},
    {"off",
     "desactivado"},
    {"Start or stop the overlay (while this window is open)",
     "Iniciar o detener el overlay (con esta ventana abierta)"},
    {"Show or hide the overlay: instant A/B against the untouched game",
     "Mostrar u ocultar el overlay: A/B instantáneo con el juego sin tocar"},
    {"Show or hide the frame-time HUD",
     "Mostrar u ocultar el HUD de tiempos de fotograma"},
    {"Panic: take the overlay down, always",
     "Pánico: quitar el overlay, siempre"},
    {"Change them on the Tuning page.",
     "Cámbialos en la página Ajustes."},
    {"Written like Ctrl+Alt+D or Shift+Alt+F9. Each needs Ctrl, Alt or Win, "
     "because Windows takes the combination away from the game. Leave one empty "
     "to switch it off.",
     "Se escriben como Ctrl+Alt+D o Shift+Alt+F9. Cada uno necesita Ctrl, Alt o "
     "Win, porque Windows le quita la combinación al juego. Deja uno vacío para "
     "desactivarlo."},
    {"Start / stop overlay",
     "Iniciar / detener overlay"},
    {"Show / hide overlay",
     "Mostrar / ocultar overlay"},
    {"Show / hide HUD",
     "Mostrar / ocultar HUD"},
    {"not a key combination",
     "no es una combinación de teclas"},
    {"Language",
     "Idioma"},
    {"Interface theme",
     "Tema de la interfaz"},
    {"Stormwind",
     "Ventormenta"},
    {"Quest log",
     "Registro de misiones"},
    {"Neural strength",
     "Intensidad neuronal"},
    {"How many times DLSS 5 runs over each frame. One pass is subtle. Two or "
     "three push the picture further from the original -- closer to the heavily "
     "processed look in demonstration videos -- and each extra pass costs another "
     "full neural pass of GPU time.",
     "Cuántas veces se aplica DLSS 5 a cada fotograma. Un pase es sutil. Dos o "
     "tres alejan más la imagen del original —más cerca del aspecto muy procesado "
     "de los vídeos de demostración— y cada pase extra cuesta otro pase neuronal "
     "completo de tiempo de GPU."},
    {"2x  Stronger",
     "2x  Más fuerte"},
    {"3x  Strongest",
     "3x  Máximo"},
    {"Closest to the game",
     "Lo más cercano al juego"},
    {"About twice the GPU time",
     "Aproximadamente el doble de tiempo de GPU"},
    {"About three times the GPU time",
     "Aproximadamente el triple de tiempo de GPU"},
    {"Four passes, set in sidecar.toml. Pick one above to go back.",
     "Cuatro pases, fijados en sidecar.toml. Elige uno de arriba para volver."},
    {"The Off preset runs no neural pass, so this has no effect until you pick "
     "another look.",
     "El preajuste Apagado no aplica ningún pase neuronal, así que esto no tiene "
     "efecto hasta que elijas otro estilo."},
};

const size_t kSpanishTableSize = sizeof(kSpanishTable) / sizeof(kSpanishTable[0]);

}  // namespace sidecar
