#include "core/I18nTable.h"

// Korean interface text. Generated by tools/gen_translation_table.py;
// the conventions are the Russian table's (I18nRu.cpp): keys are the English
// source text exactly, format specifiers keep their order, and file names,
// add-on key names and the log are never translated.

namespace sidecar {

const TranslationPair kKoreanTable[] = {
    {"Interface mode",
     "인터페이스 모드"},
    {"Easy",
     "간편"},
    {"All controls and diagnostics.",
     "모든 설정과 진단을 표시합니다."},
    {"Everyday controls. Settings are preserved.",
     "자주 쓰는 기능입니다. 설정은 유지됩니다."},
    {"Your next adventure",
     "다음 모험을 향해"},
    {"Choose a look. Check your setup. Start playing.",
     "스타일을 선택하고 설정을 확인한 뒤 게임을 시작하세요."},
    {"Discard changes",
     "변경 사항 취소"},
    {"Settings saved.",
     "설정을 저장했습니다."},
    {"Could not save settings. Check folder permissions and try again.",
     "설정을 저장할 수 없습니다. 폴더 권한을 확인하고 다시 시도하세요."},
    {"Cancel",
     "취소"},
    {"Status",
     "상태"},
    {"Setup",
     "설치"},
    {"Checks",
     "점검"},
    {"Tuning",
     "조정"},
    {"Log",
     "로그"},
    {"Neural rendering for World of Warcraft, from outside the game process",
     "월드 오브 워크래프트를 위한 뉴럴 렌더링, 게임 프로세스 바깥에서"},
    {"Stop overlay",
     "오버레이 중지"},
    {"Start overlay",
     "오버레이 시작"},
    {"Before you use this",
     "사용하기 전에"},
    {"This sidecar never loads code into Wow.exe. That is what makes it safe, and "
     "it is checked automatically every time it is built.\n\nReShade placed next "
     "to Wow.exe is a different thing entirely, and Blizzard bans accounts for "
     "it. This tool will refuse to install there and will refuse to run if it "
     "finds an injector in your WoW folder.\n\nNo third-party tool can promise "
     "you will never be banned. What this one can promise is that it does not do "
     "any of the things Blizzard bans people for.",
     "이 도구는 Wow.exe에 어떤 코드도 불러오지 않습니다. 그것이 안전한 이유이며, 빌드할 때마다 자동으로 "
     "검사됩니다.\n\nReShade를 Wow.exe 옆에 두는 것은 전혀 다른 일이며, 블리자드는 그 때문에 계정을 정지합니다. 이 도구는 "
     "그곳에 설치되기를 거부하고, WoW 폴더에서 인젝터를 발견하면 실행도 거부합니다.\n\n어떤 서드파티 도구도 절대 정지당하지 않는다고 "
     "약속할 수는 없습니다. 이 도구가 약속할 수 있는 것은, 블리자드가 계정을 정지하는 그 어떤 행위도 하지 않는다는 것입니다."},
    {"I understand",
     "이해했습니다"},
    {"Live",
     "실시간"},
    {"OVERLAY FPS",
     "오버레이 FPS"},
    {"LATENCY p50",
     "지연 시간 p50"},
    {"LATENCY p99",
     "지연 시간 p99"},
    {"CAPTURED FPS",
     "캡처 FPS"},
    {"WoW: borderless",
     "WoW: 테두리 없는 창"},
    {"WoW: not borderless",
     "WoW: 테두리 없는 창 아님"},
    {"WoW: not running",
     "WoW: 실행 중 아님"},
    {"Overlay: running",
     "오버레이: 실행 중"},
    {"Overlay: stopped",
     "오버레이: 중지됨"},
    {"READY",
     "준비됨"},
    {"CHECK",
     "확인 필요"},
    {"BLOCKED",
     "차단됨"},
    {"Hide overlay (A/B compare)",
     "오버레이 숨기기 (A/B 비교)"},
    {"Show overlay",
     "오버레이 표시"},
    {"Hide HUD",
     "HUD 숨기기"},
    {"Show HUD",
     "HUD 표시"},
    {"Hiding the overlay uncovers the untouched game without stopping capture.",
     "오버레이를 숨기면 캡처를 멈추지 않고 처리되지 않은 게임 화면이 드러납니다."},
    {"GPU MEMORY USED BY THE SIDECAR",
     "이 도구가 사용하는 GPU 메모리"},
    {"  --  SPILLING",
     "  —  넘침"},
    {"This is the sidecar's own share, not the whole card. More of it would not "
     "be faster -- the pass allocates what it needs. The number that matters is "
     "whether any has spilled.",
     "카드 전체가 아니라 이 도구의 몫입니다. 더 많다고 빨라지지 않습니다. 처리 과정은 필요한 만큼만 할당합니다. 중요한 것은 넘친 부분이 "
     "있는지입니다."},
    {"WHERE THE FRAME GOES",
     "프레임 시간의 행방"},
    {"Frames",
     "프레임"},
    {"%llu presented, %llu dropped",
     "표시 %llu, 버림 %llu"},
    {"Pass",
     "처리"},
    {"Runtime",
     "런타임"},
    {"Verdict",
     "판정"},
    {"playable",
     "플레이 가능"},
    {"marginal",
     "아슬아슬"},
    {"too slow",
     "너무 느림"},
    {"The overlay is starting. Numbers appear after the first few frames.",
     "오버레이를 시작하는 중입니다. 처음 몇 프레임 후에 수치가 나타납니다."},
    {"Nothing running.",
     "실행 중인 것이 없습니다."},
    {"The card is full, so the driver is moving resources to system memory and "
     "every frame waits on the PCIe bus. It shows below as a huge GPU wait with "
     "the GPU nearly idle, which is easy to mistake for a slow neural "
     "pass.\n\nClose what else is using the card -- browsers, streaming and "
     "capture tools, anything compositing a second monitor -- and lower the "
     "game's texture quality. Nothing in this tool can make room.",
     "카드 메모리가 가득 차서 드라이버가 리소스를 시스템 메모리로 옮기고 있으며, 매 프레임이 PCIe 버스를 기다립니다. 아래에서는 "
     "GPU가 거의 놀고 있는데 GPU 대기 시간이 매우 길게 나타나며, 느린 뉴럴 처리로 착각하기 쉽습니다.\n\n브라우저, 방송·녹화 "
     "도구, 두 번째 모니터를 합성하는 모든 것 등 카드를 쓰는 다른 프로그램을 닫고 게임의 텍스처 품질을 낮추세요. 이 도구로는 공간을 "
     "만들 수 없습니다."},
    {"This is the desktop compositor's rate, not the sidecar's and not the game's "
     "-- the game may well be running far faster. It is usually set by your "
     "monitor's refresh rate and, on a multi-monitor setup with mismatched "
     "refresh rates, by the slowest one. Nothing in this tool can raise it.",
     "이것은 데스크톱 컴포지터의 속도이며, 이 도구나 게임의 속도가 아닙니다. 게임 자체는 훨씬 빠르게 돌 수 있습니다. 보통 모니터 "
     "주사율이 정하며, 주사율이 다른 여러 모니터를 쓰면 가장 느린 모니터가 정합니다. 이 도구로는 올릴 수 없습니다."},
    {"The game is competing for the GPU. Measured on the development machine, the "
     "same scene ran at 11.7 fps with the game focused and 35.2 fps with it in "
     "the background, purely because an unfocused game throttles itself and hands "
     "the card back.\n\nCap the game's frame rate. This costs nothing: the "
     "overlay can never show more than the capture rate above, so every frame the "
     "game renders beyond that is discarded before it reaches here.",
     "게임이 GPU를 두고 경쟁하고 있습니다. 개발 PC에서 측정한 결과, 같은 장면이 게임을 앞에 두면 11.7 fps, 뒤에 두면 "
     "35.2 fps였습니다. 포커스를 잃은 게임은 스스로 속도를 낮추고 카드를 양보하기 때문입니다.\n\n게임의 프레임 속도를 제한하세요. "
     "손해는 없습니다. 오버레이는 위의 캡처 속도보다 더 많이 표시할 수 없으므로, 그 이상으로 게임이 그린 프레임은 여기 도착하기 전에 "
     "버려집니다."},
    {"The overlay is presenting close to every frame Windows hands it, and there "
     "is memory to spare. Nothing to fix here.",
     "오버레이가 Windows가 넘겨주는 거의 모든 프레임을 표시하고 있으며, 메모리도 여유가 있습니다. 고칠 것이 없습니다."},
    {"Some checks are failing. Open Checks to see what.",
     "일부 점검이 실패했습니다. 점검을 열어 확인하세요."},
    {"Files are missing. Open Setup to install them.",
     "파일이 없습니다. 설치를 열어 설치하세요."},
    {"Start World of Warcraft in borderless windowed mode, then press Start "
     "overlay.",
     "월드 오브 워크래프트를 테두리 없는 창 모드로 시작한 다음 오버레이 시작을 누르세요."},
    {"Press Start overlay.",
     "오버레이 시작을 누르세요."},
    {"Playing with the overlay up",
     "오버레이를 켜고 플레이하기"},
    {"The overlay covers the game completely and passes every click straight "
     "through to it, so play normally. It never takes focus, so whatever had the "
     "keyboard keeps it -- if the game is not responding, alt-tab to World of "
     "Warcraft once.\n\nCtrl+Alt+Backspace takes the overlay down from anywhere, "
     "without needing this window.",
     "오버레이는 게임을 완전히 덮고 모든 클릭을 그대로 게임에 전달하므로 평소처럼 플레이하면 됩니다. 포커스를 가져가지 않으므로 키보드를 "
     "갖고 있던 창이 계속 갖습니다. 게임이 반응하지 않으면 Alt+Tab으로 월드 오브 워크래프트에 한 번 "
     "전환하세요.\n\nCtrl+Alt+Backspace를 누르면 이 창 없이도 어디서든 오버레이를 내릴 수 있습니다."},
    {"Required files",
     "필요한 파일"},
    {"Three files have to sit next to the sidecar. None of them is ours to "
     "redistribute and nothing here downloads anything -- neither binary in this "
     "project can reach the network at all. Fetch them yourself, then point this "
     "at them.",
     "세 개의 파일이 이 도구 옆에 있어야 합니다. 모두 우리가 재배포할 수 있는 것이 아니며, 여기서는 아무것도 다운로드하지 않습니다. 이 "
     "프로젝트의 두 실행 파일 모두 네트워크에 전혀 접근할 수 없습니다. 직접 받은 뒤 여기서 지정하세요."},
    {"INSTALLED",
     "설치됨"},
    {"MISSING",
     "없음"},
    {"OPTIONAL",
     "선택"},
    {"Wanted as %s   |   Source: %s",
     "필요한 이름 %s   |   출처: %s"},
    {"Replace...",
     "교체..."},
    {"Choose file...",
     "파일 선택..."},
    {"Remove",
     "제거"},
    {"Deletes the files listed above from this folder, and nothing else. It never "
     "touches a WoW installation. The sidecar's own two executables stay; delete "
     "the folder to be rid of them.",
     "위에 나열된 파일만 이 폴더에서 삭제하며 다른 것은 건드리지 않습니다. WoW 설치에는 절대 손대지 않습니다. 이 도구의 두 실행 "
     "파일은 남으므로, 완전히 없애려면 폴더를 삭제하세요."},
    {"Also remove settings and logs",
     "설정과 로그도 제거"},
    {"Yes, remove them",
     "예, 제거합니다"},
    {"Remove installed files",
     "설치된 파일 제거"},
    {"Stop the overlay first -- the files are in use.",
     "먼저 오버레이를 중지하세요. 파일이 사용 중입니다."},
    {"%zu file(s) would go.",
     "파일 %zu개가 제거됩니다."},
    {"That file no longer exists.",
     "그 파일은 더 이상 존재하지 않습니다."},
    {"That is not a file.",
     "파일이 아닙니다."},
    {"Already installed.",
     "이미 설치되어 있습니다."},
    {"Could not copy it in: ",
     "복사할 수 없습니다: "},
    {"Installed ",
     "설치됨: "},
    {"Could not remove ",
     "제거할 수 없습니다: "},
    {". Stop the overlay and close anything using it, then try again.",
     ". 오버레이를 중지하고 사용 중인 프로그램을 닫은 뒤 다시 시도하세요."},
    {"Removed ",
     "제거됨: "},
    {" file(s).",
     "개 파일."},
    {"DLSS 5 neural rendering runtime",
     "DLSS 5 뉴럴 렌더링 런타임"},
    {"The neural network itself. On an RTX 40 card this must be a build patched "
     "for Ada; the stock runtime is Blackwell-only and fails at feature creation "
     "with no diagnostic.",
     "신경망 그 자체입니다. RTX 40 카드에서는 Ada용으로 패치된 빌드여야 합니다. 기본 런타임은 Blackwell 전용이며 기능 생성 "
     "시 아무 진단 없이 실패합니다."},
    {"ReShade, with add-on support",
     "애드온 지원 ReShade"},
    {"Hosts the add-on inside the sidecar's own process. The add-on-enabled build "
     "is required; the plain one loads no add-ons at all.",
     "이 도구의 프로세스 안에서 애드온을 호스팅합니다. 애드온 지원 빌드가 필요하며, 일반 빌드는 애드온을 전혀 불러오지 않습니다."},
    {"RenoDX DLSS 5 add-on",
     "RenoDX DLSS 5 애드온"},
    {"Detours the sidecar's own NGX calls and substitutes neural-rendered output. "
     "This is what makes the pass neural rather than a plain DLAA.",
     "이 도구 자신의 NGX 호출을 가로채 뉴럴 렌더링 결과로 바꿉니다. 이것이 처리를 단순한 DLAA가 아닌 뉴럴로 만듭니다."},
    {"DLSS upscaling runtime",
     "DLSS 업스케일링 런타임"},
    {"Optional. Only consulted if the add-on's work-in-progress upscaling path is "
     "switched on; neural rendering itself does not need it.",
     "선택 사항. 애드온의 개발 중인 업스케일링을 켰을 때만 사용되며, 뉴럴 렌더링 자체에는 필요하지 않습니다."},
    {"System checks",
     "시스템 점검"},
    {"Nothing here opens, reads, writes or hooks the game process. The import "
     "table of every binary is checked against that claim at build time.",
     "여기 있는 어떤 것도 게임 프로세스를 열거나 읽거나 쓰거나 후킹하지 않습니다. 모든 실행 파일의 임포트 테이블이 빌드 시 이 주장에 "
     "맞게 검사됩니다."},
    {"WoW folder (used only to scan filenames for injectors)",
     "WoW 폴더 (인젝터 파일 이름 검사에만 사용)"},
    {"Browse...",
     "찾아보기..."},
    {"Detect",
     "감지"},
    {"Re-run checks",
     "점검 다시 실행"},
    {"Detected from Battle.net's own uninstall entry. Point this at the folder "
     "Wow.exe sits in, not its parent: an injector has to be next to the "
     "executable to be loaded by it. Nothing inside is opened -- only the file "
     "names are read.",
     "Battle.net 자체 제거 정보에서 감지했습니다. 상위 폴더가 아니라 Wow.exe가 있는 폴더를 지정하세요. 인젝터는 실행 파일 "
     "옆에 있어야 불러와집니다. 안의 내용은 열지 않고 파일 이름만 읽습니다."},
    {"Graphics adapter",
     "그래픽 어댑터"},
    {"No NVIDIA adapter found.",
     "NVIDIA 어댑터를 찾을 수 없습니다."},
    {"This sidecar needs an NVIDIA RTX 40 or RTX 50 card.",
     "이 도구에는 NVIDIA RTX 40 또는 RTX 50 카드가 필요합니다."},
    {"RTX 40 (Ada) or RTX 50 (Blackwell) is required. Older cards are refused "
     "rather than run badly.",
     "RTX 40 (Ada) 또는 RTX 50 (Blackwell)이 필요합니다. 오래된 카드는 불안하게 돌리는 대신 거부됩니다."},
    {"Display driver",
     "디스플레이 드라이버"},
    {"No NVIDIA adapter to query.",
     "조회할 NVIDIA 어댑터가 없습니다."},
    {"Install an NVIDIA RTX 40 or RTX 50 card.",
     "NVIDIA RTX 40 또는 RTX 50 카드를 장착하세요."},
    {"User-mode driver ",
     "사용자 모드 드라이버 "},
    {"Could not read the driver version.",
     "드라이버 버전을 읽을 수 없습니다."},
    {"Not fatal. Update to a current NVIDIA driver if capture misbehaves.",
     "치명적이지 않습니다. 캡처가 이상하면 최신 NVIDIA 드라이버로 업데이트하세요."},
    {"Windows version",
     "Windows 버전"},
    {"Could not read the Windows build number.",
     "Windows 빌드 번호를 읽을 수 없습니다."},
    {"Not fatal, but this project is only supported on Windows 11.",
     "치명적이지 않지만, 이 프로젝트는 Windows 11만 지원합니다."},
    {"Build ",
     "빌드 "},
    {"Windows 11 is required: the overlay depends on compositor behaviour that "
     "Windows 10 does not provide.",
     "Windows 11이 필요합니다. 오버레이는 Windows 10에 없는 컴포지터 동작에 의존합니다."},
    {"Display refresh rate",
     "디스플레이 주사율"},
    {"Could not read the current display mode.",
     "현재 디스플레이 모드를 읽을 수 없습니다."},
    {"Not fatal. Check your monitor settings if pacing looks wrong.",
     "치명적이지 않습니다. 프레임 간격이 이상하면 모니터 설정을 확인하세요."},
    {"Below 120 Hz the overlay's added latency is a larger share of the frame. It "
     "will still run.",
     "120Hz 미만에서는 오버레이가 더하는 지연이 프레임에서 차지하는 비율이 커집니다. 그래도 작동합니다."},
    {"Neural runtime",
     "뉴럴 런타임"},
    {"nvngx_dlssnr.dll not found next to the sidecar.",
     "이 도구 옆에서 nvngx_dlssnr.dll을 찾을 수 없습니다."},
    {"Optional until the neural pass ships. Without it the pipeline runs the "
     "passthrough pass.",
     "뉴럴 처리가 제공될 때까지는 선택 사항입니다. 없으면 파이프라인은 패스스루 처리로 동작합니다."},
    {"Check the file is not locked by another process, and that the sidecar has "
     "permission to read it.",
     "파일이 다른 프로세스에 잠겨 있지 않은지, 이 도구에 읽기 권한이 있는지 확인하세요."},
    {"Supply a runtime built for this GPU, or the neural pass will fall back to "
     "passthrough.",
     "이 GPU용으로 빌드된 런타임을 제공하세요. 없으면 뉴럴 처리가 패스스루로 돌아갑니다."},
    {"The pass will still try this build. If it fails, quote the SHA-256 above "
     "when reporting it.",
     "처리 과정은 이 빌드로도 시도합니다. 실패하면 신고할 때 위의 SHA-256을 함께 적어 주세요."},
    {"ReShade host (optional)",
     "ReShade 호스트 (선택)"},
    {"No ReShade host alongside the sidecar.",
     "이 도구 옆에 ReShade 호스트가 없습니다."},
    {"Only needed for the ReShade-hosted neural pass. Install ReShade against the "
     "sidecar so it lands as dxgi.dll. Never place ReShade next to Wow.exe.",
     "ReShade에서 호스팅하는 뉴럴 처리에만 필요합니다. ReShade를 이 도구에 대해 설치하여 dxgi.dll로 두세요. "
     "ReShade를 Wow.exe 옆에 두어서는 안 됩니다."},
    {"World of Warcraft window",
     "월드 오브 워크래프트 창"},
    {"WoW is not running.",
     "WoW가 실행 중이 아닙니다."},
    {"Start the game, then run the probes again.",
     "게임을 시작한 뒤 점검을 다시 실행하세요."},
    {" borderless windowed",
     " 테두리 없는 창"},
    {" windowed with a border, or exclusive fullscreen",
     " 테두리 있는 창 또는 전용 전체 화면"},
    {"Set WoW to borderless windowed. Exclusive fullscreen has no compositor "
     "surface to capture and yields black frames.",
     "WoW를 테두리 없는 창으로 설정하세요. 전용 전체 화면에는 캡처할 컴포지터 표면이 없어 검은 화면이 나옵니다."},
    {"Injector scan of the WoW folder",
     "WoW 폴더 인젝터 검사"},
    {"No WoW folder set, so nothing was scanned.",
     "WoW 폴더가 설정되지 않아 아무것도 검사하지 않았습니다."},
    {"Point the manager at your WoW folder so it can check for injectors before "
     "launching.",
     "시작 전에 인젝터를 검사할 수 있도록 관리자에게 WoW 폴더를 지정하세요."},
    {"No injector loaders found.",
     "인젝터 로더가 없습니다."},
    {"Found: ",
     "발견: "},
    {"Remove these from your WoW folder. Blizzard bans accounts for in-process "
     "injectors, and this tool refuses to run alongside one.",
     "WoW 폴더에서 제거하세요. 블리자드는 프로세스 내 인젝터 때문에 계정을 정지하며, 이 도구는 인젝터와 함께 실행되지 않습니다."},
    {"Sidecar install location",
     "이 도구의 설치 위치"},
    {"Move the sidecar outside your WoW folder. Anything sitting next to Wow.exe "
     "looks like an injector, which is the one thing this design exists to avoid.",
     "이 도구를 WoW 폴더 밖으로 옮기세요. Wow.exe 옆에 있는 것은 모두 인젝터처럼 보이며, 이 설계가 피하려는 바로 그것입니다."},
    {" is the ",
     "은(는) "},
    {" runtime, version ",
     " 런타임, 버전 "},
    {" could not be read, so it has no digest.",
     "을(를) 읽을 수 없어 다이제스트가 없습니다."},
    {" is not a build this manifest knows. Its SHA-256 is ",
     "은(는) 이 매니페스트가 모르는 빌드입니다. SHA-256은 "},
    {" -- quote that when reporting it.",
     "입니다. 신고할 때 함께 적어 주세요."},
    {"This GPU (",
     "이 GPU("},
    {") is outside the supported matrix; neural rendering needs Ada or Blackwell.",
     ")는 지원 범위 밖입니다. 뉴럴 렌더링에는 Ada 또는 Blackwell이 필요합니다."},
    {"This is the stock runtime, which is built for Blackwell. On an Ada card "
     "neural-rendering feature creation fails with no explanation. An "
     "Ada-compatible build of nvngx_dlssnr.dll is required.",
     "이것은 Blackwell용으로 빌드된 기본 런타임입니다. Ada 카드에서는 뉴럴 렌더링 기능 생성이 설명 없이 실패합니다. Ada 호환 "
     "nvngx_dlssnr.dll 빌드가 필요합니다."},
    {" runtime does not run on ",
     " 런타임은 다음에서 작동하지 않습니다: "},
    {"Choose a look",
     "룩 선택"},
    {"IN USE",
     "사용 중"},
    {"Custom -- your settings do not match any preset.",
     "사용자 지정 — 설정이 어떤 프리셋과도 맞지 않습니다."},
    {"Click one above to go back to a tested combination. Nothing is selected "
     "because the individual settings below have been moved away from all four.",
     "위에서 하나를 클릭하면 검증된 조합으로 돌아갑니다. 아래 개별 설정이 네 가지 모두에서 벗어나 있어 아무것도 선택되지 않았습니다."},
    {"Pick one. Every setting below is chosen for you, and the combinations here "
     "are ones that have actually been run -- unlike most of the arrangements you "
     "can reach by moving sliders individually.",
     "하나를 고르세요. 아래 설정은 모두 자동으로 정해지며, 여기 있는 조합은 실제로 실행해 본 것들입니다. 슬라이더를 하나씩 움직여 만들 "
     "수 있는 대부분의 조합과는 다릅니다."},
    {"Recommended",
     "추천"},
    {"The tuned default. Start here.",
     "조정된 기본값. 여기서 시작하세요."},
    {"Full neural intensity with the CNN F render preset, which clamps temporal "
     "history hard -- the right choice when motion vectors are estimated from "
     "colour rather than rendered by the game.",
     "CNN F 렌더 프리셋으로 뉴럴 강도를 최대로. 시간 방향 기록을 강하게 제한하므로, 모션 벡터를 게임이 그리는 대신 색에서 추정할 때 "
     "알맞습니다."},
    {"Softer",
     "부드럽게"},
    {"Half strength. Use if the picture looks over-processed.",
     "절반 강도. 화면이 과하게 처리된 것 같을 때 사용하세요."},
    {"The same pipeline with the neural result mixed in at 60%. Cheaper on the "
     "eyes for interface-heavy scenes, and the first thing to try if faces or "
     "text look waxy.",
     "같은 파이프라인에 뉴럴 결과를 60%만 섞습니다. UI가 많은 장면에서 눈이 편하고, 얼굴이나 글자가 밀랍처럼 보이면 가장 먼저 시도할 "
     "것."},
    {"Most stable",
     "가장 안정적"},
    {"For smearing, or flicker on flames and lights.",
     "잔상이나 불꽃·조명의 깜빡임에."},
    {"Switches to CNN E, which clamps temporal history hardest, and eases the "
     "intensity. This is the preset for when motion looks smeared -- the "
     "estimated motion vectors are being confidently wrong and this contains them.",
     "시간 방향 기록을 가장 강하게 제한하는 CNN E로 바꾸고 강도를 낮춥니다. 움직임에 잔상이 생길 때의 프리셋입니다. 추정된 모션 "
     "벡터가 자신 있게 틀리는 것을 억제합니다."},
    {"Off (A/B baseline)",
     "끄기 (A/B 기준)"},
    {"Capture and present, untouched.",
     "캡처하고 표시만, 가공 없음."},
    {"No neural work at all, on the same capture and present path. This is the "
     "honest comparison: whatever you see here is what the overlay costs you "
     "before any neural rendering happens.",
     "뉴럴 처리가 전혀 없고 캡처·표시 경로는 같습니다. 정직한 비교입니다. 여기서 보이는 것이 뉴럴 렌더링 이전 오버레이 자체의 비용입니다."},
    {"Save settings",
     "설정 저장"},
    {"Changes are not saved yet.",
     "변경 사항이 아직 저장되지 않았습니다."},
    {"Restart the overlay to apply.",
     "적용하려면 오버레이를 다시 시작하세요."},
    {"Every individual setting",
     "모든 개별 설정"},
    {"Nothing in here is needed for normal use.",
     "일반적인 사용에는 필요하지 않습니다."},
    {"Pipeline",
     "파이프라인"},
    {"These are written to sidecar.toml, and the neural ones are projected into "
     "ReShade.ini where the add-on reads them. The add-on reads that file once, "
     "when it loads, so a change reaches the picture at the overlay's next start "
     "-- not while it runs.",
     "이 값들은 sidecar.toml에 기록되고, 뉴럴 관련 값은 애드온이 읽는 ReShade.ini에도 반영됩니다. 애드온은 로드될 때 "
     "이 파일을 한 번만 읽으므로, 변경은 실행 중이 아니라 다음 오버레이 시작 때 화면에 반영됩니다."},
    {"Neural pass",
     "뉴럴 처리"},
    {"passthrough -- capture and present, untouched",
     "passthrough — 캡처하고 표시만, 가공 없음"},
    {"reshade -- DLSS 5 neural rendering",
     "reshade — DLSS 5 뉴럴 렌더링"},
    {"Passthrough is the honest A/B baseline: the same capture and present path "
     "with no neural work in it at all.",
     "패스스루는 정직한 A/B 기준입니다. 같은 캡처·표시 경로에 뉴럴 처리가 전혀 없습니다."},
    {"DLSS preset",
     "DLSS 프리셋"},
    {"Optical flow grid",
     "광학 흐름 격자"},
    {"1 -- finest, most expensive",
     "1 — 가장 촘촘, 가장 무거움"},
    {"4 -- default",
     "4 — 기본값"},
    {"Pixels per estimated motion vector. Finer costs more and is not obviously "
     "better: the vectors are estimated from colour, so a finer grid can sharpen "
     "the estimate or the error equally.",
     "추정 모션 벡터 하나당 픽셀 수. 촘촘할수록 무겁고 꼭 좋아지지도 않습니다. 벡터는 색에서 추정하므로, 촘촘한 격자는 추정만큼 오차도 "
     "날카롭게 만들 수 있습니다."},
    {"Synthetic depth",
     "합성 깊이"},
    {"There is no real depth buffer to capture out of the composited frame, so a "
     "constant plane is bound instead. It costs temporal stability under motion "
     "rather than preventing NR from running; this dial is worth a try if motion "
     "smears.",
     "합성된 프레임에서는 실제 깊이 버퍼를 얻을 수 없으므로 일정한 평면을 대신 연결합니다. 움직임 중 시간적 안정성을 잃지만 NR 작동을 "
     "막지는 않습니다. 움직임에 잔상이 생기면 시도해 볼 만한 값입니다."},
    {"Neural rendering strength",
     "뉴럴 렌더링 강도"},
    {"Passed straight through to the RenoDX add-on. The add-on owns what these "
     "mean; we only carry them.",
     "RenoDX 애드온에 그대로 전달됩니다. 의미는 애드온이 정하며, 우리는 전달만 합니다."},
    {"Intensity",
     "강도"},
    {"How much of the neural result is mixed in. Start here.",
     "뉴럴 결과를 얼마나 섞을지. 여기서 시작하세요."},
    {"Add-on preset",
     "애드온 프리셋"},
    {"Style",
     "스타일"},
    {"Colour strength",
     "색 강도"},
    {"At zero the add-on's colour handling collapses to black, so this is not a "
     "subtle dial.",
     "0이면 애드온의 색 처리가 검게 무너지므로, 미세 조정용 값이 아닙니다."},
    {"HDR transfer strength",
     "HDR 전달 강도"},
    {"Paper-white scale",
     "페이퍼 화이트 배율"},
    {"Both only matter on an HDR display. The sidecar captures SDR today, so "
     "leave them at 1.00 unless you are experimenting.",
     "둘 다 HDR 디스플레이에서만 의미가 있습니다. 이 도구는 현재 SDR로 캡처하므로, 실험 중이 아니라면 1.00으로 두세요."},
    {"These three have no documented default, so they are written only once you "
     "move them. Clearing the box returns them to untouched, which leaves "
     "whatever the add-on does by itself.",
     "이 세 가지는 공개된 기본값이 없어 직접 움직였을 때만 기록됩니다. 칸을 비우면 손대지 않은 상태로 돌아가 애드온 자체 동작에 맡깁니다."},
    {"Enable the add-on's upscaling (work in progress)",
     "애드온 업스케일링 사용 (개발 중)"},
    {"The add-on marks this unfinished, and the sidecar feeds it a "
     "native-resolution DLAA contract, so it usually reports that it fell back to "
     "native. Off is the tested path.",
     "애드온이 이 기능을 미완성으로 표시하며, 이 도구는 기본 해상도의 DLAA 조건으로 넘기므로 보통 기본 해상도로 돌아갔다고 보고합니다. "
     "끄기가 검증된 경로입니다."},
    {"Hook mode",
     "후킹 모드"},
    {"0 turns neural rendering off entirely, 1 adds Streamline hooks, 2 is NGX "
     "only. Two is what this sidecar wants: it makes the NGX calls itself and "
     "there is no Streamline in the process.",
     "0은 뉴럴 렌더링을 완전히 끄고, 1은 Streamline 후킹을 추가하며, 2는 NGX만 씁니다. 이 도구가 원하는 것은 2입니다. "
     "NGX 호출을 직접 하며 프로세스에 Streamline이 없습니다."},
    {"Overlay",
     "오버레이"},
    {"Advanced",
     "고급"},
    {"Local structure",
     "로컬 구조"},
    {"How hard the model works on fine surface detail -- stonework, cloth weave, "
     "wood grain. Raising it sharpens texture and also sharpens whatever the "
     "model got wrong about it.",
     "돌 쌓기, 천의 짜임, 나뭇결 같은 표면 세부에 모델이 얼마나 공을 들이는지. 높이면 질감이 날카로워지고, 모델이 잘못 이해한 부분도 "
     "날카로워집니다."},
    {"Local tone",
     "로컬 톤"},
    {"Local contrast: how far the model pushes light against dark within a small "
     "area. This is the dial most likely to change the mood of a scene rather "
     "than its detail.",
     "국소 대비: 좁은 영역에서 밝음과 어둠을 얼마나 벌리는지. 세부보다 장면의 분위기를 바꾸기 쉬운 값입니다."},
    {"Skin structure",
     "피부 구조"},
    {"Faces and skin specifically. The one people reach for after watching a "
     "comparison video, and the one most likely to look wrong when overdone -- "
     "skin is where anybody spots a mistake.",
     "얼굴과 피부 전용. 비교 영상을 본 뒤 누구나 손대고 싶어지고, 과하면 가장 어색해 보이는 값입니다. 피부의 실수는 누구나 알아챕니다."},
    {"The strip of numbers the overlay draws in its own top-left corner: frame "
     "rate, latency, which pass is running and how many frames were dropped. It "
     "is drawn by the overlay, not by the game, so it never reaches a screenshot "
     "the game takes.",
     "오버레이가 자기 왼쪽 위에 그리는 숫자 줄: 프레임 속도, 지연 시간, 실행 중인 처리, 버린 프레임 수. 게임이 아니라 오버레이가 "
     "그리므로 게임 스크린샷에는 절대 찍히지 않습니다."},
    {"Whether the overlay covers the game the moment it launches. Off starts it "
     "hidden, which is the honest way to look at the untouched frame first and "
     "then bring the neural pass in over the top of it.",
     "오버레이가 시작하자마자 게임을 덮을지 여부. 끄면 숨긴 채로 시작합니다. 먼저 가공되지 않은 화면을 보고 그 위에 뉴럴 처리를 올리는 "
     "정직한 방법입니다."},
    {"CNN F. The default here: clamps history hard, which suits estimated motion "
     "vectors.",
     "CNN F. 여기서의 기본값. 기록을 강하게 제한하여 추정 모션 벡터에 잘 맞습니다."},
    {"CNN E. Clamps hardest. Try this first if motion smears or flames and lights "
     "flicker.",
     "CNN E. 가장 강하게 제한합니다. 움직임에 잔상이 생기거나 불꽃·조명이 깜빡이면 먼저 시도하세요."},
    {"Transformer K. The SDK default for DLAA. Sharpest when the vectors are "
     "trustworthy.",
     "Transformer K. DLAA용 SDK 기본값. 벡터를 믿을 수 있을 때 가장 선명합니다."},
    {"Transformer J. The older transformer preset.",
     "Transformer J. 이전 Transformer 프리셋."},
    {"Whatever the runtime picks for itself.",
     "런타임이 직접 고르는 것."},
    {"Show the HUD",
     "HUD 표시"},
    {"Show the overlay on start",
     "시작 시 오버레이 표시"},
    {"Reset to defaults",
     "기본값으로 재설정"},
    {"%llu earlier line(s) dropped",
     "이전 %llu줄 버림"},
    {"Last error",
     "마지막 오류"},
    {"The overlay (sidecar.log)",
     "오버레이 (sidecar.log)"},
    {"This manager",
     "이 관리자"},
    {"The overlay has not written anything yet.",
     "오버레이가 아직 아무것도 기록하지 않았습니다."},
    {"Window class not found.",
     "창 클래스를 찾을 수 없습니다."},
    {"World of Warcraft is not running.",
     "월드 오브 워크래프트가 실행 중이 아닙니다."},
    {"World of Warcraft must run in borderless windowed mode.\nExclusive "
     "fullscreen has no compositor surface to capture.",
     "월드 오브 워크래프트는 테두리 없는 창 모드로 실행해야 합니다.\n전용 전체 화면에는 캡처할 컴포지터 표면이 없습니다."},
    {"%hs is not supported. RTX 40 or RTX 50 required.",
     "%hs은(는) 지원되지 않습니다. RTX 40 또는 RTX 50이 필요합니다."},
    {"Failed to create the pipeline.",
     "파이프라인을 만들 수 없습니다."},
    {"An overlay is already running.\nStop it from the manager before starting "
     "another.",
     "오버레이가 이미 실행 중입니다.\n다른 것을 시작하기 전에 관리자에서 중지하세요."},
    {"The graphics device was reset and could not be rebuilt.",
     "그래픽 장치가 재설정되었고 다시 만들 수 없습니다."},
    {"Hotkeys",
     "단축키"},
    {"off",
     "끔"},
    {"Start or stop the overlay (while this window is open)",
     "오버레이 시작 또는 중지 (이 창이 열려 있는 동안)"},
    {"Show or hide the overlay: instant A/B against the untouched game",
     "오버레이 표시 또는 숨기기: 가공되지 않은 게임과 즉시 A/B 비교"},
    {"Show or hide the frame-time HUD",
     "프레임 시간 HUD 표시 또는 숨기기"},
    {"Panic: take the overlay down, always",
     "비상: 언제든 오버레이 내리기"},
    {"Change them on the Tuning page.",
     "조정 페이지에서 바꿀 수 있습니다."},
    {"Written like Ctrl+Alt+D or Shift+Alt+F9. Each needs Ctrl, Alt or Win, "
     "because Windows takes the combination away from the game. Leave one empty "
     "to switch it off.",
     "Ctrl+Alt+D나 Shift+Alt+F9처럼 씁니다. Windows가 그 조합을 게임에서 가져가므로 각각 Ctrl, Alt, Win "
     "중 하나가 필요합니다. 비워 두면 꺼집니다."},
    {"Start / stop overlay",
     "오버레이 시작 / 중지"},
    {"Show / hide overlay",
     "오버레이 표시 / 숨기기"},
    {"Show / hide HUD",
     "HUD 표시 / 숨기기"},
    {"not a key combination",
     "키 조합이 아닙니다"},
    {"Language",
     "언어"},
    {"Interface theme",
     "인터페이스 테마"},
    {"Stormwind",
     "스톰윈드"},
    {"Quest log",
     "퀘스트 목록"},
    {"Dragonflight",
     "용군단"},
    {"Neural strength",
     "뉴럴 강도"},
    {"How many times DLSS 5 runs over each frame. One pass is subtle. Two or "
     "three push the picture further from the original -- closer to the heavily "
     "processed look in demonstration videos -- and each extra pass costs another "
     "full neural pass of GPU time.",
     "각 프레임에 DLSS 5를 몇 번 적용할지. 한 번은 은은합니다. 두세 번이면 원본에서 더 멀어져 데모 영상의 강하게 처리된 모습에 "
     "가까워지며, 한 번 늘릴 때마다 뉴럴 처리 한 번 분량의 GPU 시간이 더 듭니다."},
    {"1x  Natural",
     "1x  자연스럽게"},
    {"2x  Stronger",
     "2x  더 강하게"},
    {"3x  Strongest",
     "3x  가장 강하게"},
    {"Closest to the game",
     "게임과 가장 가까움"},
    {"About twice the GPU time",
     "GPU 시간 약 2배"},
    {"About three times the GPU time",
     "GPU 시간 약 3배"},
    {"Four passes, set in sidecar.toml. Pick one above to go back.",
     "4회, sidecar.toml에서 설정됨. 위에서 하나를 고르면 돌아갑니다."},
    {"The Off preset runs no neural pass, so this has no effect until you pick "
     "another look.",
     "끄기 프리셋은 뉴럴 처리를 하지 않으므로, 다른 룩을 고르기 전까지 이 설정은 효과가 없습니다."},
};

const size_t kKoreanTableSize = sizeof(kKoreanTable) / sizeof(kKoreanTable[0]);

}  // namespace sidecar
