#include "core/I18nTable.h"

// Japanese interface text. Generated by tools/gen_translation_table.py;
// the conventions are the Russian table's (I18nRu.cpp): keys are the English
// source text exactly, format specifiers keep their order, and file names,
// add-on key names and the log are never translated.

namespace sidecar {

const TranslationPair kJapaneseTable[] = {
    {"Interface mode",
     "操作モード"},
    {"Easy",
     "かんたん"},
    {"All controls and diagnostics.",
     "すべての設定と診断を表示します。"},
    {"Everyday controls. Settings are preserved.",
     "基本操作を表示します。設定は保持されます。"},
    {"Your next adventure",
     "次の冒険へ"},
    {"Choose a look. Check your setup. Start playing.",
     "スタイルを選び、設定を確認して、ゲームを始めましょう。"},
    {"Discard changes",
     "変更を破棄"},
    {"Settings saved.",
     "設定を保存しました。"},
    {"Could not save settings. Check folder permissions and try again.",
     "設定を保存できません。フォルダーのアクセス権を確認して再試行してください。"},
    {"Cancel",
     "キャンセル"},
    {"Status",
     "ステータス"},
    {"Setup",
     "セットアップ"},
    {"Checks",
     "チェック"},
    {"Tuning",
     "調整"},
    {"Log",
     "ログ"},
    {"Neural rendering for World of Warcraft, from outside the game process",
     "World of Warcraft のためのニューラルレンダリング。ゲームのプロセスの外から"},
    {"Stop overlay",
     "オーバーレイを停止"},
    {"Start overlay",
     "オーバーレイを開始"},
    {"Before you use this",
     "ご利用の前に"},
    {"This sidecar never loads code into Wow.exe. That is what makes it safe, and "
     "it is checked automatically every time it is built.\n\nReShade placed next "
     "to Wow.exe is a different thing entirely, and Blizzard bans accounts for "
     "it. This tool will refuse to install there and will refuse to run if it "
     "finds an injector in your WoW folder.\n\nNo third-party tool can promise "
     "you will never be banned. What this one can promise is that it does not do "
     "any of the things Blizzard bans people for.",
     "このツールは Wow.exe にコードを一切読み込みません。それが安全である理由であり、ビルドのたびに自動で検証されています。\n\nReShade "
     "を Wow.exe の隣に置くのはまったく別の話で、Blizzard はそれを理由にアカウントを BAN "
     "します。このツールはそこへのインストールを拒否し、WoW フォルダーにインジェクターを見つけた場合は起動も拒否します。\n\nBAN "
     "されないことを約束できるサードパーティ製ツールはありません。このツールが約束できるのは、Blizzard が BAN "
     "の理由とすることを何ひとつ行わないということです。"},
    {"I understand",
     "理解しました"},
    {"Live",
     "ライブ"},
    {"OVERLAY FPS",
     "オーバーレイ FPS"},
    {"LATENCY p50",
     "レイテンシ p50"},
    {"LATENCY p99",
     "レイテンシ p99"},
    {"CAPTURED FPS",
     "キャプチャ FPS"},
    {"WoW: borderless",
     "WoW：ボーダーレス"},
    {"WoW: not borderless",
     "WoW：ボーダーレスではない"},
    {"WoW: not running",
     "WoW：起動していない"},
    {"Overlay: running",
     "オーバーレイ：実行中"},
    {"Overlay: stopped",
     "オーバーレイ：停止"},
    {"READY",
     "準備完了"},
    {"CHECK",
     "要確認"},
    {"BLOCKED",
     "ブロック"},
    {"Hide overlay (A/B compare)",
     "オーバーレイを隠す（A/B 比較）"},
    {"Show overlay",
     "オーバーレイを表示"},
    {"Hide HUD",
     "HUD を隠す"},
    {"Show HUD",
     "HUD を表示"},
    {"Hiding the overlay uncovers the untouched game without stopping capture.",
     "オーバーレイを隠すと、キャプチャを止めずに未処理のゲーム画面が見えます。"},
    {"GPU MEMORY USED BY THE SIDECAR",
     "このツールが使う GPU メモリ"},
    {"  --  SPILLING",
     "  ―  あふれ"},
    {"This is the sidecar's own share, not the whole card. More of it would not "
     "be faster -- the pass allocates what it needs. The number that matters is "
     "whether any has spilled.",
     "これはこのツール自身の使用分で、カード全体ではありません。増やしても速くはなりません。処理は必要な分だけ確保します。重要なのは、あふれが出ているかどうか"
     "です。"},
    {"WHERE THE FRAME GOES",
     "フレーム時間の内訳"},
    {"Frames",
     "フレーム"},
    {"%llu presented, %llu dropped",
     "表示 %llu、破棄 %llu"},
    {"Pass",
     "処理"},
    {"Runtime",
     "ランタイム"},
    {"Verdict",
     "判定"},
    {"playable",
     "快適"},
    {"marginal",
     "ぎりぎり"},
    {"too slow",
     "遅すぎる"},
    {"The overlay is starting. Numbers appear after the first few frames.",
     "オーバーレイを起動中です。最初の数フレームの後に数値が表示されます。"},
    {"Nothing running.",
     "実行中のものはありません。"},
    {"The card is full, so the driver is moving resources to system memory and "
     "every frame waits on the PCIe bus. It shows below as a huge GPU wait with "
     "the GPU nearly idle, which is easy to mistake for a slow neural "
     "pass.\n\nClose what else is using the card -- browsers, streaming and "
     "capture tools, anything compositing a second monitor -- and lower the "
     "game's texture quality. Nothing in this tool can make room.",
     "カードのメモリが満杯のため、ドライバーがリソースをシステムメモリへ移し、毎フレーム PCIe バスを待っています。下の表示では GPU "
     "がほぼ遊んでいるのに GPU 待ちが極端に長くなり、ニューラル処理が遅いのと見分けがつきにくい状態です。\n\nブラウザー、配信・録画ツール、2 "
     "台目のモニターを合成しているものなど、カードを使う他のものを閉じ、ゲームのテクスチャ品質を下げてください。このツールでは空きを作れません。"},
    {"This is the desktop compositor's rate, not the sidecar's and not the game's "
     "-- the game may well be running far faster. It is usually set by your "
     "monitor's refresh rate and, on a multi-monitor setup with mismatched "
     "refresh rates, by the slowest one. Nothing in this tool can raise it.",
     "これはデスクトップ "
     "コンポジターのレートで、このツールのものでもゲームのものでもありません。ゲーム自体はもっと速く動いているかもしれません。通常はモニターのリフレッシュレー"
     "トで決まり、レートの違う複数モニター環境では最も遅いモニターで決まります。このツールでは上げられません。"},
    {"The game is competing for the GPU. Measured on the development machine, the "
     "same scene ran at 11.7 fps with the game focused and 35.2 fps with it in "
     "the background, purely because an unfocused game throttles itself and hands "
     "the card back.\n\nCap the game's frame rate. This costs nothing: the "
     "overlay can never show more than the capture rate above, so every frame the "
     "game renders beyond that is discarded before it reaches here.",
     "ゲームが GPU を奪い合っています。開発マシンでの計測では、同じシーンがゲームを前面にすると 11.7 fps、背面にすると 35.2 fps "
     "でした。フォーカスを失ったゲームは自ら速度を落としてカードを譲るためです。\n\nゲームのフレームレートに上限を設定してください。代償はありません。オー"
     "バーレイは上のキャプチャレートを超えて表示できないので、それを超えてゲームが描いたフレームはここに届く前に捨てられます。"},
    {"The overlay is presenting close to every frame Windows hands it, and there "
     "is memory to spare. Nothing to fix here.",
     "オーバーレイは Windows から渡されるほぼすべてのフレームを表示しており、メモリにも余裕があります。ここで直すことはありません。"},
    {"Some checks are failing. Open Checks to see what.",
     "失敗しているチェックがあります。「チェック」を開いて確認してください。"},
    {"Files are missing. Open Setup to install them.",
     "ファイルが不足しています。「セットアップ」を開いてインストールしてください。"},
    {"Start World of Warcraft in borderless windowed mode, then press Start "
     "overlay.",
     "World of Warcraft をボーダーレスウィンドウで起動し、「オーバーレイを開始」を押してください。"},
    {"Press Start overlay.",
     "「オーバーレイを開始」を押してください。"},
    {"Playing with the overlay up",
     "オーバーレイ使用中のプレイ"},
    {"The overlay covers the game completely and passes every click straight "
     "through to it, so play normally. It never takes focus, so whatever had the "
     "keyboard keeps it -- if the game is not responding, alt-tab to World of "
     "Warcraft once.\n\nCtrl+Alt+Backspace takes the overlay down from anywhere, "
     "without needing this window.",
     "オーバーレイはゲームを完全に覆い、すべてのクリックをそのままゲームへ通すので、普段どおりにプレイできます。フォーカスは決して奪わないため、キーボードを持"
     "っていたウィンドウがそのまま保持します。ゲームが反応しない場合は、一度 Alt+Tab で World of Warcraft "
     "に切り替えてください。\n\nCtrl+Alt+Backspace で、このウィンドウなしでもどこからでもオーバーレイを閉じられます。"},
    {"Required files",
     "必要なファイル"},
    {"Three files have to sit next to the sidecar. None of them is ours to "
     "redistribute and nothing here downloads anything -- neither binary in this "
     "project can reach the network at all. Fetch them yourself, then point this "
     "at them.",
     "3 "
     "つのファイルをこのツールの隣に置く必要があります。どれも私たちが再配布できるものではなく、ここでは何もダウンロードしません。このプロジェクトのどちらの実"
     "行ファイルもネットワークに一切接続できません。各自で入手し、ここで指定してください。"},
    {"INSTALLED",
     "インストール済み"},
    {"MISSING",
     "不足"},
    {"OPTIONAL",
     "任意"},
    {"Wanted as %s   |   Source: %s",
     "配置名 %s   |   入手元：%s"},
    {"Replace...",
     "置き換え..."},
    {"Choose file...",
     "ファイルを選択..."},
    {"Remove",
     "削除"},
    {"Deletes the files listed above from this folder, and nothing else. It never "
     "touches a WoW installation. The sidecar's own two executables stay; delete "
     "the folder to be rid of them.",
     "上に挙げたファイルだけをこのフォルダーから削除します。WoW のインストールには一切触れません。このツール自身の 2 "
     "つの実行ファイルは残るので、完全に消すにはフォルダーごと削除してください。"},
    {"Also remove settings and logs",
     "設定とログも削除"},
    {"Yes, remove them",
     "はい、削除します"},
    {"Remove installed files",
     "インストールしたファイルを削除"},
    {"Stop the overlay first -- the files are in use.",
     "先にオーバーレイを停止してください。ファイルが使用中です。"},
    {"%zu file(s) would go.",
     "%zu 個のファイルが削除されます。"},
    {"That file no longer exists.",
     "そのファイルはもう存在しません。"},
    {"That is not a file.",
     "それはファイルではありません。"},
    {"Already installed.",
     "インストール済みです。"},
    {"Could not copy it in: ",
     "コピーできませんでした："},
    {"Installed ",
     "インストールしました："},
    {"Could not remove ",
     "削除できませんでした："},
    {". Stop the overlay and close anything using it, then try again.",
     "。オーバーレイを停止し、使用中のものを閉じてから再試行してください。"},
    {"Removed ",
     "削除しました："},
    {" file(s).",
     " 個のファイル。"},
    {"DLSS 5 neural rendering runtime",
     "DLSS 5 ニューラルレンダリング ランタイム"},
    {"The neural network itself. On an RTX 40 card this must be a build patched "
     "for Ada; the stock runtime is Blackwell-only and fails at feature creation "
     "with no diagnostic.",
     "ニューラルネットワーク本体です。RTX 40 のカードでは Ada 向けにパッチされたビルドが必要です。純正のランタイムは Blackwell "
     "専用で、機能の作成時に何の診断もなく失敗します。"},
    {"ReShade, with add-on support",
     "アドオン対応版 ReShade"},
    {"Hosts the add-on inside the sidecar's own process. The add-on-enabled build "
     "is required; the plain one loads no add-ons at all.",
     "このツール自身のプロセス内でアドオンをホストします。アドオン対応ビルドが必要で、通常版はアドオンを一切読み込みません。"},
    {"RenoDX DLSS 5 add-on",
     "RenoDX DLSS 5 アドオン"},
    {"Detours the sidecar's own NGX calls and substitutes neural-rendered output. "
     "This is what makes the pass neural rather than a plain DLAA.",
     "このツール自身の NGX 呼び出しを横取りし、ニューラルレンダリングの出力に差し替えます。これにより処理が単なる DLAA "
     "ではなくニューラルになります。"},
    {"DLSS upscaling runtime",
     "DLSS アップスケーリング ランタイム"},
    {"Optional. Only consulted if the add-on's work-in-progress upscaling path is "
     "switched on; neural rendering itself does not need it.",
     "任意。アドオンの開発中のアップスケーリングを有効にした場合にのみ使われます。ニューラルレンダリング自体には不要です。"},
    {"System checks",
     "システムチェック"},
    {"Nothing here opens, reads, writes or hooks the game process. The import "
     "table of every binary is checked against that claim at build time.",
     "ここにあるものは、ゲームのプロセスを開く・読む・書く・フックすることは一切ありません。すべての実行ファイルのインポートテーブルが、ビルド時にこの主張に照"
     "らして検証されます。"},
    {"WoW folder (used only to scan filenames for injectors)",
     "WoW フォルダー（インジェクターのファイル名を調べるためだけに使用）"},
    {"Browse...",
     "参照..."},
    {"Detect",
     "検出"},
    {"Re-run checks",
     "チェックを再実行"},
    {"Detected from Battle.net's own uninstall entry. Point this at the folder "
     "Wow.exe sits in, not its parent: an injector has to be next to the "
     "executable to be loaded by it. Nothing inside is opened -- only the file "
     "names are read.",
     "Battle.net 自身のアンインストール情報から検出しました。親フォルダーではなく、Wow.exe "
     "があるフォルダーを指定してください。インジェクターは実行ファイルの隣になければ読み込まれません。中身は開かず、ファイル名だけを読み取ります。"},
    {"Graphics adapter",
     "グラフィックス アダプター"},
    {"No NVIDIA adapter found.",
     "NVIDIA アダプターが見つかりません。"},
    {"This sidecar needs an NVIDIA RTX 40 or RTX 50 card.",
     "このツールには NVIDIA RTX 40 または RTX 50 が必要です。"},
    {"RTX 40 (Ada) or RTX 50 (Blackwell) is required. Older cards are refused "
     "rather than run badly.",
     "RTX 40（Ada）または RTX 50（Blackwell）が必要です。古いカードは不安定に動かすのではなく、拒否されます。"},
    {"Display driver",
     "ディスプレイ ドライバー"},
    {"No NVIDIA adapter to query.",
     "問い合わせる NVIDIA アダプターがありません。"},
    {"Install an NVIDIA RTX 40 or RTX 50 card.",
     "NVIDIA RTX 40 または RTX 50 を取り付けてください。"},
    {"User-mode driver ",
     "ユーザーモード ドライバー "},
    {"Could not read the driver version.",
     "ドライバーのバージョンを読み取れませんでした。"},
    {"Not fatal. Update to a current NVIDIA driver if capture misbehaves.",
     "致命的ではありません。キャプチャがおかしい場合は最新の NVIDIA ドライバーに更新してください。"},
    {"Windows version",
     "Windows のバージョン"},
    {"Could not read the Windows build number.",
     "Windows のビルド番号を読み取れませんでした。"},
    {"Not fatal, but this project is only supported on Windows 11.",
     "致命的ではありませんが、このプロジェクトは Windows 11 のみサポートしています。"},
    {"Build ",
     "ビルド "},
    {"Windows 11 is required: the overlay depends on compositor behaviour that "
     "Windows 10 does not provide.",
     "Windows 11 が必要です。オーバーレイは Windows 10 にないコンポジターの動作に依存しています。"},
    {"Display refresh rate",
     "ディスプレイのリフレッシュレート"},
    {"Could not read the current display mode.",
     "現在のディスプレイ モードを読み取れませんでした。"},
    {"Not fatal. Check your monitor settings if pacing looks wrong.",
     "致命的ではありません。フレームのペースがおかしい場合はモニター設定を確認してください。"},
    {"Below 120 Hz the overlay's added latency is a larger share of the frame. It "
     "will still run.",
     "120 Hz 未満では、オーバーレイが加える遅延がフレームに占める割合が大きくなります。それでも動作します。"},
    {"Neural runtime",
     "ニューラル ランタイム"},
    {"nvngx_dlssnr.dll not found next to the sidecar.",
     "このツールの隣に nvngx_dlssnr.dll が見つかりません。"},
    {"Optional until the neural pass ships. Without it the pipeline runs the "
     "passthrough pass.",
     "ニューラル処理の提供までは任意です。なければパイプラインはパススルー処理で動きます。"},
    {"Check the file is not locked by another process, and that the sidecar has "
     "permission to read it.",
     "ファイルが他のプロセスにロックされていないか、このツールに読み取り権限があるか確認してください。"},
    {"Supply a runtime built for this GPU, or the neural pass will fall back to "
     "passthrough.",
     "この GPU 向けにビルドされたランタイムを用意してください。ないとニューラル処理はパススルーに戻ります。"},
    {"The pass will still try this build. If it fails, quote the SHA-256 above "
     "when reporting it.",
     "処理はこのビルドでも試行します。失敗した場合は、報告の際に上の SHA-256 を添えてください。"},
    {"ReShade host (optional)",
     "ReShade ホスト（任意）"},
    {"No ReShade host alongside the sidecar.",
     "このツールの隣に ReShade ホストがありません。"},
    {"Only needed for the ReShade-hosted neural pass. Install ReShade against the "
     "sidecar so it lands as dxgi.dll. Never place ReShade next to Wow.exe.",
     "ReShade でホストするニューラル処理にのみ必要です。ReShade をこのツールに対してインストールし、dxgi.dll "
     "として配置してください。ReShade を Wow.exe の隣に置いてはいけません。"},
    {"World of Warcraft window",
     "World of Warcraft のウィンドウ"},
    {"WoW is not running.",
     "WoW が起動していません。"},
    {"Start the game, then run the probes again.",
     "ゲームを起動してから、チェックを再実行してください。"},
    {" borderless windowed",
     " ボーダーレスウィンドウ"},
    {" windowed with a border, or exclusive fullscreen",
     " 枠付きウィンドウ、または排他的フルスクリーン"},
    {"Set WoW to borderless windowed. Exclusive fullscreen has no compositor "
     "surface to capture and yields black frames.",
     "WoW をボーダーレスウィンドウに設定してください。排他的フルスクリーンにはキャプチャできるコンポジター面がなく、真っ黒なフレームになります。"},
    {"Injector scan of the WoW folder",
     "WoW フォルダーのインジェクター検査"},
    {"No WoW folder set, so nothing was scanned.",
     "WoW フォルダーが設定されていないため、何も検査していません。"},
    {"Point the manager at your WoW folder so it can check for injectors before "
     "launching.",
     "起動前にインジェクターを検査できるよう、マネージャーに WoW フォルダーを指定してください。"},
    {"No injector loaders found.",
     "インジェクターのローダーは見つかりませんでした。"},
    {"Found: ",
     "検出："},
    {"Remove these from your WoW folder. Blizzard bans accounts for in-process "
     "injectors, and this tool refuses to run alongside one.",
     "これらを WoW フォルダーから削除してください。Blizzard はプロセス内インジェクターを理由にアカウントを BAN "
     "します。このツールはインジェクターと一緒には動作しません。"},
    {"Sidecar install location",
     "このツールのインストール場所"},
    {"Move the sidecar outside your WoW folder. Anything sitting next to Wow.exe "
     "looks like an injector, which is the one thing this design exists to avoid.",
     "このツールを WoW フォルダーの外へ移動してください。Wow.exe "
     "の隣にあるものはすべてインジェクターに見えます。それこそがこの設計が避けようとしていることです。"},
    {" is the ",
     " は "},
    {" runtime, version ",
     " ランタイム、バージョン "},
    {" could not be read, so it has no digest.",
     " を読み取れなかったため、ダイジェストがありません。"},
    {" is not a build this manifest knows. Its SHA-256 is ",
     " はこのマニフェストが知らないビルドです。SHA-256 は "},
    {" -- quote that when reporting it.",
     " です。報告の際に添えてください。"},
    {"This GPU (",
     "この GPU（"},
    {") is outside the supported matrix; neural rendering needs Ada or Blackwell.",
     "）はサポート対象外です。ニューラルレンダリングには Ada か Blackwell が必要です。"},
    {"This is the stock runtime, which is built for Blackwell. On an Ada card "
     "neural-rendering feature creation fails with no explanation. An "
     "Ada-compatible build of nvngx_dlssnr.dll is required.",
     "これは Blackwell 向けにビルドされた純正ランタイムです。Ada のカードではニューラルレンダリング機能の作成が理由もなく失敗します。Ada "
     "対応の nvngx_dlssnr.dll が必要です。"},
    {" runtime does not run on ",
     " ランタイムは次の環境では動きません："},
    {"Choose a look",
     "見た目を選ぶ"},
    {"IN USE",
     "使用中"},
    {"Custom -- your settings do not match any preset.",
     "カスタム：現在の設定はどのプリセットとも一致しません。"},
    {"Click one above to go back to a tested combination. Nothing is selected "
     "because the individual settings below have been moved away from all four.",
     "上のいずれかをクリックすると、検証済みの組み合わせに戻せます。下の個別設定が 4 つのどれからも外れているため、何も選択されていません。"},
    {"Pick one. Every setting below is chosen for you, and the combinations here "
     "are ones that have actually been run -- unlike most of the arrangements you "
     "can reach by moving sliders individually.",
     "ひとつ選んでください。下の設定はすべて自動で決まり、ここにある組み合わせは実際に試したものです。スライダーを個別に動かして作れる組み合わせの大半はそうで"
     "はありません。"},
    {"Recommended",
     "おすすめ"},
    {"The tuned default. Start here.",
     "調整済みの既定値。まずはここから。"},
    {"Full neural intensity with the CNN F render preset, which clamps temporal "
     "history hard -- the right choice when motion vectors are estimated from "
     "colour rather than rendered by the game.",
     "CNN F レンダー "
     "プリセットでニューラル強度を最大に。時間方向の履歴を強く制限するので、モーションベクトルをゲームが描くのではなく色から推定する場合に適しています。"},
    {"Softer",
     "控えめ"},
    {"Half strength. Use if the picture looks over-processed.",
     "強度半分。処理しすぎに見える場合に。"},
    {"The same pipeline with the neural result mixed in at 60%. Cheaper on the "
     "eyes for interface-heavy scenes, and the first thing to try if faces or "
     "text look waxy.",
     "同じパイプラインで、ニューラル結果を 60% だけ混ぜます。UI の多い場面で目に優しく、顔や文字がろう人形のように見える場合にまず試すもの。"},
    {"Most stable",
     "最も安定"},
    {"For smearing, or flicker on flames and lights.",
     "残像や、炎・光のちらつきに。"},
    {"Switches to CNN E, which clamps temporal history hardest, and eases the "
     "intensity. This is the preset for when motion looks smeared -- the "
     "estimated motion vectors are being confidently wrong and this contains them.",
     "時間方向の履歴を最も強く制限する CNN E "
     "に切り替え、強度を下げます。動きに残像が出るときのプリセットです。推定したモーションベクトルが自信満々に間違っているのを抑え込みます。"},
    {"Off (A/B baseline)",
     "オフ（A/B 基準）"},
    {"Capture and present, untouched.",
     "キャプチャして表示するだけ。無加工。"},
    {"No neural work at all, on the same capture and present path. This is the "
     "honest comparison: whatever you see here is what the overlay costs you "
     "before any neural rendering happens.",
     "ニューラル処理は一切なし。キャプチャと表示の経路は同じです。これが正直な比較で、ここで見えるものがニューラルレンダリング以前のオーバーレイ自体のコストで"
     "す。"},
    {"Save settings",
     "設定を保存"},
    {"Changes are not saved yet.",
     "変更はまだ保存されていません。"},
    {"Restart the overlay to apply.",
     "オーバーレイを再起動すると反映されます。"},
    {"Every individual setting",
     "すべての個別設定"},
    {"Nothing in here is needed for normal use.",
     "通常の利用ではここは必要ありません。"},
    {"Pipeline",
     "パイプライン"},
    {"These are written to sidecar.toml, and the neural ones are projected into "
     "ReShade.ini where the add-on reads them. The add-on reads that file once, "
     "when it loads, so a change reaches the picture at the overlay's next start "
     "-- not while it runs.",
     "これらは sidecar.toml に書き込まれ、ニューラル関連はアドオンが読む ReShade.ini "
     "にも反映されます。アドオンはこのファイルを読み込み時に一度だけ読むので、変更が画面に届くのは実行中ではなく、次にオーバーレイを起動したときです。"},
    {"Neural pass",
     "ニューラル処理"},
    {"passthrough -- capture and present, untouched",
     "passthrough ― キャプチャして表示するだけ、無加工"},
    {"reshade -- DLSS 5 neural rendering",
     "reshade ― DLSS 5 ニューラルレンダリング"},
    {"Passthrough is the honest A/B baseline: the same capture and present path "
     "with no neural work in it at all.",
     "パススルーは正直な A/B 基準です。同じキャプチャと表示の経路で、ニューラル処理は一切ありません。"},
    {"DLSS preset",
     "DLSS プリセット"},
    {"Optical flow grid",
     "オプティカルフローのグリッド"},
    {"1 -- finest, most expensive",
     "1 ― 最も細かく、最も重い"},
    {"4 -- default",
     "4 ― 既定"},
    {"Pixels per estimated motion vector. Finer costs more and is not obviously "
     "better: the vectors are estimated from colour, so a finer grid can sharpen "
     "the estimate or the error equally.",
     "推定モーションベクトル 1 "
     "つあたりのピクセル数。細かいほど重く、良くなるとは限りません。ベクトルは色から推定するため、細かいグリッドは推定も誤差も同じように鋭くしえます。"},
    {"Synthetic depth",
     "合成深度"},
    {"There is no real depth buffer to capture out of the composited frame, so a "
     "constant plane is bound instead. It costs temporal stability under motion "
     "rather than preventing NR from running; this dial is worth a try if motion "
     "smears.",
     "合成済みのフレームからは本物の深度バッファを取得できないため、代わりに一定の平面を割り当てます。動きの中での時間的安定性は犠牲になりますが、NR "
     "の動作は妨げません。動きに残像が出るなら試す価値のある設定です。"},
    {"Neural rendering strength",
     "ニューラルレンダリングの強さ"},
    {"Passed straight through to the RenoDX add-on. The add-on owns what these "
     "mean; we only carry them.",
     "RenoDX アドオンにそのまま渡されます。意味を決めるのはアドオンで、私たちは運ぶだけです。"},
    {"Intensity",
     "強度"},
    {"How much of the neural result is mixed in. Start here.",
     "ニューラル結果をどれだけ混ぜるか。まずはここから。"},
    {"Add-on preset",
     "アドオン プリセット"},
    {"Style",
     "スタイル"},
    {"Colour strength",
     "色の強さ"},
    {"At zero the add-on's colour handling collapses to black, so this is not a "
     "subtle dial.",
     "0 にするとアドオンの色処理が黒につぶれます。微調整向きの設定ではありません。"},
    {"HDR transfer strength",
     "HDR 伝達の強さ"},
    {"Paper-white scale",
     "ペーパーホワイトの倍率"},
    {"Both only matter on an HDR display. The sidecar captures SDR today, so "
     "leave them at 1.00 unless you are experimenting.",
     "どちらも HDR ディスプレイでのみ意味があります。このツールは現在 SDR でキャプチャするので、実験するのでなければ 1.00 "
     "のままにしてください。"},
    {"These three have no documented default, so they are written only once you "
     "move them. Clearing the box returns them to untouched, which leaves "
     "whatever the add-on does by itself.",
     "この 3 つには公開された既定値がないため、動かしたときだけ書き込まれます。欄を空にすると未変更に戻り、アドオン自身の動作に任せます。"},
    {"Enable the add-on's upscaling (work in progress)",
     "アドオンのアップスケーリングを有効化（開発中）"},
    {"The add-on marks this unfinished, and the sidecar feeds it a "
     "native-resolution DLAA contract, so it usually reports that it fell back to "
     "native. Off is the tested path.",
     "アドオンはこれを未完成としており、このツールはネイティブ解像度の DLAA "
     "条件で渡すため、通常はネイティブに戻ったと報告されます。オフが検証済みの経路です。"},
    {"Hook mode",
     "フックモード"},
    {"0 turns neural rendering off entirely, 1 adds Streamline hooks, 2 is NGX "
     "only. Two is what this sidecar wants: it makes the NGX calls itself and "
     "there is no Streamline in the process.",
     "0 はニューラルレンダリングを完全にオフ、1 は Streamline のフックを追加、2 は NGX のみ。このツールが求めるのは 2 です。NGX "
     "呼び出しを自分で行い、プロセス内に Streamline はありません。"},
    {"Overlay",
     "オーバーレイ"},
    {"Advanced",
     "詳細"},
    {"Local structure",
     "ローカル構造"},
    {"How hard the model works on fine surface detail -- stonework, cloth weave, "
     "wood grain. Raising it sharpens texture and also sharpens whatever the "
     "model got wrong about it.",
     "石積み、布の織り目、木目など、表面の細部にモデルがどれだけ手を加えるか。上げると質感が鋭くなり、モデルが誤解した部分も鋭くなります。"},
    {"Local tone",
     "ローカルトーン"},
    {"Local contrast: how far the model pushes light against dark within a small "
     "area. This is the dial most likely to change the mood of a scene rather "
     "than its detail.",
     "局所コントラスト：狭い範囲で明暗をどこまで押し広げるか。細部よりも場面の雰囲気を変えやすい設定です。"},
    {"Skin structure",
     "肌の構造"},
    {"Faces and skin specifically. The one people reach for after watching a "
     "comparison video, and the one most likely to look wrong when overdone -- "
     "skin is where anybody spots a mistake.",
     "顔と肌に特化した設定。比較動画を見た後に誰もが触りたくなり、やりすぎると最もおかしく見えるもの。肌の間違いは誰にでも分かります。"},
    {"The strip of numbers the overlay draws in its own top-left corner: frame "
     "rate, latency, which pass is running and how many frames were dropped. It "
     "is drawn by the overlay, not by the game, so it never reaches a screenshot "
     "the game takes.",
     "オーバーレイが自分の左上に描く数値の帯：フレームレート、レイテンシ、実行中の処理、破棄されたフレーム数。ゲームではなくオーバーレイが描くので、ゲームのス"
     "クリーンショットには決して写りません。"},
    {"Whether the overlay covers the game the moment it launches. Off starts it "
     "hidden, which is the honest way to look at the untouched frame first and "
     "then bring the neural pass in over the top of it.",
     "起動した瞬間にオーバーレイがゲームを覆うかどうか。オフにすると非表示で始まります。まず無加工の画面を見てから、その上にニューラル処理を重ねる正直な方法で"
     "す。"},
    {"CNN F. The default here: clamps history hard, which suits estimated motion "
     "vectors.",
     "CNN F。ここでの既定値。履歴を強く制限し、推定モーションベクトルに向いています。"},
    {"CNN E. Clamps hardest. Try this first if motion smears or flames and lights "
     "flicker.",
     "CNN E。最も強く制限します。動きに残像が出たり炎や光がちらつく場合にまず試してください。"},
    {"Transformer K. The SDK default for DLAA. Sharpest when the vectors are "
     "trustworthy.",
     "Transformer K。DLAA の SDK 既定値。ベクトルが信頼できるときに最も鮮明です。"},
    {"Transformer J. The older transformer preset.",
     "Transformer J。以前の Transformer プリセット。"},
    {"Whatever the runtime picks for itself.",
     "ランタイム自身が選ぶもの。"},
    {"Show the HUD",
     "HUD を表示"},
    {"Show the overlay on start",
     "起動時にオーバーレイを表示"},
    {"Reset to defaults",
     "既定値に戻す"},
    {"%llu earlier line(s) dropped",
     "以前の %llu 行を破棄しました"},
    {"Last error",
     "最後のエラー"},
    {"The overlay (sidecar.log)",
     "オーバーレイ（sidecar.log）"},
    {"This manager",
     "このマネージャー"},
    {"The overlay has not written anything yet.",
     "オーバーレイはまだ何も書き込んでいません。"},
    {"Window class not found.",
     "ウィンドウクラスが見つかりません。"},
    {"World of Warcraft is not running.",
     "World of Warcraft が起動していません。"},
    {"World of Warcraft must run in borderless windowed mode.\nExclusive "
     "fullscreen has no compositor surface to capture.",
     "World of Warcraft "
     "はボーダーレスウィンドウで実行する必要があります。\n排他的フルスクリーンにはキャプチャできるコンポジター面がありません。"},
    {"%hs is not supported. RTX 40 or RTX 50 required.",
     "%hs はサポートされていません。RTX 40 または RTX 50 が必要です。"},
    {"Failed to create the pipeline.",
     "パイプラインを作成できませんでした。"},
    {"An overlay is already running.\nStop it from the manager before starting "
     "another.",
     "オーバーレイはすでに実行中です。\n別のものを開始する前に、マネージャーから停止してください。"},
    {"The graphics device was reset and could not be rebuilt.",
     "グラフィックス デバイスがリセットされ、再構築できませんでした。"},
    {"Hotkeys",
     "ホットキー"},
    {"off",
     "オフ"},
    {"Start or stop the overlay (while this window is open)",
     "オーバーレイの開始・停止（このウィンドウが開いている間）"},
    {"Show or hide the overlay: instant A/B against the untouched game",
     "オーバーレイの表示・非表示：無加工のゲームと即座に A/B 比較"},
    {"Show or hide the frame-time HUD",
     "フレーム時間 HUD の表示・非表示"},
    {"Panic: take the overlay down, always",
     "緊急：いつでもオーバーレイを閉じる"},
    {"Change them on the Tuning page.",
     "「調整」ページで変更できます。"},
    {"Written like Ctrl+Alt+D or Shift+Alt+F9. Each needs Ctrl, Alt or Win, "
     "because Windows takes the combination away from the game. Leave one empty "
     "to switch it off.",
     "Ctrl+Alt+D や Shift+Alt+F9 のように書きます。Windows がその組み合わせをゲームから奪うため、どれも "
     "Ctrl、Alt、Win のいずれかが必要です。空欄にするとオフになります。"},
    {"Start / stop overlay",
     "オーバーレイ開始 / 停止"},
    {"Show / hide overlay",
     "オーバーレイ表示 / 非表示"},
    {"Show / hide HUD",
     "HUD 表示 / 非表示"},
    {"not a key combination",
     "キーの組み合わせではありません"},
    {"Language",
     "言語"},
    {"Interface theme",
     "インターフェースのテーマ"},
    {"Stormwind",
     "ストームウィンド"},
    {"Quest log",
     "クエストログ"},
    {"Dragonflight",
     "ドラゴンフライト"},
    {"Neural strength",
     "ニューラル強度"},
    {"How many times DLSS 5 runs over each frame. One pass is subtle. Two or "
     "three push the picture further from the original -- closer to the heavily "
     "processed look in demonstration videos -- and each extra pass costs another "
     "full neural pass of GPU time.",
     "各フレームに DLSS 5 を何回かけるか。1 回は控えめです。2 回や 3 "
     "回では元の画面からさらに離れ、デモ動画のような強く処理された見た目に近づきます。1 回増やすごとに、ニューラル処理 1 回分の GPU "
     "時間がかかります。"},
    {"1x  Natural",
     "1x  ナチュラル"},
    {"2x  Stronger",
     "2x  強め"},
    {"3x  Strongest",
     "3x  最強"},
    {"Closest to the game",
     "ゲームに最も近い"},
    {"About twice the GPU time",
     "GPU 時間は約 2 倍"},
    {"About three times the GPU time",
     "GPU 時間は約 3 倍"},
    {"Four passes, set in sidecar.toml. Pick one above to go back.",
     "4 回。sidecar.toml で設定されています。上から選ぶと戻せます。"},
    {"The Off preset runs no neural pass, so this has no effect until you pick "
     "another look.",
     "「オフ」プリセットはニューラル処理を行わないため、別の見た目を選ぶまでこの設定は効きません。"},
};

const size_t kJapaneseTableSize = sizeof(kJapaneseTable) / sizeof(kJapaneseTable[0]);

}  // namespace sidecar
