#include "core/I18nTable.h"

// Turkish interface text. Generated by tools/gen_translation_table.py;
// the conventions are the Russian table's (I18nRu.cpp): keys are the English
// source text exactly, format specifiers keep their order, and file names,
// add-on key names and the log are never translated.

namespace sidecar {

const TranslationPair kTurkishTable[] = {
    {"Status",
     "Durum"},
    {"Setup",
     "Kurulum"},
    {"Checks",
     "Denetimler"},
    {"Tuning",
     "Ayarlar"},
    {"Log",
     "Günlük"},
    {"Neural rendering for World of Warcraft, from outside the game process",
     "World of Warcraft için nöral işleme, oyun sürecinin dışından"},
    {"Stop overlay",
     "Katmanı durdur"},
    {"Start overlay",
     "Katmanı başlat"},
    {"Before you use this",
     "Kullanmadan önce"},
    {"This sidecar never loads code into Wow.exe. That is what makes it safe, and "
     "it is checked automatically every time it is built.\n\nReShade placed next "
     "to Wow.exe is a different thing entirely, and Blizzard bans accounts for "
     "it. This tool will refuse to install there and will refuse to run if it "
     "finds an injector in your WoW folder.\n\nNo third-party tool can promise "
     "you will never be banned. What this one can promise is that it does not do "
     "any of the things Blizzard bans people for.",
     "Bu yardımcı program Wow.exe içine asla kod yüklemez. Onu güvenli yapan "
     "budur ve her derlemede otomatik olarak denetlenir.\n\nWow.exe'nin yanına "
     "konan ReShade bambaşka bir şeydir ve Blizzard bunun için hesap yasaklar. Bu "
     "araç oraya kurulmayı reddeder ve WoW klasörünüzde bir enjektör bulursa "
     "çalışmayı reddeder.\n\nHiçbir üçüncü taraf araç asla yasaklanmayacağınızı "
     "vaat edemez. Bu aracın vaat edebileceği, Blizzard'ın yasakladığı şeylerin "
     "hiçbirini yapmamasıdır."},
    {"I understand",
     "Anladım"},
    {"Live",
     "Canlı"},
    {"OVERLAY FPS",
     "KATMAN FPS"},
    {"LATENCY p50",
     "GECİKME p50"},
    {"LATENCY p99",
     "GECİKME p99"},
    {"CAPTURED FPS",
     "YAKALANAN FPS"},
    {"WoW: borderless",
     "WoW: kenarlıksız pencere"},
    {"WoW: not borderless",
     "WoW: kenarlıksız değil"},
    {"WoW: not running",
     "WoW: çalışmıyor"},
    {"Overlay: running",
     "Katman: çalışıyor"},
    {"Overlay: stopped",
     "Katman: durduruldu"},
    {"READY",
     "HAZIR"},
    {"CHECK",
     "KONTROL ET"},
    {"BLOCKED",
     "ENGELLENDİ"},
    {"Hide overlay (A/B compare)",
     "Katmanı gizle (A/B karşılaştırma)"},
    {"Show overlay",
     "Katmanı göster"},
    {"Hide HUD",
     "HUD'u gizle"},
    {"Show HUD",
     "HUD'u göster"},
    {"Hiding the overlay uncovers the untouched game without stopping capture.",
     "Katmanı gizlemek, yakalamayı durdurmadan oyunun işlenmemiş halini gösterir."},
    {"GPU MEMORY USED BY THE SIDECAR",
     "YARDIMCININ KULLANDIĞI GPU BELLEĞİ"},
    {"  --  SPILLING",
     "  —  TAŞIYOR"},
    {"This is the sidecar's own share, not the whole card. More of it would not "
     "be faster -- the pass allocates what it needs. The number that matters is "
     "whether any has spilled.",
     "Bu, kartın tamamı değil, yalnızca yardımcının payıdır. Daha fazlası onu "
     "hızlandırmazdı; geçiş neye ihtiyacı varsa onu ayırır. Önemli olan, taşan "
     "olup olmadığıdır."},
    {"WHERE THE FRAME GOES",
     "KARE NEREYE GİDİYOR"},
    {"Frames",
     "Kareler"},
    {"%llu presented, %llu dropped",
     "%llu gösterildi, %llu düşürüldü"},
    {"Pass",
     "Geçiş"},
    {"Runtime",
     "Çalışma zamanı"},
    {"Verdict",
     "Karar"},
    {"playable",
     "oynanabilir"},
    {"marginal",
     "sınırda"},
    {"too slow",
     "çok yavaş"},
    {"The overlay is starting. Numbers appear after the first few frames.",
     "Katman başlıyor. Sayılar ilk birkaç kareden sonra görünür."},
    {"Nothing running.",
     "Çalışan bir şey yok."},
    {"The card is full, so the driver is moving resources to system memory and "
     "every frame waits on the PCIe bus. It shows below as a huge GPU wait with "
     "the GPU nearly idle, which is easy to mistake for a slow neural "
     "pass.\n\nClose what else is using the card -- browsers, streaming and "
     "capture tools, anything compositing a second monitor -- and lower the "
     "game's texture quality. Nothing in this tool can make room.",
     "Kart dolu, bu yüzden sürücü kaynakları sistem belleğine taşıyor ve her kare "
     "PCIe veri yolunu bekliyor. Aşağıda GPU neredeyse boştayken çok büyük bir "
     "GPU beklemesi olarak görünür ve yavaş bir nöral geçişle kolayca "
     "karıştırılır.\n\nKartı kullanan diğer şeyleri kapatın — tarayıcılar, yayın "
     "ve kayıt araçları, ikinci bir monitörü birleştiren her şey — ve oyunun doku "
     "kalitesini düşürün. Bu araçtaki hiçbir şey yer açamaz."},
    {"This is the desktop compositor's rate, not the sidecar's and not the game's "
     "-- the game may well be running far faster. It is usually set by your "
     "monitor's refresh rate and, on a multi-monitor setup with mismatched "
     "refresh rates, by the slowest one. Nothing in this tool can raise it.",
     "Bu, masaüstü birleştiricisinin hızıdır; yardımcının da oyunun da değil — "
     "oyun çok daha hızlı çalışıyor olabilir. Genellikle monitörünüzün yenileme "
     "hızına, farklı hızlarda birden fazla monitör varsa en yavaşına bağlıdır. Bu "
     "araçtaki hiçbir şey onu artıramaz."},
    {"The game is competing for the GPU. Measured on the development machine, the "
     "same scene ran at 11.7 fps with the game focused and 35.2 fps with it in "
     "the background, purely because an unfocused game throttles itself and hands "
     "the card back.\n\nCap the game's frame rate. This costs nothing: the "
     "overlay can never show more than the capture rate above, so every frame the "
     "game renders beyond that is discarded before it reaches here.",
     "Oyun GPU için yarışıyor. Geliştirme makinesinde aynı sahne, oyun ön "
     "plandayken 11,7 fps, arka plandayken 35,2 fps çalıştı; sırf odakta olmayan "
     "bir oyun kendini kısıp kartı bıraktığı için.\n\nOyunun kare hızını "
     "sınırlayın. Bunun bir bedeli yok: katman yukarıdaki yakalama hızından "
     "fazlasını asla gösteremez, dolayısıyla oyunun bunun üstünde çizdiği her "
     "kare buraya ulaşmadan atılır."},
    {"The overlay is presenting close to every frame Windows hands it, and there "
     "is memory to spare. Nothing to fix here.",
     "Katman, Windows'un verdiği karelerin neredeyse hepsini gösteriyor ve bellek "
     "yeterli. Burada düzeltilecek bir şey yok."},
    {"Some checks are failing. Open Checks to see what.",
     "Bazı denetimler başarısız. Hangileri olduğunu görmek için Denetimler'i açın."},
    {"Files are missing. Open Setup to install them.",
     "Dosyalar eksik. Kurmak için Kurulum'u açın."},
    {"Start World of Warcraft in borderless windowed mode, then press Start "
     "overlay.",
     "World of Warcraft'ı kenarlıksız pencere modunda başlatın, sonra Katmanı "
     "başlat'a basın."},
    {"Press Start overlay.",
     "Katmanı başlat'a basın."},
    {"Playing with the overlay up",
     "Katman açıkken oynamak"},
    {"The overlay covers the game completely and passes every click straight "
     "through to it, so play normally. It never takes focus, so whatever had the "
     "keyboard keeps it -- if the game is not responding, alt-tab to World of "
     "Warcraft once.\n\nCtrl+Alt+Backspace takes the overlay down from anywhere, "
     "without needing this window.",
     "Katman oyunu tamamen kaplar ve her tıklamayı doğrudan oyuna geçirir, yani "
     "normal oynayın. Asla odak almaz; klavye kimdeyse onda kalır — oyun yanıt "
     "vermiyorsa bir kez Alt+Tab ile World of Warcraft'a geçin.\n\nCtrl+Alt+Geri "
     "Al, bu pencereye gerek kalmadan katmanı her yerden kapatır."},
    {"Required files",
     "Gerekli dosyalar"},
    {"Three files have to sit next to the sidecar. None of them is ours to "
     "redistribute and nothing here downloads anything -- neither binary in this "
     "project can reach the network at all. Fetch them yourself, then point this "
     "at them.",
     "Üç dosyanın yardımcının yanında durması gerekir. Hiçbirini dağıtma hakkımız "
     "yok ve burada hiçbir şey indirilmez — bu projedeki iki programın hiçbiri "
     "ağa erişemez. Onları kendiniz edinin, sonra burada gösterin."},
    {"INSTALLED",
     "KURULU"},
    {"MISSING",
     "EKSİK"},
    {"OPTIONAL",
     "İSTEĞE BAĞLI"},
    {"Wanted as %s   |   Source: %s",
     "Beklenen ad %s   |   Kaynak: %s"},
    {"Replace...",
     "Değiştir..."},
    {"Choose file...",
     "Dosya seç..."},
    {"Remove",
     "Kaldır"},
    {"Deletes the files listed above from this folder, and nothing else. It never "
     "touches a WoW installation. The sidecar's own two executables stay; delete "
     "the folder to be rid of them.",
     "Yukarıda listelenen dosyaları bu klasörden siler, başka hiçbir şeyi değil. "
     "Bir WoW kurulumuna asla dokunmaz. Yardımcının iki programı kalır; onlardan "
     "kurtulmak için klasörü silin."},
    {"Also remove settings and logs",
     "Ayarları ve günlükleri de kaldır"},
    {"Yes, remove them",
     "Evet, kaldır"},
    {"Remove installed files",
     "Kurulu dosyaları kaldır"},
    {"Stop the overlay first -- the files are in use.",
     "Önce katmanı durdurun — dosyalar kullanımda."},
    {"%zu file(s) would go.",
     "%zu dosya kaldırılacak."},
    {"That file no longer exists.",
     "Bu dosya artık yok."},
    {"That is not a file.",
     "Bu bir dosya değil."},
    {"Already installed.",
     "Zaten kurulu."},
    {"Could not copy it in: ",
     "Kopyalanamadı: "},
    {"Installed ",
     "Kuruldu: "},
    {"Could not remove ",
     "Kaldırılamadı: "},
    {". Stop the overlay and close anything using it, then try again.",
     ". Katmanı durdurun, onu kullanan her şeyi kapatın ve tekrar deneyin."},
    {"Removed ",
     "Kaldırıldı: "},
    {" file(s).",
     " dosya."},
    {"DLSS 5 neural rendering runtime",
     "DLSS 5 nöral işleme çalışma zamanı"},
    {"The neural network itself. On an RTX 40 card this must be a build patched "
     "for Ada; the stock runtime is Blackwell-only and fails at feature creation "
     "with no diagnostic.",
     "Sinir ağının kendisi. RTX 40 kartta Ada için yamalanmış bir sürüm "
     "olmalıdır; özgün çalışma zamanı yalnızca Blackwell içindir ve özellik "
     "oluşturulurken hiçbir açıklama vermeden başarısız olur."},
    {"ReShade, with add-on support",
     "Eklenti destekli ReShade"},
    {"Hosts the add-on inside the sidecar's own process. The add-on-enabled build "
     "is required; the plain one loads no add-ons at all.",
     "Eklentiyi yardımcının kendi sürecinde barındırır. Eklenti destekli sürüm "
     "gereklidir; sade sürüm hiç eklenti yüklemez."},
    {"RenoDX DLSS 5 add-on",
     "RenoDX DLSS 5 eklentisi"},
    {"Detours the sidecar's own NGX calls and substitutes neural-rendered output. "
     "This is what makes the pass neural rather than a plain DLAA.",
     "Yardımcının kendi NGX çağrılarını yönlendirir ve çıktıyı nöral işlenmiş "
     "olanla değiştirir. Geçişi sade bir DLAA yerine nöral yapan budur."},
    {"DLSS upscaling runtime",
     "DLSS ölçekleme çalışma zamanı"},
    {"Optional. Only consulted if the add-on's work-in-progress upscaling path is "
     "switched on; neural rendering itself does not need it.",
     "İsteğe bağlı. Yalnızca eklentinin deneysel ölçekleme yolu açıksa "
     "kullanılır; nöral işlemenin kendisi buna ihtiyaç duymaz."},
    {"System checks",
     "Sistem denetimleri"},
    {"Nothing here opens, reads, writes or hooks the game process. The import "
     "table of every binary is checked against that claim at build time.",
     "Buradaki hiçbir şey oyun sürecini açmaz, okumaz, yazmaz veya kancalamaz. "
     "Her programın içe aktarma tablosu derleme sırasında bu iddiaya karşı "
     "denetlenir."},
    {"WoW folder (used only to scan filenames for injectors)",
     "WoW klasörü (yalnızca enjektör dosya adlarını taramak için)"},
    {"Browse...",
     "Gözat..."},
    {"Detect",
     "Algıla"},
    {"Re-run checks",
     "Denetimleri yeniden çalıştır"},
    {"Detected from Battle.net's own uninstall entry. Point this at the folder "
     "Wow.exe sits in, not its parent: an injector has to be next to the "
     "executable to be loaded by it. Nothing inside is opened -- only the file "
     "names are read.",
     "Battle.net'in kendi kaldırma kaydından algılandı. Üst klasörü değil, "
     "Wow.exe'nin bulunduğu klasörü gösterin: bir enjektörün yüklenmesi için "
     "programın yanında olması gerekir. İçeride hiçbir şey açılmaz — yalnızca "
     "dosya adları okunur."},
    {"Graphics adapter",
     "Grafik bağdaştırıcısı"},
    {"No NVIDIA adapter found.",
     "NVIDIA bağdaştırıcısı bulunamadı."},
    {"This sidecar needs an NVIDIA RTX 40 or RTX 50 card.",
     "Bu yardımcı bir NVIDIA RTX 40 veya RTX 50 kart gerektirir."},
    {"RTX 40 (Ada) or RTX 50 (Blackwell) is required. Older cards are refused "
     "rather than run badly.",
     "RTX 40 (Ada) veya RTX 50 (Blackwell) gerekir. Eski kartlar kötü "
     "çalıştırılmak yerine reddedilir."},
    {"Display driver",
     "Ekran sürücüsü"},
    {"No NVIDIA adapter to query.",
     "Sorgulanacak NVIDIA bağdaştırıcısı yok."},
    {"Install an NVIDIA RTX 40 or RTX 50 card.",
     "Bir NVIDIA RTX 40 veya RTX 50 kart takın."},
    {"User-mode driver ",
     "Kullanıcı modu sürücüsü "},
    {"Could not read the driver version.",
     "Sürücü sürümü okunamadı."},
    {"Not fatal. Update to a current NVIDIA driver if capture misbehaves.",
     "Ciddi değil. Yakalama sorun çıkarırsa güncel bir NVIDIA sürücüsüne "
     "yükseltin."},
    {"Windows version",
     "Windows sürümü"},
    {"Could not read the Windows build number.",
     "Windows derleme numarası okunamadı."},
    {"Not fatal, but this project is only supported on Windows 11.",
     "Ciddi değil, ama bu proje yalnızca Windows 11'de desteklenir."},
    {"Build ",
     "Derleme "},
    {"Windows 11 is required: the overlay depends on compositor behaviour that "
     "Windows 10 does not provide.",
     "Windows 11 gerekir: katman, Windows 10'un sunmadığı bir birleştirici "
     "davranışına dayanır."},
    {"Display refresh rate",
     "Ekran yenileme hızı"},
    {"Could not read the current display mode.",
     "Geçerli ekran modu okunamadı."},
    {"Not fatal. Check your monitor settings if pacing looks wrong.",
     "Ciddi değil. Kare zamanlaması tuhaf görünürse monitör ayarlarınızı kontrol "
     "edin."},
    {"Below 120 Hz the overlay's added latency is a larger share of the frame. It "
     "will still run.",
     "120 Hz'in altında katmanın eklediği gecikme karenin daha büyük bir payıdır. "
     "Yine de çalışır."},
    {"Neural runtime",
     "Nöral çalışma zamanı"},
    {"nvngx_dlssnr.dll not found next to the sidecar.",
     "nvngx_dlssnr.dll yardımcının yanında bulunamadı."},
    {"Optional until the neural pass ships. Without it the pipeline runs the "
     "passthrough pass.",
     "Nöral geçiş gelene kadar isteğe bağlı. Onsuz işlem hattı doğrudan geçişi "
     "çalıştırır."},
    {"Check the file is not locked by another process, and that the sidecar has "
     "permission to read it.",
     "Dosyanın başka bir süreç tarafından kilitlenmediğini ve yardımcının onu "
     "okuma izni olduğunu kontrol edin."},
    {"Supply a runtime built for this GPU, or the neural pass will fall back to "
     "passthrough.",
     "Bu GPU için derlenmiş bir çalışma zamanı sağlayın, yoksa nöral geçiş "
     "doğrudan geçişe döner."},
    {"The pass will still try this build. If it fails, quote the SHA-256 above "
     "when reporting it.",
     "Geçiş bu sürümü yine de deneyecek. Başarısız olursa bildirirken yukarıdaki "
     "SHA-256'yı belirtin."},
    {"ReShade host (optional)",
     "ReShade barındırıcısı (isteğe bağlı)"},
    {"No ReShade host alongside the sidecar.",
     "Yardımcının yanında ReShade barındırıcısı yok."},
    {"Only needed for the ReShade-hosted neural pass. Install ReShade against the "
     "sidecar so it lands as dxgi.dll. Never place ReShade next to Wow.exe.",
     "Yalnızca ReShade'de barındırılan nöral geçiş için gerekir. ReShade'i "
     "yardımcıya kurun ki dxgi.dll olarak yerleşsin. ReShade'i asla Wow.exe'nin "
     "yanına koymayın."},
    {"World of Warcraft window",
     "World of Warcraft penceresi"},
    {"WoW is not running.",
     "WoW çalışmıyor."},
    {"Start the game, then run the probes again.",
     "Oyunu başlatın, sonra denetimleri yeniden çalıştırın."},
    {" borderless windowed",
     " kenarlıksız pencere"},
    {" windowed with a border, or exclusive fullscreen",
     " kenarlıklı pencere veya özel tam ekran"},
    {"Set WoW to borderless windowed. Exclusive fullscreen has no compositor "
     "surface to capture and yields black frames.",
     "WoW'u kenarlıksız pencereye alın. Özel tam ekranın yakalanacak birleştirici "
     "yüzeyi yoktur ve siyah kareler verir."},
    {"Injector scan of the WoW folder",
     "WoW klasöründe enjektör taraması"},
    {"No WoW folder set, so nothing was scanned.",
     "WoW klasörü ayarlanmadı, bu yüzden hiçbir şey taranmadı."},
    {"Point the manager at your WoW folder so it can check for injectors before "
     "launching.",
     "Başlatmadan önce enjektörleri denetleyebilmesi için yöneticiye WoW "
     "klasörünüzü gösterin."},
    {"No injector loaders found.",
     "Enjektör yükleyici bulunamadı."},
    {"Found: ",
     "Bulundu: "},
    {"Remove these from your WoW folder. Blizzard bans accounts for in-process "
     "injectors, and this tool refuses to run alongside one.",
     "Bunları WoW klasörünüzden kaldırın. Blizzard süreç içi enjektörler için "
     "hesap yasaklar ve bu araç bir enjektörün yanında çalışmayı reddeder."},
    {"Sidecar install location",
     "Yardımcının kurulum konumu"},
    {"Move the sidecar outside your WoW folder. Anything sitting next to Wow.exe "
     "looks like an injector, which is the one thing this design exists to avoid.",
     "Yardımcıyı WoW klasörünüzün dışına taşıyın. Wow.exe'nin yanındaki her şey "
     "enjektör gibi görünür; bu tasarımın kaçınmak için var olduğu tek şey de "
     "budur."},
    {" is the ",
     " şu çalışma zamanıdır: "},
    {" runtime, version ",
     ", sürüm "},
    {" could not be read, so it has no digest.",
     " okunamadı, bu yüzden özeti yok."},
    {" is not a build this manifest knows. Its SHA-256 is ",
     " bu bildirimin tanıdığı bir sürüm değil. SHA-256 değeri "},
    {" -- quote that when reporting it.",
     " — bildirirken bunu belirtin."},
    {"This GPU (",
     "Bu GPU ("},
    {") is outside the supported matrix; neural rendering needs Ada or Blackwell.",
     ") desteklenen listenin dışında; nöral işleme Ada veya Blackwell gerektirir."},
    {"This is the stock runtime, which is built for Blackwell. On an Ada card "
     "neural-rendering feature creation fails with no explanation. An "
     "Ada-compatible build of nvngx_dlssnr.dll is required.",
     "Bu, Blackwell için derlenmiş özgün çalışma zamanıdır. Ada kartta nöral "
     "işleme özelliği oluşturma açıklamasız başarısız olur. Ada uyumlu bir "
     "nvngx_dlssnr.dll sürümü gerekir."},
    {" runtime does not run on ",
     " çalışma zamanı şurada çalışmaz: "},
    {"Choose a look",
     "Bir görünüm seçin"},
    {"IN USE",
     "KULLANIMDA"},
    {"Custom -- your settings do not match any preset.",
     "Özel — ayarlarınız hiçbir hazır ayarla eşleşmiyor."},
    {"Click one above to go back to a tested combination. Nothing is selected "
     "because the individual settings below have been moved away from all four.",
     "Test edilmiş bir birleşime dönmek için yukarıdakilerden birine tıklayın. "
     "Hiçbiri seçili değil çünkü aşağıdaki tek tek ayarlar dördünden de uzaklaştı."},
    {"Pick one. Every setting below is chosen for you, and the combinations here "
     "are ones that have actually been run -- unlike most of the arrangements you "
     "can reach by moving sliders individually.",
     "Birini seçin. Aşağıdaki her ayar sizin için seçilir ve buradaki birleşimler "
     "gerçekten denenmiş olanlardır — kaydırıcıları tek tek oynatarak ulaşılan "
     "çoğu düzenlemenin aksine."},
    {"Recommended",
     "Önerilen"},
    {"The tuned default. Start here.",
     "Ayarlanmış varsayılan. Buradan başlayın."},
    {"Full neural intensity with the CNN F render preset, which clamps temporal "
     "history hard -- the right choice when motion vectors are estimated from "
     "colour rather than rendered by the game.",
     "CNN F işleme ön ayarıyla tam nöral yoğunluk; zamansal geçmişi sıkı biçimde "
     "sınırlar — hareket vektörleri oyun tarafından çizilmek yerine renkten "
     "tahmin edildiğinde doğru seçimdir."},
    {"Softer",
     "Daha yumuşak"},
    {"Half strength. Use if the picture looks over-processed.",
     "Yarım güç. Görüntü aşırı işlenmiş görünürse kullanın."},
    {"The same pipeline with the neural result mixed in at 60%. Cheaper on the "
     "eyes for interface-heavy scenes, and the first thing to try if faces or "
     "text look waxy.",
     "Aynı işlem hattı, nöral sonuç %60 oranında karıştırılır. Arayüzü yoğun "
     "sahnelerde göze daha rahat ve yüzler ya da yazılar mum gibi görünürse ilk "
     "denenecek şey."},
    {"Most stable",
     "En kararlı"},
    {"For smearing, or flicker on flames and lights.",
     "Bulanık iz ya da alev ve ışıklarda titreme için."},
    {"Switches to CNN E, which clamps temporal history hardest, and eases the "
     "intensity. This is the preset for when motion looks smeared -- the "
     "estimated motion vectors are being confidently wrong and this contains them.",
     "Zamansal geçmişi en sıkı sınırlayan CNN E'ye geçer ve yoğunluğu hafifletir. "
     "Hareket bulanık göründüğünde kullanılacak ön ayardır — tahmini hareket "
     "vektörleri kendinden emin biçimde yanılıyordur ve bu onları dizginler."},
    {"Off (A/B baseline)",
     "Kapalı (A/B referansı)"},
    {"Capture and present, untouched.",
     "Yakala ve göster, dokunmadan."},
    {"No neural work at all, on the same capture and present path. This is the "
     "honest comparison: whatever you see here is what the overlay costs you "
     "before any neural rendering happens.",
     "Aynı yakalama ve gösterim yolunda hiç nöral iş yok. Dürüst karşılaştırma "
     "budur: burada gördüğünüz, herhangi bir nöral işlemeden önce katmanın size "
     "maliyetidir."},
    {"Save settings",
     "Ayarları kaydet"},
    {"Changes are not saved yet.",
     "Değişiklikler henüz kaydedilmedi."},
    {"Nothing here reaches the picture until it is written to sidecar.toml.",
     "Bunların hiçbiri sidecar.toml dosyasına yazılana kadar görüntüye ulaşmaz."},
    {"Restart the overlay to apply.",
     "Uygulamak için katmanı yeniden başlatın."},
    {"Every individual setting",
     "Tüm ayrı ayarlar"},
    {"Nothing in here is needed for normal use.",
     "Buradakilerin hiçbiri normal kullanım için gerekli değil."},
    {"Pipeline",
     "İşlem hattı"},
    {"These are written to sidecar.toml, and the neural ones are projected into "
     "ReShade.ini where the add-on reads them. The add-on reads that file once, "
     "when it loads, so a change reaches the picture at the overlay's next start "
     "-- not while it runs.",
     "Bunlar sidecar.toml'a yazılır, nöral olanlar ayrıca eklentinin okuduğu "
     "ReShade.ini'ye aktarılır. Eklenti bu dosyayı yalnızca yüklenirken bir kez "
     "okur; bu yüzden bir değişiklik çalışırken değil, katmanın bir sonraki "
     "başlangıcında görüntüye ulaşır."},
    {"Neural pass",
     "Nöral geçiş"},
    {"passthrough -- capture and present, untouched",
     "passthrough — yakala ve göster, dokunmadan"},
    {"reshade -- DLSS 5 neural rendering",
     "reshade — DLSS 5 nöral işleme"},
    {"Passthrough is the honest A/B baseline: the same capture and present path "
     "with no neural work in it at all.",
     "Doğrudan geçiş dürüst A/B referansıdır: hiç nöral iş olmadan aynı yakalama "
     "ve gösterim yolu."},
    {"DLSS preset",
     "DLSS ön ayarı"},
    {"Optical flow grid",
     "Optik akış ızgarası"},
    {"1 -- finest, most expensive",
     "1 — en ince, en pahalı"},
    {"4 -- default",
     "4 — varsayılan"},
    {"Pixels per estimated motion vector. Finer costs more and is not obviously "
     "better: the vectors are estimated from colour, so a finer grid can sharpen "
     "the estimate or the error equally.",
     "Tahmin edilen hareket vektörü başına piksel. Daha ince daha pahalıdır ve "
     "açıkça daha iyi değildir: vektörler renkten tahmin edildiği için daha ince "
     "ızgara tahmini de hatayı da aynı ölçüde keskinleştirebilir."},
    {"Synthetic depth",
     "Yapay derinlik"},
    {"There is no real depth buffer to capture out of the composited frame, so a "
     "constant plane is bound instead. It costs temporal stability under motion "
     "rather than preventing NR from running; this dial is worth a try if motion "
     "smears.",
     "Birleştirilmiş kareden yakalanacak gerçek bir derinlik arabelleği yok, bu "
     "yüzden yerine sabit bir düzlem bağlanır. Bu, NR'nin çalışmasını engellemez "
     "ama hareket sırasında zamansal kararlılıktan götürür; hareket "
     "bulanıklaşırsa bu ayar denemeye değer."},
    {"Neural rendering strength",
     "Nöral işleme gücü"},
    {"Passed straight through to the RenoDX add-on. The add-on owns what these "
     "mean; we only carry them.",
     "Doğrudan RenoDX eklentisine iletilir. Ne anlama geldiklerine eklenti karar "
     "verir; biz yalnızca taşırız."},
    {"Intensity",
     "Yoğunluk"},
    {"How much of the neural result is mixed in. Start here.",
     "Nöral sonucun ne kadarının karıştırılacağı. Buradan başlayın."},
    {"Add-on preset",
     "Eklenti ön ayarı"},
    {"Style",
     "Stil"},
    {"Colour strength",
     "Renk gücü"},
    {"At zero the add-on's colour handling collapses to black, so this is not a "
     "subtle dial.",
     "Sıfırda eklentinin renk işlemesi siyaha çöker, yani bu ince bir ayar "
     "değildir."},
    {"HDR transfer strength",
     "HDR aktarım gücü"},
    {"Paper-white scale",
     "Kâğıt beyazı ölçeği"},
    {"Both only matter on an HDR display. The sidecar captures SDR today, so "
     "leave them at 1.00 unless you are experimenting.",
     "İkisi de yalnızca HDR ekranda önemlidir. Yardımcı şu an SDR yakalıyor, "
     "deneme yapmıyorsanız 1.00'da bırakın."},
    {"These three have no documented default, so they are written only once you "
     "move them. Clearing the box returns them to untouched, which leaves "
     "whatever the add-on does by itself.",
     "Bu üçünün belgelenmiş bir varsayılanı yok, bu yüzden yalnızca onları "
     "değiştirdiğinizde yazılırlar. Kutuyu boşaltmak onları dokunulmamış hale "
     "döndürür ve eklenti kendi bildiğini yapar."},
    {"Enable the add-on's upscaling (work in progress)",
     "Eklentinin ölçeklemesini aç (geliştirme aşamasında)"},
    {"The add-on marks this unfinished, and the sidecar feeds it a "
     "native-resolution DLAA contract, so it usually reports that it fell back to "
     "native. Off is the tested path.",
     "Eklenti bunu bitmemiş olarak işaretliyor ve yardımcı ona doğal çözünürlükte "
     "bir DLAA sözleşmesi veriyor, bu yüzden genellikle doğal çözünürlüğe "
     "döndüğünü bildirir. Kapalı, test edilmiş yoldur."},
    {"Hook mode",
     "Kanca modu"},
    {"0 turns neural rendering off entirely, 1 adds Streamline hooks, 2 is NGX "
     "only. Two is what this sidecar wants: it makes the NGX calls itself and "
     "there is no Streamline in the process.",
     "0 nöral işlemeyi tamamen kapatır, 1 Streamline kancaları ekler, 2 yalnızca "
     "NGX'tir. Bu yardımcının istediği ikidir: NGX çağrılarını kendisi yapar ve "
     "süreçte Streamline yoktur."},
    {"Overlay",
     "Katman"},
    {"Advanced",
     "Gelişmiş"},
    {"Local structure",
     "Yerel yapı"},
    {"How hard the model works on fine surface detail -- stonework, cloth weave, "
     "wood grain. Raising it sharpens texture and also sharpens whatever the "
     "model got wrong about it.",
     "Modelin ince yüzey ayrıntıları üzerinde ne kadar çalıştığı — taş işçiliği, "
     "kumaş dokusu, ahşap damarı. Artırmak dokuyu keskinleştirir, modelin yanlış "
     "anladığı her şeyi de."},
    {"Local tone",
     "Yerel ton"},
    {"Local contrast: how far the model pushes light against dark within a small "
     "area. This is the dial most likely to change the mood of a scene rather "
     "than its detail.",
     "Yerel kontrast: modelin küçük bir alanda ışığı karanlığa karşı ne kadar "
     "ittiği. Bir sahnenin ayrıntısından çok havasını değiştirmesi en olası ayar "
     "budur."},
    {"Skin structure",
     "Cilt yapısı"},
    {"Faces and skin specifically. The one people reach for after watching a "
     "comparison video, and the one most likely to look wrong when overdone -- "
     "skin is where anybody spots a mistake.",
     "Özellikle yüzler ve cilt. Karşılaştırma videosu izledikten sonra herkesin "
     "uzandığı ayar ve abartıldığında en çok yanlış görünen — ciltteki hatayı "
     "herkes fark eder."},
    {"The strip of numbers the overlay draws in its own top-left corner: frame "
     "rate, latency, which pass is running and how many frames were dropped. It "
     "is drawn by the overlay, not by the game, so it never reaches a screenshot "
     "the game takes.",
     "Katmanın sol üst köşesine çizdiği sayı şeridi: kare hızı, gecikme, hangi "
     "geçişin çalıştığı ve kaç karenin düşürüldüğü. Oyun değil katman çizer, bu "
     "yüzden oyunun aldığı ekran görüntüsünde asla görünmez."},
    {"Whether the overlay covers the game the moment it launches. Off starts it "
     "hidden, which is the honest way to look at the untouched frame first and "
     "then bring the neural pass in over the top of it.",
     "Katmanın açılır açılmaz oyunu kaplayıp kaplamayacağı. Kapalı, onu gizli "
     "başlatır; önce dokunulmamış kareye bakıp sonra nöral geçişi üstüne "
     "getirmenin dürüst yolu budur."},
    {"CNN F. The default here: clamps history hard, which suits estimated motion "
     "vectors.",
     "CNN F. Buradaki varsayılan: geçmişi sıkı sınırlar, tahmini hareket "
     "vektörlerine uygundur."},
    {"CNN E. Clamps hardest. Try this first if motion smears or flames and lights "
     "flicker.",
     "CNN E. En sıkı sınırlar. Hareket bulanıklaşıyorsa ya da alev ve ışıklar "
     "titriyorsa önce bunu deneyin."},
    {"Transformer K. The SDK default for DLAA. Sharpest when the vectors are "
     "trustworthy.",
     "Transformer K. DLAA için SDK varsayılanı. Vektörler güvenilir olduğunda en "
     "keskini."},
    {"Transformer J. The older transformer preset.",
     "Transformer J. Eski transformer ön ayarı."},
    {"Whatever the runtime picks for itself.",
     "Çalışma zamanı kendi ne seçerse."},
    {"Show the HUD",
     "HUD'u göster"},
    {"Show the overlay on start",
     "Başlangıçta katmanı göster"},
    {"Reset to defaults",
     "Varsayılanlara sıfırla"},
    {"%llu earlier line(s) dropped",
     "%llu önceki satır düşürüldü"},
    {"Last error",
     "Son hata"},
    {"The overlay (sidecar.log)",
     "Katman (sidecar.log)"},
    {"This manager",
     "Bu yönetici"},
    {"The overlay has not written anything yet.",
     "Katman henüz bir şey yazmadı."},
    {"Window class not found.",
     "Pencere sınıfı bulunamadı."},
    {"World of Warcraft is not running.",
     "World of Warcraft çalışmıyor."},
    {"World of Warcraft must run in borderless windowed mode.\nExclusive "
     "fullscreen has no compositor surface to capture.",
     "World of Warcraft kenarlıksız pencere modunda çalışmalıdır.\nÖzel tam "
     "ekranın yakalanacak birleştirici yüzeyi yoktur."},
    {"%hs is not supported. RTX 40 or RTX 50 required.",
     "%hs desteklenmiyor. RTX 40 veya RTX 50 gerekir."},
    {"Failed to create the pipeline.",
     "İşlem hattı oluşturulamadı."},
    {"An overlay is already running.\nStop it from the manager before starting "
     "another.",
     "Zaten çalışan bir katman var.\nBaşka birini başlatmadan önce onu "
     "yöneticiden durdurun."},
    {"The graphics device was reset and could not be rebuilt.",
     "Grafik aygıtı sıfırlandı ve yeniden kurulamadı."},
    {"Hotkeys",
     "Kısayol tuşları"},
    {"off",
     "kapalı"},
    {"Start or stop the overlay (while this window is open)",
     "Katmanı başlat veya durdur (bu pencere açıkken)"},
    {"Show or hide the overlay: instant A/B against the untouched game",
     "Katmanı göster veya gizle: dokunulmamış oyunla anında A/B"},
    {"Show or hide the frame-time HUD",
     "Kare süresi HUD'unu göster veya gizle"},
    {"Panic: take the overlay down, always",
     "Panik: katmanı her zaman kapat"},
    {"Change them on the Tuning page.",
     "Ayarlar sayfasından değiştirin."},
    {"Written like Ctrl+Alt+D or Shift+Alt+F9. Each needs Ctrl, Alt or Win, "
     "because Windows takes the combination away from the game. Leave one empty "
     "to switch it off.",
     "Ctrl+Alt+D veya Shift+Alt+F9 gibi yazılır. Her biri Ctrl, Alt veya Win "
     "gerektirir, çünkü Windows bu kombinasyonu oyundan alır. Kapatmak için "
     "birini boş bırakın."},
    {"Start / stop overlay",
     "Katmanı başlat / durdur"},
    {"Show / hide overlay",
     "Katmanı göster / gizle"},
    {"Show / hide HUD",
     "HUD'u göster / gizle"},
    {"not a key combination",
     "tuş kombinasyonu değil"},
    {"Language",
     "Dil"},
    {"Interface theme",
     "Arayüz teması"},
    {"Quest log",
     "Görev günlüğü"},
    {"Neural strength",
     "Nöral güç"},
    {"How many times DLSS 5 runs over each frame. One pass is subtle. Two or "
     "three push the picture further from the original -- closer to the heavily "
     "processed look in demonstration videos -- and each extra pass costs another "
     "full neural pass of GPU time.",
     "DLSS 5'in her karede kaç kez çalıştığı. Tek geçiş belli belirsizdir. İki ya "
     "da üç, görüntüyü özgünden daha da uzaklaştırır — tanıtım videolarındaki "
     "yoğun işlenmiş görünüme yaklaşır — ve her ek geçiş GPU süresinden bir tam "
     "nöral geçiş daha harcar."},
    {"1x  Natural",
     "1x  Doğal"},
    {"2x  Stronger",
     "2x  Daha güçlü"},
    {"3x  Strongest",
     "3x  En güçlü"},
    {"Closest to the game",
     "Oyuna en yakın"},
    {"About twice the GPU time",
     "Yaklaşık iki kat GPU süresi"},
    {"About three times the GPU time",
     "Yaklaşık üç kat GPU süresi"},
    {"Four passes, set in sidecar.toml. Pick one above to go back.",
     "Dört geçiş, sidecar.toml'da ayarlanmış. Geri dönmek için yukarıdan birini "
     "seçin."},
    {"The Off preset runs no neural pass, so this has no effect until you pick "
     "another look.",
     "Kapalı ön ayarı hiç nöral geçiş çalıştırmaz, bu yüzden başka bir görünüm "
     "seçene kadar bunun etkisi olmaz."},
};

const size_t kTurkishTableSize = sizeof(kTurkishTable) / sizeof(kTurkishTable[0]);

}  // namespace sidecar
