#include "core/I18nTable.h"

// German interface text. Generated by tools/gen_translation_table.py;
// the conventions are the Russian table's (I18nRu.cpp): keys are the English
// source text exactly, format specifiers keep their order, and file names,
// add-on key names and the log are never translated.

namespace sidecar {

const TranslationPair kGermanTable[] = {
    {"Setup",
     "Einrichtung"},
    {"Checks",
     "Prüfungen"},
    {"Tuning",
     "Feinabstimmung"},
    {"Log",
     "Protokoll"},
    {"Neural rendering for World of Warcraft, from outside the game process",
     "Neuronales Rendering für World of Warcraft, von außerhalb des Spielprozesses"},
    {"Stop overlay",
     "Overlay stoppen"},
    {"Start overlay",
     "Overlay starten"},
    {"Before you use this",
     "Bevor du das benutzt"},
    {"This sidecar never loads code into Wow.exe. That is what makes it safe, and "
     "it is checked automatically every time it is built.\n\nReShade placed next "
     "to Wow.exe is a different thing entirely, and Blizzard bans accounts for "
     "it. This tool will refuse to install there and will refuse to run if it "
     "finds an injector in your WoW folder.\n\nNo third-party tool can promise "
     "you will never be banned. What this one can promise is that it does not do "
     "any of the things Blizzard bans people for.",
     "Dieser Sidecar lädt niemals Code in Wow.exe. Genau das macht ihn sicher, "
     "und es wird bei jedem Build automatisch geprüft.\n\nReShade neben Wow.exe "
     "ist etwas völlig anderes, und Blizzard sperrt Accounts dafür. Dieses Tool "
     "verweigert die Installation dort und startet nicht, wenn es in deinem "
     "WoW-Ordner einen Injektor findet.\n\nKein Drittanbieter-Tool kann "
     "versprechen, dass du nie gesperrt wirst. Dieses kann versprechen, dass es "
     "nichts von dem tut, wofür Blizzard sperrt."},
    {"I understand",
     "Verstanden"},
    {"OVERLAY FPS",
     "OVERLAY-FPS"},
    {"LATENCY p50",
     "LATENZ p50"},
    {"LATENCY p99",
     "LATENZ p99"},
    {"CAPTURED FPS",
     "ERFASSTE FPS"},
    {"WoW: borderless",
     "WoW: randloses Fenster"},
    {"WoW: not borderless",
     "WoW: nicht randlos"},
    {"WoW: not running",
     "WoW: läuft nicht"},
    {"Overlay: running",
     "Overlay: läuft"},
    {"Overlay: stopped",
     "Overlay: gestoppt"},
    {"READY",
     "BEREIT"},
    {"CHECK",
     "PRÜFEN"},
    {"BLOCKED",
     "BLOCKIERT"},
    {"Hide overlay (A/B compare)",
     "Overlay ausblenden (A/B-Vergleich)"},
    {"Show overlay",
     "Overlay einblenden"},
    {"Hide HUD",
     "HUD ausblenden"},
    {"Show HUD",
     "HUD einblenden"},
    {"Hiding the overlay uncovers the untouched game without stopping capture.",
     "Das Ausblenden zeigt das unveränderte Spiel, ohne die Erfassung zu stoppen."},
    {"GPU MEMORY USED BY THE SIDECAR",
     "VOM SIDECAR BELEGTER GPU-SPEICHER"},
    {"  --  SPILLING",
     "  —  AUSLAGERUNG"},
    {"This is the sidecar's own share, not the whole card. More of it would not "
     "be faster -- the pass allocates what it needs. The number that matters is "
     "whether any has spilled.",
     "Das ist nur der Anteil des Sidecars, nicht die ganze Karte. Mehr davon wäre "
     "nicht schneller – der Pass belegt, was er braucht. Entscheidend ist, ob "
     "etwas ausgelagert wurde."},
    {"WHERE THE FRAME GOES",
     "WOHIN DER FRAME GEHT"},
    {"%llu presented, %llu dropped",
     "%llu angezeigt, %llu verworfen"},
    {"Runtime",
     "Laufzeit"},
    {"Verdict",
     "Urteil"},
    {"playable",
     "spielbar"},
    {"marginal",
     "grenzwertig"},
    {"too slow",
     "zu langsam"},
    {"The overlay is starting. Numbers appear after the first few frames.",
     "Das Overlay startet. Zahlen erscheinen nach den ersten Frames."},
    {"Nothing running.",
     "Nichts läuft."},
    {"The card is full, so the driver is moving resources to system memory and "
     "every frame waits on the PCIe bus. It shows below as a huge GPU wait with "
     "the GPU nearly idle, which is easy to mistake for a slow neural "
     "pass.\n\nClose what else is using the card -- browsers, streaming and "
     "capture tools, anything compositing a second monitor -- and lower the "
     "game's texture quality. Nothing in this tool can make room.",
     "Die Karte ist voll, also verschiebt der Treiber Ressourcen in den "
     "Arbeitsspeicher und jeder Frame wartet auf den PCIe-Bus. Unten erscheint "
     "das als riesige GPU-Wartezeit bei fast untätiger GPU – leicht zu "
     "verwechseln mit einem langsamen neuronalen Pass.\n\nSchließe, was die Karte "
     "sonst noch nutzt – Browser, Streaming- und Aufnahmetools, alles, was einen "
     "zweiten Monitor zusammensetzt – und senke die Texturqualität im Spiel. "
     "Nichts in diesem Tool kann Platz schaffen."},
    {"This is the desktop compositor's rate, not the sidecar's and not the game's "
     "-- the game may well be running far faster. It is usually set by your "
     "monitor's refresh rate and, on a multi-monitor setup with mismatched "
     "refresh rates, by the slowest one. Nothing in this tool can raise it.",
     "Das ist die Rate des Desktop-Compositors, nicht die des Sidecars und nicht "
     "die des Spiels – das Spiel läuft womöglich viel schneller. Meist bestimmt "
     "sie die Bildwiederholrate deines Monitors und bei mehreren Monitoren mit "
     "unterschiedlichen Raten der langsamste. Nichts in diesem Tool kann sie "
     "erhöhen."},
    {"The game is competing for the GPU. Measured on the development machine, the "
     "same scene ran at 11.7 fps with the game focused and 35.2 fps with it in "
     "the background, purely because an unfocused game throttles itself and hands "
     "the card back.\n\nCap the game's frame rate. This costs nothing: the "
     "overlay can never show more than the capture rate above, so every frame the "
     "game renders beyond that is discarded before it reaches here.",
     "Das Spiel konkurriert um die GPU. Auf dem Entwicklungsrechner lief dieselbe "
     "Szene mit fokussiertem Spiel bei 11,7 fps und im Hintergrund bei 35,2 fps – "
     "nur weil ein unfokussiertes Spiel sich selbst drosselt und die Karte "
     "freigibt.\n\nBegrenze die Bildrate des Spiels. Das kostet nichts: Das "
     "Overlay kann nie mehr zeigen als die Erfassungsrate oben, also wird jeder "
     "Frame darüber verworfen, bevor er hier ankommt."},
    {"The overlay is presenting close to every frame Windows hands it, and there "
     "is memory to spare. Nothing to fix here.",
     "Das Overlay zeigt fast jeden Frame, den Windows liefert, und es ist "
     "Speicher frei. Hier gibt es nichts zu beheben."},
    {"Some checks are failing. Open Checks to see what.",
     "Einige Prüfungen schlagen fehl. Öffne Prüfungen, um zu sehen, welche."},
    {"Files are missing. Open Setup to install them.",
     "Dateien fehlen. Öffne Einrichtung, um sie zu installieren."},
    {"Start World of Warcraft in borderless windowed mode, then press Start "
     "overlay.",
     "Starte World of Warcraft im randlosen Fenstermodus und drücke dann Overlay "
     "starten."},
    {"Press Start overlay.",
     "Drücke Overlay starten."},
    {"Playing with the overlay up",
     "Spielen mit aktivem Overlay"},
    {"The overlay covers the game completely and passes every click straight "
     "through to it, so play normally. It never takes focus, so whatever had the "
     "keyboard keeps it -- if the game is not responding, alt-tab to World of "
     "Warcraft once.\n\nCtrl+Alt+Backspace takes the overlay down from anywhere, "
     "without needing this window.",
     "Das Overlay bedeckt das Spiel vollständig und reicht jeden Klick direkt "
     "durch, also spiel ganz normal. Es nimmt nie den Fokus, deshalb behält die "
     "Tastatur, wer sie hatte – reagiert das Spiel nicht, wechsle einmal per "
     "Alt+Tab zu World of Warcraft.\n\nStrg+Alt+Rücktaste nimmt das Overlay von "
     "überall herunter, ohne dieses Fenster."},
    {"Required files",
     "Benötigte Dateien"},
    {"Three files have to sit next to the sidecar. None of them is ours to "
     "redistribute and nothing here downloads anything -- neither binary in this "
     "project can reach the network at all. Fetch them yourself, then point this "
     "at them.",
     "Drei Dateien müssen neben dem Sidecar liegen. Keine davon dürfen wir "
     "weitergeben, und hier wird nichts heruntergeladen – keine der beiden "
     "Programmdateien kann überhaupt ins Netz. Besorge sie selbst und zeige dann "
     "hier auf sie."},
    {"INSTALLED",
     "INSTALLIERT"},
    {"MISSING",
     "FEHLT"},
    {"Wanted as %s   |   Source: %s",
     "Erwartet als %s   |   Quelle: %s"},
    {"Replace...",
     "Ersetzen..."},
    {"Choose file...",
     "Datei wählen..."},
    {"Remove",
     "Entfernen"},
    {"Deletes the files listed above from this folder, and nothing else. It never "
     "touches a WoW installation. The sidecar's own two executables stay; delete "
     "the folder to be rid of them.",
     "Löscht die oben aufgeführten Dateien aus diesem Ordner und sonst nichts. "
     "Eine WoW-Installation wird nie berührt. Die beiden Programmdateien des "
     "Sidecars bleiben; lösche den Ordner, um sie loszuwerden."},
    {"Also remove settings and logs",
     "Auch Einstellungen und Protokolle entfernen"},
    {"Yes, remove them",
     "Ja, entfernen"},
    {"Remove installed files",
     "Installierte Dateien entfernen"},
    {"Stop the overlay first -- the files are in use.",
     "Stoppe zuerst das Overlay – die Dateien sind in Benutzung."},
    {"%zu file(s) would go.",
     "%zu Datei(en) würden entfernt."},
    {"That file no longer exists.",
     "Diese Datei existiert nicht mehr."},
    {"That is not a file.",
     "Das ist keine Datei."},
    {"Already installed.",
     "Bereits installiert."},
    {"Could not copy it in: ",
     "Konnte nicht kopiert werden: "},
    {"Installed ",
     "Installiert: "},
    {"Could not remove ",
     "Konnte nicht entfernt werden: "},
    {". Stop the overlay and close anything using it, then try again.",
     ". Stoppe das Overlay, schließe alles, was die Datei nutzt, und versuche es "
     "erneut."},
    {"Removed ",
     "Entfernt: "},
    {" file(s).",
     " Datei(en)."},
    {"DLSS 5 neural rendering runtime",
     "DLSS-5-Laufzeit für neuronales Rendering"},
    {"The neural network itself. On an RTX 40 card this must be a build patched "
     "for Ada; the stock runtime is Blackwell-only and fails at feature creation "
     "with no diagnostic.",
     "Das neuronale Netz selbst. Auf einer RTX-40-Karte muss es ein für Ada "
     "gepatchter Build sein; die Originallaufzeit ist nur für Blackwell und "
     "scheitert bei der Feature-Erstellung ohne jede Diagnose."},
    {"ReShade, with add-on support",
     "ReShade mit Add-on-Unterstützung"},
    {"Hosts the add-on inside the sidecar's own process. The add-on-enabled build "
     "is required; the plain one loads no add-ons at all.",
     "Hostet das Add-on im eigenen Prozess des Sidecars. Der Build mit "
     "Add-on-Unterstützung ist nötig; der normale lädt gar keine Add-ons."},
    {"RenoDX DLSS 5 add-on",
     "RenoDX-DLSS-5-Add-on"},
    {"Detours the sidecar's own NGX calls and substitutes neural-rendered output. "
     "This is what makes the pass neural rather than a plain DLAA.",
     "Leitet die eigenen NGX-Aufrufe des Sidecars um und ersetzt die Ausgabe "
     "durch neuronal gerenderte. Erst dadurch wird der Pass neuronal statt eines "
     "einfachen DLAA."},
    {"DLSS upscaling runtime",
     "DLSS-Upscaling-Laufzeit"},
    {"Optional. Only consulted if the add-on's work-in-progress upscaling path is "
     "switched on; neural rendering itself does not need it.",
     "Optional. Wird nur genutzt, wenn der unfertige Upscaling-Pfad des Add-ons "
     "eingeschaltet ist; neuronales Rendering selbst braucht sie nicht."},
    {"System checks",
     "Systemprüfungen"},
    {"Nothing here opens, reads, writes or hooks the game process. The import "
     "table of every binary is checked against that claim at build time.",
     "Nichts hiervon öffnet, liest, schreibt oder hookt den Spielprozess. Die "
     "Importtabelle jeder Programmdatei wird beim Build gegen diese Aussage "
     "geprüft."},
    {"WoW folder (used only to scan filenames for injectors)",
     "WoW-Ordner (nur zum Durchsuchen der Dateinamen nach Injektoren)"},
    {"Browse...",
     "Durchsuchen..."},
    {"Detect",
     "Erkennen"},
    {"Re-run checks",
     "Prüfungen wiederholen"},
    {"Detected from Battle.net's own uninstall entry. Point this at the folder "
     "Wow.exe sits in, not its parent: an injector has to be next to the "
     "executable to be loaded by it. Nothing inside is opened -- only the file "
     "names are read.",
     "Aus dem Deinstallationseintrag von Battle.net erkannt. Zeige auf den "
     "Ordner, in dem Wow.exe liegt, nicht auf den übergeordneten: Ein Injektor "
     "muss neben der Programmdatei liegen, um von ihr geladen zu werden. Darin "
     "wird nichts geöffnet – nur die Dateinamen werden gelesen."},
    {"Graphics adapter",
     "Grafikadapter"},
    {"No NVIDIA adapter found.",
     "Kein NVIDIA-Adapter gefunden."},
    {"This sidecar needs an NVIDIA RTX 40 or RTX 50 card.",
     "Dieser Sidecar braucht eine NVIDIA RTX 40 oder RTX 50."},
    {"RTX 40 (Ada) or RTX 50 (Blackwell) is required. Older cards are refused "
     "rather than run badly.",
     "RTX 40 (Ada) oder RTX 50 (Blackwell) ist nötig. Ältere Karten werden "
     "abgelehnt, statt schlecht zu laufen."},
    {"Display driver",
     "Grafiktreiber"},
    {"No NVIDIA adapter to query.",
     "Kein NVIDIA-Adapter zum Abfragen."},
    {"Install an NVIDIA RTX 40 or RTX 50 card.",
     "Installiere eine NVIDIA RTX 40 oder RTX 50."},
    {"User-mode driver ",
     "Usermode-Treiber "},
    {"Could not read the driver version.",
     "Treiberversion konnte nicht gelesen werden."},
    {"Not fatal. Update to a current NVIDIA driver if capture misbehaves.",
     "Nicht kritisch. Aktualisiere auf einen aktuellen NVIDIA-Treiber, falls die "
     "Erfassung Probleme macht."},
    {"Windows version",
     "Windows-Version"},
    {"Could not read the Windows build number.",
     "Windows-Buildnummer konnte nicht gelesen werden."},
    {"Not fatal, but this project is only supported on Windows 11.",
     "Nicht kritisch, aber dieses Projekt wird nur unter Windows 11 unterstützt."},
    {"Windows 11 is required: the overlay depends on compositor behaviour that "
     "Windows 10 does not provide.",
     "Windows 11 ist nötig: Das Overlay hängt von einem Compositor-Verhalten ab, "
     "das Windows 10 nicht bietet."},
    {"Display refresh rate",
     "Bildwiederholrate"},
    {"Could not read the current display mode.",
     "Aktueller Anzeigemodus konnte nicht gelesen werden."},
    {"Not fatal. Check your monitor settings if pacing looks wrong.",
     "Nicht kritisch. Prüfe deine Monitoreinstellungen, wenn das Timing falsch "
     "wirkt."},
    {"Below 120 Hz the overlay's added latency is a larger share of the frame. It "
     "will still run.",
     "Unter 120 Hz ist die zusätzliche Latenz des Overlays ein größerer Teil des "
     "Frames. Es läuft trotzdem."},
    {"Neural runtime",
     "Neuronale Laufzeit"},
    {"nvngx_dlssnr.dll not found next to the sidecar.",
     "nvngx_dlssnr.dll wurde neben dem Sidecar nicht gefunden."},
    {"Optional until the neural pass ships. Without it the pipeline runs the "
     "passthrough pass.",
     "Optional, bis der neuronale Pass kommt. Ohne sie läuft die Pipeline im "
     "Durchreich-Pass."},
    {"Check the file is not locked by another process, and that the sidecar has "
     "permission to read it.",
     "Prüfe, ob die Datei von einem anderen Prozess gesperrt ist und ob der "
     "Sidecar sie lesen darf."},
    {"Supply a runtime built for this GPU, or the neural pass will fall back to "
     "passthrough.",
     "Stelle eine für diese GPU gebaute Laufzeit bereit, sonst fällt der "
     "neuronale Pass auf Durchreichen zurück."},
    {"The pass will still try this build. If it fails, quote the SHA-256 above "
     "when reporting it.",
     "Der Pass versucht es trotzdem mit diesem Build. Scheitert er, gib beim "
     "Melden den SHA-256 oben an."},
    {"ReShade host (optional)",
     "ReShade-Host (optional)"},
    {"No ReShade host alongside the sidecar.",
     "Kein ReShade-Host neben dem Sidecar."},
    {"Only needed for the ReShade-hosted neural pass. Install ReShade against the "
     "sidecar so it lands as dxgi.dll. Never place ReShade next to Wow.exe.",
     "Nur für den in ReShade gehosteten neuronalen Pass nötig. Installiere "
     "ReShade für den Sidecar, sodass es als dxgi.dll landet. Lege ReShade "
     "niemals neben Wow.exe."},
    {"World of Warcraft window",
     "World-of-Warcraft-Fenster"},
    {"WoW is not running.",
     "WoW läuft nicht."},
    {"Start the game, then run the probes again.",
     "Starte das Spiel und führe die Prüfungen erneut aus."},
    {" borderless windowed",
     " randloses Fenster"},
    {" windowed with a border, or exclusive fullscreen",
     " Fenster mit Rahmen oder exklusiver Vollbildmodus"},
    {"Set WoW to borderless windowed. Exclusive fullscreen has no compositor "
     "surface to capture and yields black frames.",
     "Stelle WoW auf randloses Fenster. Exklusiver Vollbildmodus hat keine "
     "Compositor-Fläche zum Erfassen und liefert schwarze Frames."},
    {"Injector scan of the WoW folder",
     "Injektorsuche im WoW-Ordner"},
    {"No WoW folder set, so nothing was scanned.",
     "Kein WoW-Ordner gesetzt, also wurde nichts durchsucht."},
    {"Point the manager at your WoW folder so it can check for injectors before "
     "launching.",
     "Zeige dem Manager deinen WoW-Ordner, damit er vor dem Start nach Injektoren "
     "suchen kann."},
    {"No injector loaders found.",
     "Keine Injektor-Loader gefunden."},
    {"Found: ",
     "Gefunden: "},
    {"Remove these from your WoW folder. Blizzard bans accounts for in-process "
     "injectors, and this tool refuses to run alongside one.",
     "Entferne sie aus deinem WoW-Ordner. Blizzard sperrt Accounts für Injektoren "
     "im Prozess, und dieses Tool läuft nicht neben einem."},
    {"Sidecar install location",
     "Installationsort des Sidecars"},
    {"Move the sidecar outside your WoW folder. Anything sitting next to Wow.exe "
     "looks like an injector, which is the one thing this design exists to avoid.",
     "Verschiebe den Sidecar aus deinem WoW-Ordner. Alles neben Wow.exe sieht aus "
     "wie ein Injektor – genau das, was dieses Design vermeiden soll."},
    {" is the ",
     " ist die "},
    {" runtime, version ",
     "-Laufzeit, Version "},
    {" could not be read, so it has no digest.",
     " konnte nicht gelesen werden und hat daher keinen Hash."},
    {" is not a build this manifest knows. Its SHA-256 is ",
     " ist kein Build, den dieses Manifest kennt. Sein SHA-256 ist "},
    {" -- quote that when reporting it.",
     " – gib ihn beim Melden an."},
    {"This GPU (",
     "Diese GPU ("},
    {") is outside the supported matrix; neural rendering needs Ada or Blackwell.",
     ") liegt außerhalb der unterstützten Liste; neuronales Rendering braucht Ada "
     "oder Blackwell."},
    {"This is the stock runtime, which is built for Blackwell. On an Ada card "
     "neural-rendering feature creation fails with no explanation. An "
     "Ada-compatible build of nvngx_dlssnr.dll is required.",
     "Das ist die Originallaufzeit, gebaut für Blackwell. Auf einer Ada-Karte "
     "scheitert die Erstellung des Features ohne Erklärung. Ein Ada-kompatibler "
     "Build von nvngx_dlssnr.dll ist nötig."},
    {"The ",
     "Die "},
    {" runtime does not run on ",
     "-Laufzeit läuft nicht auf "},
    {"Choose a look",
     "Wähle einen Look"},
    {"IN USE",
     "AKTIV"},
    {"Custom -- your settings do not match any preset.",
     "Eigene Einstellung – passt zu keiner Vorgabe."},
    {"Click one above to go back to a tested combination. Nothing is selected "
     "because the individual settings below have been moved away from all four.",
     "Klicke oben auf eine, um zu einer getesteten Kombination zurückzukehren. "
     "Keine ist gewählt, weil die Einzeleinstellungen unten von allen vier "
     "abweichen."},
    {"Pick one. Every setting below is chosen for you, and the combinations here "
     "are ones that have actually been run -- unlike most of the arrangements you "
     "can reach by moving sliders individually.",
     "Wähle eine. Jede Einstellung unten wird für dich gesetzt, und diese "
     "Kombinationen wurden wirklich getestet – anders als die meisten, die man "
     "durch Verschieben einzelner Regler erreicht."},
    {"Recommended",
     "Empfohlen"},
    {"The tuned default. Start here.",
     "Die abgestimmte Vorgabe. Fang hier an."},
    {"Full neural intensity with the CNN F render preset, which clamps temporal "
     "history hard -- the right choice when motion vectors are estimated from "
     "colour rather than rendered by the game.",
     "Volle neuronale Intensität mit dem Render-Preset CNN F, das den zeitlichen "
     "Verlauf stark begrenzt – die richtige Wahl, wenn Bewegungsvektoren aus der "
     "Farbe geschätzt statt vom Spiel gerendert werden."},
    {"Softer",
     "Sanfter"},
    {"Half strength. Use if the picture looks over-processed.",
     "Halbe Stärke. Nimm das, wenn das Bild überbearbeitet wirkt."},
    {"The same pipeline with the neural result mixed in at 60%. Cheaper on the "
     "eyes for interface-heavy scenes, and the first thing to try if faces or "
     "text look waxy.",
     "Dieselbe Pipeline, das neuronale Ergebnis zu 60 % eingemischt. Angenehmer "
     "bei Szenen mit viel Interface und das Erste, was man probiert, wenn "
     "Gesichter oder Text wächsern wirken."},
    {"Most stable",
     "Am stabilsten"},
    {"For smearing, or flicker on flames and lights.",
     "Bei Verschmieren oder Flackern von Flammen und Lichtern."},
    {"Switches to CNN E, which clamps temporal history hardest, and eases the "
     "intensity. This is the preset for when motion looks smeared -- the "
     "estimated motion vectors are being confidently wrong and this contains them.",
     "Wechselt zu CNN E, das den zeitlichen Verlauf am stärksten begrenzt, und "
     "senkt die Intensität. Das Preset für verschmierte Bewegung – die "
     "geschätzten Bewegungsvektoren liegen überzeugt daneben, und das hier fängt "
     "es ab."},
    {"Off (A/B baseline)",
     "Aus (A/B-Referenz)"},
    {"Capture and present, untouched.",
     "Erfassen und anzeigen, unverändert."},
    {"No neural work at all, on the same capture and present path. This is the "
     "honest comparison: whatever you see here is what the overlay costs you "
     "before any neural rendering happens.",
     "Gar keine neuronale Arbeit, auf demselben Erfassungs- und Anzeigeweg. Der "
     "ehrliche Vergleich: Was du hier siehst, kostet dich das Overlay, bevor "
     "überhaupt neuronal gerendert wird."},
    {"Save settings",
     "Einstellungen speichern"},
    {"Changes are not saved yet.",
     "Änderungen sind noch nicht gespeichert."},
    {"Nothing here reaches the picture until it is written to sidecar.toml.",
     "Nichts davon erreicht das Bild, bevor es in sidecar.toml steht."},
    {"Restart the overlay to apply.",
     "Overlay neu starten, um es anzuwenden."},
    {"Every individual setting",
     "Alle Einzeleinstellungen"},
    {"Nothing in here is needed for normal use.",
     "Nichts hiervon ist für den normalen Gebrauch nötig."},
    {"These are written to sidecar.toml, and the neural ones are projected into "
     "ReShade.ini where the add-on reads them. The add-on reads that file once, "
     "when it loads, so a change reaches the picture at the overlay's next start "
     "-- not while it runs.",
     "Diese werden in sidecar.toml geschrieben, die neuronalen zusätzlich in "
     "ReShade.ini, wo das Add-on sie liest. Das Add-on liest die Datei nur einmal "
     "beim Laden, also wirkt eine Änderung erst beim nächsten Start des Overlays "
     "– nicht während es läuft."},
    {"Neural pass",
     "Neuronaler Pass"},
    {"passthrough -- capture and present, untouched",
     "passthrough – erfassen und anzeigen, unverändert"},
    {"reshade -- DLSS 5 neural rendering",
     "reshade – neuronales DLSS-5-Rendering"},
    {"Passthrough is the honest A/B baseline: the same capture and present path "
     "with no neural work in it at all.",
     "Durchreichen ist die ehrliche A/B-Referenz: derselbe Erfassungs- und "
     "Anzeigeweg ohne jede neuronale Arbeit."},
    {"DLSS preset",
     "DLSS-Preset"},
    {"Optical flow grid",
     "Raster des optischen Flusses"},
    {"1 -- finest, most expensive",
     "1 – am feinsten, am teuersten"},
    {"4 -- default",
     "4 – Standard"},
    {"Pixels per estimated motion vector. Finer costs more and is not obviously "
     "better: the vectors are estimated from colour, so a finer grid can sharpen "
     "the estimate or the error equally.",
     "Pixel pro geschätztem Bewegungsvektor. Feiner kostet mehr und ist nicht "
     "klar besser: Die Vektoren werden aus der Farbe geschätzt, also kann ein "
     "feineres Raster die Schätzung ebenso schärfen wie den Fehler."},
    {"Synthetic depth",
     "Synthetische Tiefe"},
    {"There is no real depth buffer to capture out of the composited frame, so a "
     "constant plane is bound instead. It costs temporal stability under motion "
     "rather than preventing NR from running; this dial is worth a try if motion "
     "smears.",
     "Im zusammengesetzten Frame gibt es keinen echten Tiefenpuffer, also wird "
     "stattdessen eine konstante Ebene gebunden. Das kostet zeitliche Stabilität "
     "bei Bewegung, verhindert NR aber nicht; bei verschmierter Bewegung ist "
     "dieser Regler einen Versuch wert."},
    {"Neural rendering strength",
     "Stärke des neuronalen Renderings"},
    {"Passed straight through to the RenoDX add-on. The add-on owns what these "
     "mean; we only carry them.",
     "Werden direkt an das RenoDX-Add-on weitergereicht. Was sie bedeuten, "
     "bestimmt das Add-on; wir reichen sie nur durch."},
    {"Intensity",
     "Intensität"},
    {"How much of the neural result is mixed in. Start here.",
     "Wie viel vom neuronalen Ergebnis eingemischt wird. Fang hier an."},
    {"Add-on preset",
     "Add-on-Preset"},
    {"Style",
     "Stil"},
    {"Colour strength",
     "Farbstärke"},
    {"At zero the add-on's colour handling collapses to black, so this is not a "
     "subtle dial.",
     "Bei null bricht die Farbverarbeitung des Add-ons zu Schwarz zusammen – das "
     "ist kein subtiler Regler."},
    {"HDR transfer strength",
     "HDR-Transferstärke"},
    {"Paper-white scale",
     "Papierweiß-Skalierung"},
    {"Both only matter on an HDR display. The sidecar captures SDR today, so "
     "leave them at 1.00 unless you are experimenting.",
     "Beide zählen nur auf einem HDR-Display. Der Sidecar erfasst derzeit SDR, "
     "also lass sie auf 1.00, außer du experimentierst."},
    {"These three have no documented default, so they are written only once you "
     "move them. Clearing the box returns them to untouched, which leaves "
     "whatever the add-on does by itself.",
     "Diese drei haben keinen dokumentierten Standard und werden erst "
     "geschrieben, wenn du sie bewegst. Leerst du das Feld, sind sie wieder "
     "unberührt und das Add-on macht, was es selbst tut."},
    {"Enable the add-on's upscaling (work in progress)",
     "Upscaling des Add-ons aktivieren (in Arbeit)"},
    {"The add-on marks this unfinished, and the sidecar feeds it a "
     "native-resolution DLAA contract, so it usually reports that it fell back to "
     "native. Off is the tested path.",
     "Das Add-on markiert dies als unfertig, und der Sidecar liefert einen "
     "DLAA-Vertrag in nativer Auflösung, daher meldet es meist, dass es auf nativ "
     "zurückgefallen ist. Aus ist der getestete Weg."},
    {"Hook mode",
     "Hook-Modus"},
    {"0 turns neural rendering off entirely, 1 adds Streamline hooks, 2 is NGX "
     "only. Two is what this sidecar wants: it makes the NGX calls itself and "
     "there is no Streamline in the process.",
     "0 schaltet neuronales Rendering ganz ab, 1 fügt Streamline-Hooks hinzu, 2 "
     "ist nur NGX. Zwei ist, was dieser Sidecar will: Er macht die NGX-Aufrufe "
     "selbst, und im Prozess gibt es kein Streamline."},
    {"Advanced",
     "Erweitert"},
    {"Local structure",
     "Lokale Struktur"},
    {"How hard the model works on fine surface detail -- stonework, cloth weave, "
     "wood grain. Raising it sharpens texture and also sharpens whatever the "
     "model got wrong about it.",
     "Wie stark das Modell an feinen Oberflächendetails arbeitet – Mauerwerk, "
     "Stoffgewebe, Holzmaserung. Höher schärft die Textur und auch alles, was das "
     "Modell daran falsch verstanden hat."},
    {"Local tone",
     "Lokaler Ton"},
    {"Local contrast: how far the model pushes light against dark within a small "
     "area. This is the dial most likely to change the mood of a scene rather "
     "than its detail.",
     "Lokaler Kontrast: wie weit das Modell Licht gegen Dunkel auf kleiner Fläche "
     "treibt. Dieser Regler verändert am ehesten die Stimmung einer Szene statt "
     "ihres Details."},
    {"Skin structure",
     "Hautstruktur"},
    {"Faces and skin specifically. The one people reach for after watching a "
     "comparison video, and the one most likely to look wrong when overdone -- "
     "skin is where anybody spots a mistake.",
     "Gesichter und Haut im Speziellen. Der Regler, zu dem man nach einem "
     "Vergleichsvideo greift, und der, der übertrieben am ehesten falsch aussieht "
     "– an der Haut sieht jeder einen Fehler."},
    {"The strip of numbers the overlay draws in its own top-left corner: frame "
     "rate, latency, which pass is running and how many frames were dropped. It "
     "is drawn by the overlay, not by the game, so it never reaches a screenshot "
     "the game takes.",
     "Die Zahlenleiste, die das Overlay in seine obere linke Ecke zeichnet: "
     "Bildrate, Latenz, welcher Pass läuft und wie viele Frames verworfen wurden. "
     "Sie stammt vom Overlay, nicht vom Spiel, und landet daher nie in einem "
     "Screenshot des Spiels."},
    {"Whether the overlay covers the game the moment it launches. Off starts it "
     "hidden, which is the honest way to look at the untouched frame first and "
     "then bring the neural pass in over the top of it.",
     "Ob das Overlay das Spiel sofort beim Start bedeckt. Aus startet es "
     "verborgen – der ehrliche Weg, erst das unveränderte Bild anzusehen und dann "
     "den neuronalen Pass darüberzulegen."},
    {"CNN F. The default here: clamps history hard, which suits estimated motion "
     "vectors.",
     "CNN F. Hier der Standard: begrenzt den Verlauf stark, was zu geschätzten "
     "Bewegungsvektoren passt."},
    {"CNN E. Clamps hardest. Try this first if motion smears or flames and lights "
     "flicker.",
     "CNN E. Begrenzt am stärksten. Probier es zuerst, wenn Bewegung verschmiert "
     "oder Flammen und Lichter flackern."},
    {"Transformer K. The SDK default for DLAA. Sharpest when the vectors are "
     "trustworthy.",
     "Transformer K. Der SDK-Standard für DLAA. Am schärfsten, wenn die Vektoren "
     "verlässlich sind."},
    {"Transformer J. The older transformer preset.",
     "Transformer J. Das ältere Transformer-Preset."},
    {"Whatever the runtime picks for itself.",
     "Was die Laufzeit selbst wählt."},
    {"Show the HUD",
     "HUD anzeigen"},
    {"Show the overlay on start",
     "Overlay beim Start anzeigen"},
    {"Reset to defaults",
     "Auf Standard zurücksetzen"},
    {"%llu earlier line(s) dropped",
     "%llu frühere Zeile(n) verworfen"},
    {"Last error",
     "Letzter Fehler"},
    {"The overlay (sidecar.log)",
     "Das Overlay (sidecar.log)"},
    {"This manager",
     "Dieser Manager"},
    {"The overlay has not written anything yet.",
     "Das Overlay hat noch nichts geschrieben."},
    {"Window class not found.",
     "Fensterklasse nicht gefunden."},
    {"World of Warcraft is not running.",
     "World of Warcraft läuft nicht."},
    {"World of Warcraft must run in borderless windowed mode.\nExclusive "
     "fullscreen has no compositor surface to capture.",
     "World of Warcraft muss im randlosen Fenstermodus laufen.\nExklusiver "
     "Vollbildmodus hat keine Compositor-Fläche zum Erfassen."},
    {"%hs is not supported. RTX 40 or RTX 50 required.",
     "%hs wird nicht unterstützt. RTX 40 oder RTX 50 nötig."},
    {"Failed to create the pipeline.",
     "Die Pipeline konnte nicht erstellt werden."},
    {"An overlay is already running.\nStop it from the manager before starting "
     "another.",
     "Es läuft bereits ein Overlay.\nStoppe es im Manager, bevor du ein weiteres "
     "startest."},
    {"The graphics device was reset and could not be rebuilt.",
     "Das Grafikgerät wurde zurückgesetzt und konnte nicht neu aufgebaut werden."},
    {"Hotkeys",
     "Tastenkürzel"},
    {"off",
     "aus"},
    {"Start or stop the overlay (while this window is open)",
     "Overlay starten oder stoppen (solange dieses Fenster offen ist)"},
    {"Show or hide the overlay: instant A/B against the untouched game",
     "Overlay ein-/ausblenden: sofortiger A/B-Vergleich mit dem unveränderten "
     "Spiel"},
    {"Show or hide the frame-time HUD",
     "Frame-Zeit-HUD ein-/ausblenden"},
    {"Panic: take the overlay down, always",
     "Panik: Overlay herunternehmen, immer"},
    {"Change them on the Tuning page.",
     "Änderbar auf der Seite Feinabstimmung."},
    {"Written like Ctrl+Alt+D or Shift+Alt+F9. Each needs Ctrl, Alt or Win, "
     "because Windows takes the combination away from the game. Leave one empty "
     "to switch it off.",
     "Geschrieben wie Ctrl+Alt+D oder Shift+Alt+F9. Jedes braucht Ctrl, Alt oder "
     "Win, weil Windows dem Spiel die Kombination wegnimmt. Leer lassen, um eines "
     "abzuschalten."},
    {"Start / stop overlay",
     "Overlay starten / stoppen"},
    {"Show / hide overlay",
     "Overlay ein-/ausblenden"},
    {"Show / hide HUD",
     "HUD ein-/ausblenden"},
    {"not a key combination",
     "keine Tastenkombination"},
    {"Language",
     "Sprache"},
    {"Interface theme",
     "Oberflächen-Design"},
    {"Stormwind",
     "Sturmwind"},
    {"Quest log",
     "Questlog"},
    {"Neural strength",
     "Neuronale Stärke"},
    {"How many times DLSS 5 runs over each frame. One pass is subtle. Two or "
     "three push the picture further from the original -- closer to the heavily "
     "processed look in demonstration videos -- and each extra pass costs another "
     "full neural pass of GPU time.",
     "Wie oft DLSS 5 über jeden Frame läuft. Ein Pass ist dezent. Zwei oder drei "
     "entfernen das Bild weiter vom Original – näher am stark bearbeiteten Look "
     "der Demovideos – und jeder zusätzliche Pass kostet einen weiteren vollen "
     "neuronalen Pass an GPU-Zeit."},
    {"1x  Natural",
     "1x  Natürlich"},
    {"2x  Stronger",
     "2x  Stärker"},
    {"3x  Strongest",
     "3x  Am stärksten"},
    {"Closest to the game",
     "Am nächsten am Spiel"},
    {"About twice the GPU time",
     "Etwa doppelte GPU-Zeit"},
    {"About three times the GPU time",
     "Etwa dreifache GPU-Zeit"},
    {"Four passes, set in sidecar.toml. Pick one above to go back.",
     "Vier Passes, gesetzt in sidecar.toml. Wähle oben einen, um zurückzukehren."},
    {"The Off preset runs no neural pass, so this has no effect until you pick "
     "another look.",
     "Das Aus-Preset führt keinen neuronalen Pass aus, daher wirkt dies erst, "
     "wenn du einen anderen Look wählst."},
};

const size_t kGermanTableSize = sizeof(kGermanTable) / sizeof(kGermanTable[0]);

}  // namespace sidecar
