#include "core/I18nTable.h"

// French interface text. Generated by tools/gen_translation_table.py;
// the conventions are the Russian table's (I18nRu.cpp): keys are the English
// source text exactly, format specifiers keep their order, and file names,
// add-on key names and the log are never translated.

namespace sidecar {

const TranslationPair kFrenchTable[] = {
    {"Status",
     "État"},
    {"Setup",
     "Installation"},
    {"Checks",
     "Vérifications"},
    {"Tuning",
     "Réglages"},
    {"Log",
     "Journal"},
    {"Neural rendering for World of Warcraft, from outside the game process",
     "Rendu neuronal pour World of Warcraft, depuis l’extérieur du processus du "
     "jeu"},
    {"Stop overlay",
     "Arrêter l’overlay"},
    {"Start overlay",
     "Lancer l’overlay"},
    {"Before you use this",
     "Avant de commencer"},
    {"This sidecar never loads code into Wow.exe. That is what makes it safe, and "
     "it is checked automatically every time it is built.\n\nReShade placed next "
     "to Wow.exe is a different thing entirely, and Blizzard bans accounts for "
     "it. This tool will refuse to install there and will refuse to run if it "
     "finds an injector in your WoW folder.\n\nNo third-party tool can promise "
     "you will never be banned. What this one can promise is that it does not do "
     "any of the things Blizzard bans people for.",
     "Ce sidecar ne charge jamais de code dans Wow.exe. C’est ce qui le rend sûr, "
     "et c’est vérifié automatiquement à chaque compilation.\n\nReShade placé à "
     "côté de Wow.exe est tout autre chose, et Blizzard bannit des comptes pour "
     "cela. Cet outil refusera de s’installer là et refusera de démarrer s’il "
     "trouve un injecteur dans votre dossier WoW.\n\nAucun outil tiers ne peut "
     "promettre que vous ne serez jamais banni. Celui-ci peut promettre qu’il ne "
     "fait rien de ce pour quoi Blizzard bannit."},
    {"I understand",
     "J’ai compris"},
    {"Live",
     "En direct"},
    {"OVERLAY FPS",
     "FPS DE L’OVERLAY"},
    {"LATENCY p50",
     "LATENCE p50"},
    {"LATENCY p99",
     "LATENCE p99"},
    {"CAPTURED FPS",
     "FPS CAPTURÉS"},
    {"WoW: borderless",
     "WoW : fenêtré sans bordure"},
    {"WoW: not borderless",
     "WoW : pas sans bordure"},
    {"WoW: not running",
     "WoW : non lancé"},
    {"Overlay: running",
     "Overlay : actif"},
    {"Overlay: stopped",
     "Overlay : arrêté"},
    {"READY",
     "PRÊT"},
    {"CHECK",
     "À VÉRIFIER"},
    {"BLOCKED",
     "BLOQUÉ"},
    {"Hide overlay (A/B compare)",
     "Masquer l’overlay (comparaison A/B)"},
    {"Show overlay",
     "Afficher l’overlay"},
    {"Hide HUD",
     "Masquer le HUD"},
    {"Show HUD",
     "Afficher le HUD"},
    {"Hiding the overlay uncovers the untouched game without stopping capture.",
     "Masquer l’overlay révèle le jeu intact sans arrêter la capture."},
    {"GPU MEMORY USED BY THE SIDECAR",
     "MÉMOIRE GPU UTILISÉE PAR LE SIDECAR"},
    {"  --  SPILLING",
     "  —  DÉBORDEMENT"},
    {"This is the sidecar's own share, not the whole card. More of it would not "
     "be faster -- the pass allocates what it needs. The number that matters is "
     "whether any has spilled.",
     "C’est la part du sidecar seul, pas toute la carte. En avoir plus ne serait "
     "pas plus rapide : la passe réserve ce dont elle a besoin. Ce qui compte, "
     "c’est de savoir si quelque chose a débordé."},
    {"WHERE THE FRAME GOES",
     "OÙ PASSE L’IMAGE"},
    {"Frames",
     "Images"},
    {"%llu presented, %llu dropped",
     "%llu affichées, %llu abandonnées"},
    {"Pass",
     "Passe"},
    {"playable",
     "jouable"},
    {"marginal",
     "limite"},
    {"too slow",
     "trop lent"},
    {"The overlay is starting. Numbers appear after the first few frames.",
     "L’overlay démarre. Les chiffres apparaissent après les premières images."},
    {"Nothing running.",
     "Rien en cours."},
    {"The card is full, so the driver is moving resources to system memory and "
     "every frame waits on the PCIe bus. It shows below as a huge GPU wait with "
     "the GPU nearly idle, which is easy to mistake for a slow neural "
     "pass.\n\nClose what else is using the card -- browsers, streaming and "
     "capture tools, anything compositing a second monitor -- and lower the "
     "game's texture quality. Nothing in this tool can make room.",
     "La carte est pleine : le pilote déplace des ressources vers la mémoire "
     "système et chaque image attend le bus PCIe. Cela apparaît ci-dessous comme "
     "une énorme attente GPU avec un GPU presque inactif, facile à confondre avec "
     "une passe neuronale lente.\n\nFermez ce qui utilise aussi la carte — "
     "navigateurs, outils de streaming et de capture, tout ce qui compose un "
     "second écran — et baissez la qualité des textures du jeu. Rien dans cet "
     "outil ne peut libérer de la place."},
    {"This is the desktop compositor's rate, not the sidecar's and not the game's "
     "-- the game may well be running far faster. It is usually set by your "
     "monitor's refresh rate and, on a multi-monitor setup with mismatched "
     "refresh rates, by the slowest one. Nothing in this tool can raise it.",
     "C’est la cadence du compositeur du bureau, ni celle du sidecar ni celle du "
     "jeu — le jeu tourne peut-être bien plus vite. Elle est généralement fixée "
     "par la fréquence de votre écran et, avec plusieurs écrans de fréquences "
     "différentes, par le plus lent. Rien dans cet outil ne peut l’augmenter."},
    {"The game is competing for the GPU. Measured on the development machine, the "
     "same scene ran at 11.7 fps with the game focused and 35.2 fps with it in "
     "the background, purely because an unfocused game throttles itself and hands "
     "the card back.\n\nCap the game's frame rate. This costs nothing: the "
     "overlay can never show more than the capture rate above, so every frame the "
     "game renders beyond that is discarded before it reaches here.",
     "Le jeu se dispute le GPU. Mesuré sur la machine de développement, la même "
     "scène tournait à 11,7 fps avec le jeu au premier plan et à 35,2 fps en "
     "arrière-plan, simplement parce qu’un jeu sans focus se bride et rend la "
     "carte.\n\nLimitez les FPS du jeu. Cela ne coûte rien : l’overlay ne peut "
     "jamais afficher plus que la cadence de capture ci-dessus, donc chaque image "
     "rendue au-delà est jetée avant d’arriver ici."},
    {"The overlay is presenting close to every frame Windows hands it, and there "
     "is memory to spare. Nothing to fix here.",
     "L’overlay affiche presque chaque image que Windows lui donne, et il reste "
     "de la mémoire. Rien à corriger ici."},
    {"Some checks are failing. Open Checks to see what.",
     "Certaines vérifications échouent. Ouvrez Vérifications pour voir lesquelles."},
    {"Files are missing. Open Setup to install them.",
     "Des fichiers manquent. Ouvrez Installation pour les installer."},
    {"Start World of Warcraft in borderless windowed mode, then press Start "
     "overlay.",
     "Lancez World of Warcraft en mode fenêtré sans bordure, puis appuyez sur "
     "Lancer l’overlay."},
    {"Press Start overlay.",
     "Appuyez sur Lancer l’overlay."},
    {"Playing with the overlay up",
     "Jouer avec l’overlay"},
    {"The overlay covers the game completely and passes every click straight "
     "through to it, so play normally. It never takes focus, so whatever had the "
     "keyboard keeps it -- if the game is not responding, alt-tab to World of "
     "Warcraft once.\n\nCtrl+Alt+Backspace takes the overlay down from anywhere, "
     "without needing this window.",
     "L’overlay couvre entièrement le jeu et lui transmet chaque clic, alors "
     "jouez normalement. Il ne prend jamais le focus, donc ce qui avait le "
     "clavier le garde — si le jeu ne répond pas, faites Alt+Tab une fois vers "
     "World of Warcraft.\n\nCtrl+Alt+Retour arrière retire l’overlay de n’importe "
     "où, sans cette fenêtre."},
    {"Required files",
     "Fichiers requis"},
    {"Three files have to sit next to the sidecar. None of them is ours to "
     "redistribute and nothing here downloads anything -- neither binary in this "
     "project can reach the network at all. Fetch them yourself, then point this "
     "at them.",
     "Trois fichiers doivent se trouver à côté du sidecar. Aucun n’est à nous de "
     "redistribuer et rien ici ne télécharge quoi que ce soit — aucun des deux "
     "exécutables du projet ne peut accéder au réseau. Récupérez-les vous-même, "
     "puis indiquez-les ici."},
    {"INSTALLED",
     "INSTALLÉ"},
    {"MISSING",
     "MANQUANT"},
    {"OPTIONAL",
     "FACULTATIF"},
    {"Wanted as %s   |   Source: %s",
     "Attendu sous %s   |   Source : %s"},
    {"Replace...",
     "Remplacer..."},
    {"Choose file...",
     "Choisir un fichier..."},
    {"Remove",
     "Supprimer"},
    {"Deletes the files listed above from this folder, and nothing else. It never "
     "touches a WoW installation. The sidecar's own two executables stay; delete "
     "the folder to be rid of them.",
     "Supprime de ce dossier les fichiers listés ci-dessus, et rien d’autre. Ne "
     "touche jamais à une installation de WoW. Les deux exécutables du sidecar "
     "restent ; supprimez le dossier pour vous en débarrasser."},
    {"Also remove settings and logs",
     "Supprimer aussi réglages et journaux"},
    {"Yes, remove them",
     "Oui, les supprimer"},
    {"Remove installed files",
     "Supprimer les fichiers installés"},
    {"Stop the overlay first -- the files are in use.",
     "Arrêtez d’abord l’overlay — les fichiers sont utilisés."},
    {"%zu file(s) would go.",
     "%zu fichier(s) seraient supprimés."},
    {"That file no longer exists.",
     "Ce fichier n’existe plus."},
    {"That is not a file.",
     "Ce n’est pas un fichier."},
    {"Already installed.",
     "Déjà installé."},
    {"Could not copy it in: ",
     "Copie impossible : "},
    {"Installed ",
     "Installé : "},
    {"Could not remove ",
     "Suppression impossible : "},
    {". Stop the overlay and close anything using it, then try again.",
     ". Arrêtez l’overlay et fermez ce qui l’utilise, puis réessayez."},
    {"Removed ",
     "Supprimé : "},
    {" file(s).",
     " fichier(s)."},
    {"DLSS 5 neural rendering runtime",
     "Runtime de rendu neuronal DLSS 5"},
    {"The neural network itself. On an RTX 40 card this must be a build patched "
     "for Ada; the stock runtime is Blackwell-only and fails at feature creation "
     "with no diagnostic.",
     "Le réseau neuronal lui-même. Sur une carte RTX 40, il faut une version "
     "patchée pour Ada ; le runtime d’origine est réservé à Blackwell et échoue à "
     "la création de la fonction sans aucun diagnostic."},
    {"ReShade, with add-on support",
     "ReShade, avec prise en charge des add-ons"},
    {"Hosts the add-on inside the sidecar's own process. The add-on-enabled build "
     "is required; the plain one loads no add-ons at all.",
     "Héberge l’add-on dans le processus même du sidecar. La version avec add-ons "
     "est requise ; la version simple n’en charge aucun."},
    {"RenoDX DLSS 5 add-on",
     "Add-on RenoDX DLSS 5"},
    {"Detours the sidecar's own NGX calls and substitutes neural-rendered output. "
     "This is what makes the pass neural rather than a plain DLAA.",
     "Détourne les appels NGX du sidecar lui-même et substitue une sortie rendue "
     "neuronalement. C’est ce qui rend la passe neuronale plutôt qu’un simple "
     "DLAA."},
    {"DLSS upscaling runtime",
     "Runtime de mise à l’échelle DLSS"},
    {"Optional. Only consulted if the add-on's work-in-progress upscaling path is "
     "switched on; neural rendering itself does not need it.",
     "Facultatif. Utilisé seulement si la mise à l’échelle expérimentale de "
     "l’add-on est activée ; le rendu neuronal n’en a pas besoin."},
    {"System checks",
     "Vérifications système"},
    {"Nothing here opens, reads, writes or hooks the game process. The import "
     "table of every binary is checked against that claim at build time.",
     "Rien ici n’ouvre, ne lit, n’écrit ni n’intercepte le processus du jeu. La "
     "table d’importation de chaque exécutable est vérifiée contre cette "
     "affirmation à la compilation."},
    {"WoW folder (used only to scan filenames for injectors)",
     "Dossier WoW (utilisé seulement pour repérer des injecteurs par nom de "
     "fichier)"},
    {"Browse...",
     "Parcourir..."},
    {"Detect",
     "Détecter"},
    {"Re-run checks",
     "Relancer les vérifications"},
    {"Detected from Battle.net's own uninstall entry. Point this at the folder "
     "Wow.exe sits in, not its parent: an injector has to be next to the "
     "executable to be loaded by it. Nothing inside is opened -- only the file "
     "names are read.",
     "Détecté depuis l’entrée de désinstallation de Battle.net. Indiquez le "
     "dossier qui contient Wow.exe, pas son parent : un injecteur doit être à "
     "côté de l’exécutable pour être chargé. Rien n’y est ouvert — seuls les noms "
     "de fichiers sont lus."},
    {"Graphics adapter",
     "Carte graphique"},
    {"No NVIDIA adapter found.",
     "Aucune carte NVIDIA trouvée."},
    {"This sidecar needs an NVIDIA RTX 40 or RTX 50 card.",
     "Ce sidecar nécessite une carte NVIDIA RTX 40 ou RTX 50."},
    {"RTX 40 (Ada) or RTX 50 (Blackwell) is required. Older cards are refused "
     "rather than run badly.",
     "Une RTX 40 (Ada) ou RTX 50 (Blackwell) est requise. Les cartes plus "
     "anciennes sont refusées plutôt que de mal fonctionner."},
    {"Display driver",
     "Pilote graphique"},
    {"No NVIDIA adapter to query.",
     "Aucune carte NVIDIA à interroger."},
    {"Install an NVIDIA RTX 40 or RTX 50 card.",
     "Installez une carte NVIDIA RTX 40 ou RTX 50."},
    {"User-mode driver ",
     "Pilote en mode utilisateur "},
    {"Could not read the driver version.",
     "Impossible de lire la version du pilote."},
    {"Not fatal. Update to a current NVIDIA driver if capture misbehaves.",
     "Pas bloquant. Mettez à jour votre pilote NVIDIA si la capture se comporte "
     "mal."},
    {"Windows version",
     "Version de Windows"},
    {"Could not read the Windows build number.",
     "Impossible de lire le numéro de build de Windows."},
    {"Not fatal, but this project is only supported on Windows 11.",
     "Pas bloquant, mais ce projet n’est pris en charge que sous Windows 11."},
    {"Windows 11 is required: the overlay depends on compositor behaviour that "
     "Windows 10 does not provide.",
     "Windows 11 est requis : l’overlay dépend d’un comportement du compositeur "
     "que Windows 10 n’offre pas."},
    {"Display refresh rate",
     "Fréquence d’affichage"},
    {"Could not read the current display mode.",
     "Impossible de lire le mode d’affichage actuel."},
    {"Not fatal. Check your monitor settings if pacing looks wrong.",
     "Pas bloquant. Vérifiez les réglages de l’écran si la cadence semble "
     "anormale."},
    {"Below 120 Hz the overlay's added latency is a larger share of the frame. It "
     "will still run.",
     "Sous 120 Hz, la latence ajoutée par l’overlay pèse davantage dans l’image. "
     "Il fonctionnera quand même."},
    {"Neural runtime",
     "Runtime neuronal"},
    {"nvngx_dlssnr.dll not found next to the sidecar.",
     "nvngx_dlssnr.dll introuvable à côté du sidecar."},
    {"Optional until the neural pass ships. Without it the pipeline runs the "
     "passthrough pass.",
     "Facultatif tant que la passe neuronale n’est pas livrée. Sans lui, le "
     "pipeline utilise la passe directe."},
    {"Check the file is not locked by another process, and that the sidecar has "
     "permission to read it.",
     "Vérifiez que le fichier n’est pas verrouillé par un autre processus et que "
     "le sidecar a le droit de le lire."},
    {"Supply a runtime built for this GPU, or the neural pass will fall back to "
     "passthrough.",
     "Fournissez un runtime compilé pour ce GPU, sinon la passe neuronale "
     "reviendra au mode direct."},
    {"The pass will still try this build. If it fails, quote the SHA-256 above "
     "when reporting it.",
     "La passe essaiera quand même cette version. Si elle échoue, citez le "
     "SHA-256 ci-dessus dans votre rapport."},
    {"ReShade host (optional)",
     "Hôte ReShade (facultatif)"},
    {"No ReShade host alongside the sidecar.",
     "Aucun hôte ReShade à côté du sidecar."},
    {"Only needed for the ReShade-hosted neural pass. Install ReShade against the "
     "sidecar so it lands as dxgi.dll. Never place ReShade next to Wow.exe.",
     "Nécessaire seulement pour la passe neuronale hébergée par ReShade. "
     "Installez ReShade sur le sidecar pour qu’il devienne dxgi.dll. Ne placez "
     "jamais ReShade à côté de Wow.exe."},
    {"World of Warcraft window",
     "Fenêtre de World of Warcraft"},
    {"WoW is not running.",
     "WoW n’est pas lancé."},
    {"Start the game, then run the probes again.",
     "Lancez le jeu, puis relancez les vérifications."},
    {" borderless windowed",
     " fenêtré sans bordure"},
    {" windowed with a border, or exclusive fullscreen",
     " fenêtré avec bordure, ou plein écran exclusif"},
    {"Set WoW to borderless windowed. Exclusive fullscreen has no compositor "
     "surface to capture and yields black frames.",
     "Passez WoW en fenêtré sans bordure. Le plein écran exclusif n’a pas de "
     "surface de compositeur à capturer et donne des images noires."},
    {"Injector scan of the WoW folder",
     "Recherche d’injecteurs dans le dossier WoW"},
    {"No WoW folder set, so nothing was scanned.",
     "Aucun dossier WoW défini, donc rien n’a été analysé."},
    {"Point the manager at your WoW folder so it can check for injectors before "
     "launching.",
     "Indiquez votre dossier WoW au gestionnaire pour qu’il recherche des "
     "injecteurs avant le lancement."},
    {"No injector loaders found.",
     "Aucun chargeur d’injection trouvé."},
    {"Found: ",
     "Trouvé : "},
    {"Remove these from your WoW folder. Blizzard bans accounts for in-process "
     "injectors, and this tool refuses to run alongside one.",
     "Retirez-les de votre dossier WoW. Blizzard bannit des comptes pour des "
     "injecteurs dans le processus, et cet outil refuse de fonctionner à côté "
     "d’un injecteur."},
    {"Sidecar install location",
     "Emplacement d’installation du sidecar"},
    {"Move the sidecar outside your WoW folder. Anything sitting next to Wow.exe "
     "looks like an injector, which is the one thing this design exists to avoid.",
     "Déplacez le sidecar hors de votre dossier WoW. Tout ce qui est à côté de "
     "Wow.exe ressemble à un injecteur — exactement ce que cette conception veut "
     "éviter."},
    {" is the ",
     " est le runtime "},
    {" runtime, version ",
     ", version "},
    {" could not be read, so it has no digest.",
     " n’a pas pu être lu, il n’a donc pas d’empreinte."},
    {" is not a build this manifest knows. Its SHA-256 is ",
     " n’est pas une version connue de ce manifeste. Son SHA-256 est "},
    {" -- quote that when reporting it.",
     " — citez-le dans votre rapport."},
    {"This GPU (",
     "Ce GPU ("},
    {") is outside the supported matrix; neural rendering needs Ada or Blackwell.",
     ") est hors de la liste prise en charge ; le rendu neuronal nécessite Ada ou "
     "Blackwell."},
    {"This is the stock runtime, which is built for Blackwell. On an Ada card "
     "neural-rendering feature creation fails with no explanation. An "
     "Ada-compatible build of nvngx_dlssnr.dll is required.",
     "C’est le runtime d’origine, compilé pour Blackwell. Sur une carte Ada, la "
     "création de la fonction de rendu neuronal échoue sans explication. Une "
     "version de nvngx_dlssnr.dll compatible Ada est requise."},
    {"The ",
     "Le runtime "},
    {" runtime does not run on ",
     " ne fonctionne pas sur "},
    {"Choose a look",
     "Choisir un rendu"},
    {"IN USE",
     "ACTIF"},
    {"Custom -- your settings do not match any preset.",
     "Personnalisé — vos réglages ne correspondent à aucun préréglage."},
    {"Click one above to go back to a tested combination. Nothing is selected "
     "because the individual settings below have been moved away from all four.",
     "Cliquez sur l’un d’eux pour revenir à une combinaison testée. Aucun n’est "
     "sélectionné parce que les réglages individuels ci-dessous s’écartent des "
     "quatre."},
    {"Pick one. Every setting below is chosen for you, and the combinations here "
     "are ones that have actually been run -- unlike most of the arrangements you "
     "can reach by moving sliders individually.",
     "Choisissez-en un. Chaque réglage ci-dessous est choisi pour vous, et ces "
     "combinaisons ont réellement été testées — contrairement à la plupart de "
     "celles obtenues en bougeant les curseurs un par un."},
    {"Recommended",
     "Recommandé"},
    {"The tuned default. Start here.",
     "Le réglage par défaut. Commencez ici."},
    {"Full neural intensity with the CNN F render preset, which clamps temporal "
     "history hard -- the right choice when motion vectors are estimated from "
     "colour rather than rendered by the game.",
     "Intensité neuronale maximale avec le préréglage de rendu CNN F, qui limite "
     "fortement l’historique temporel — le bon choix quand les vecteurs de "
     "mouvement sont estimés à partir de la couleur plutôt que rendus par le jeu."},
    {"Softer",
     "Plus doux"},
    {"Half strength. Use if the picture looks over-processed.",
     "Demi-intensité. À utiliser si l’image paraît surtraitée."},
    {"The same pipeline with the neural result mixed in at 60%. Cheaper on the "
     "eyes for interface-heavy scenes, and the first thing to try if faces or "
     "text look waxy.",
     "Le même pipeline avec le résultat neuronal mélangé à 60 %. Plus reposant "
     "pour les scènes chargées d’interface, et le premier essai si les visages ou "
     "le texte semblent cireux."},
    {"Most stable",
     "Le plus stable"},
    {"For smearing, or flicker on flames and lights.",
     "Contre les traînées, ou le scintillement des flammes et des lumières."},
    {"Switches to CNN E, which clamps temporal history hardest, and eases the "
     "intensity. This is the preset for when motion looks smeared -- the "
     "estimated motion vectors are being confidently wrong and this contains them.",
     "Passe à CNN E, qui limite le plus l’historique temporel, et adoucit "
     "l’intensité. C’est le préréglage quand le mouvement bave — les vecteurs "
     "estimés se trompent avec assurance et celui-ci les contient."},
    {"Off (A/B baseline)",
     "Désactivé (référence A/B)"},
    {"Capture and present, untouched.",
     "Capturer et afficher, sans modification."},
    {"No neural work at all, on the same capture and present path. This is the "
     "honest comparison: whatever you see here is what the overlay costs you "
     "before any neural rendering happens.",
     "Aucun travail neuronal, sur le même chemin de capture et d’affichage. C’est "
     "la comparaison honnête : ce que vous voyez ici est ce que l’overlay vous "
     "coûte avant tout rendu neuronal."},
    {"Save settings",
     "Enregistrer les réglages"},
    {"Changes are not saved yet.",
     "Les modifications ne sont pas encore enregistrées."},
    {"Nothing here reaches the picture until it is written to sidecar.toml.",
     "Rien de tout cela n’atteint l’image avant d’être écrit dans sidecar.toml."},
    {"Restart the overlay to apply.",
     "Relancez l’overlay pour appliquer."},
    {"Every individual setting",
     "Tous les réglages individuels"},
    {"Nothing in here is needed for normal use.",
     "Rien ici n’est nécessaire pour un usage normal."},
    {"These are written to sidecar.toml, and the neural ones are projected into "
     "ReShade.ini where the add-on reads them. The add-on reads that file once, "
     "when it loads, so a change reaches the picture at the overlay's next start "
     "-- not while it runs.",
     "Ils sont écrits dans sidecar.toml, et les réglages neuronaux sont reportés "
     "dans ReShade.ini où l’add-on les lit. L’add-on lit ce fichier une seule "
     "fois, au chargement, donc un changement atteint l’image au prochain "
     "démarrage de l’overlay — pas pendant qu’il tourne."},
    {"Neural pass",
     "Passe neuronale"},
    {"passthrough -- capture and present, untouched",
     "passthrough — capturer et afficher, sans modification"},
    {"reshade -- DLSS 5 neural rendering",
     "reshade — rendu neuronal DLSS 5"},
    {"Passthrough is the honest A/B baseline: the same capture and present path "
     "with no neural work in it at all.",
     "La passe directe est la référence A/B honnête : le même chemin de capture "
     "et d’affichage, sans aucun travail neuronal."},
    {"DLSS preset",
     "Préréglage DLSS"},
    {"Optical flow grid",
     "Grille du flux optique"},
    {"1 -- finest, most expensive",
     "1 — la plus fine, la plus coûteuse"},
    {"4 -- default",
     "4 — par défaut"},
    {"Pixels per estimated motion vector. Finer costs more and is not obviously "
     "better: the vectors are estimated from colour, so a finer grid can sharpen "
     "the estimate or the error equally.",
     "Pixels par vecteur de mouvement estimé. Plus fin coûte plus et n’est pas "
     "forcément mieux : les vecteurs sont estimés à partir de la couleur, donc "
     "une grille plus fine peut affiner l’estimation comme l’erreur."},
    {"Synthetic depth",
     "Profondeur synthétique"},
    {"There is no real depth buffer to capture out of the composited frame, so a "
     "constant plane is bound instead. It costs temporal stability under motion "
     "rather than preventing NR from running; this dial is worth a try if motion "
     "smears.",
     "Il n’y a pas de vrai tampon de profondeur à capturer dans l’image composée, "
     "donc un plan constant est lié à la place. Cela coûte de la stabilité "
     "temporelle en mouvement sans empêcher le NR de fonctionner ; ce réglage "
     "vaut un essai si le mouvement bave."},
    {"Neural rendering strength",
     "Intensité du rendu neuronal"},
    {"Passed straight through to the RenoDX add-on. The add-on owns what these "
     "mean; we only carry them.",
     "Transmis tels quels à l’add-on RenoDX. C’est l’add-on qui décide de leur "
     "sens ; nous ne faisons que les transmettre."},
    {"Intensity",
     "Intensité"},
    {"How much of the neural result is mixed in. Start here.",
     "Quelle part du résultat neuronal est mélangée. Commencez ici."},
    {"Add-on preset",
     "Préréglage de l’add-on"},
    {"Colour strength",
     "Intensité des couleurs"},
    {"At zero the add-on's colour handling collapses to black, so this is not a "
     "subtle dial.",
     "À zéro, la gestion des couleurs de l’add-on tombe au noir : ce n’est pas un "
     "réglage subtil."},
    {"HDR transfer strength",
     "Intensité du transfert HDR"},
    {"Paper-white scale",
     "Échelle du blanc papier"},
    {"Both only matter on an HDR display. The sidecar captures SDR today, so "
     "leave them at 1.00 unless you are experimenting.",
     "Les deux ne comptent que sur un écran HDR. Le sidecar capture en SDR pour "
     "l’instant, laissez-les à 1.00 sauf pour expérimenter."},
    {"These three have no documented default, so they are written only once you "
     "move them. Clearing the box returns them to untouched, which leaves "
     "whatever the add-on does by itself.",
     "Ces trois-là n’ont pas de valeur par défaut documentée, ils ne sont donc "
     "écrits qu’une fois modifiés. Vider la case les remet à l’état intact, ce "
     "qui laisse l’add-on faire ce qu’il fait de lui-même."},
    {"Enable the add-on's upscaling (work in progress)",
     "Activer la mise à l’échelle de l’add-on (en cours)"},
    {"The add-on marks this unfinished, and the sidecar feeds it a "
     "native-resolution DLAA contract, so it usually reports that it fell back to "
     "native. Off is the tested path.",
     "L’add-on la marque comme inachevée, et le sidecar lui fournit un contrat "
     "DLAA en résolution native, donc il indique généralement être revenu à la "
     "native. Désactivé est le chemin testé."},
    {"Hook mode",
     "Mode d’interception"},
    {"0 turns neural rendering off entirely, 1 adds Streamline hooks, 2 is NGX "
     "only. Two is what this sidecar wants: it makes the NGX calls itself and "
     "there is no Streamline in the process.",
     "0 désactive complètement le rendu neuronal, 1 ajoute les interceptions "
     "Streamline, 2 est NGX seul. Deux est ce que veut ce sidecar : il fait "
     "lui-même les appels NGX et il n’y a pas de Streamline dans le processus."},
    {"Advanced",
     "Avancé"},
    {"Local structure",
     "Structure locale"},
    {"How hard the model works on fine surface detail -- stonework, cloth weave, "
     "wood grain. Raising it sharpens texture and also sharpens whatever the "
     "model got wrong about it.",
     "À quel point le modèle travaille les détails fins des surfaces — pierre, "
     "trame du tissu, veinure du bois. L’augmenter affûte la texture et aussi "
     "tout ce que le modèle a mal compris."},
    {"Local tone",
     "Tonalité locale"},
    {"Local contrast: how far the model pushes light against dark within a small "
     "area. This is the dial most likely to change the mood of a scene rather "
     "than its detail.",
     "Contraste local : jusqu’où le modèle pousse la lumière contre l’ombre sur "
     "une petite zone. C’est le réglage le plus susceptible de changer l’ambiance "
     "d’une scène plutôt que ses détails."},
    {"Skin structure",
     "Structure de la peau"},
    {"Faces and skin specifically. The one people reach for after watching a "
     "comparison video, and the one most likely to look wrong when overdone -- "
     "skin is where anybody spots a mistake.",
     "Visages et peau en particulier. Celui qu’on touche après une vidéo "
     "comparative, et celui qui a le plus de chances de mal rendre s’il est "
     "poussé — sur la peau, tout le monde repère une erreur."},
    {"The strip of numbers the overlay draws in its own top-left corner: frame "
     "rate, latency, which pass is running and how many frames were dropped. It "
     "is drawn by the overlay, not by the game, so it never reaches a screenshot "
     "the game takes.",
     "La bande de chiffres que l’overlay dessine dans son coin supérieur gauche : "
     "FPS, latence, passe active et images abandonnées. Elle est dessinée par "
     "l’overlay, pas par le jeu, donc elle n’apparaît jamais dans une capture "
     "d’écran du jeu."},
    {"Whether the overlay covers the game the moment it launches. Off starts it "
     "hidden, which is the honest way to look at the untouched frame first and "
     "then bring the neural pass in over the top of it.",
     "Si l’overlay couvre le jeu dès son lancement. Désactivé le démarre masqué, "
     "la façon honnête de regarder d’abord l’image intacte puis d’appliquer la "
     "passe neuronale par-dessus."},
    {"CNN F. The default here: clamps history hard, which suits estimated motion "
     "vectors.",
     "CNN F. Le réglage par défaut ici : limite fortement l’historique, ce qui "
     "convient aux vecteurs de mouvement estimés."},
    {"CNN E. Clamps hardest. Try this first if motion smears or flames and lights "
     "flicker.",
     "CNN E. Limite le plus. À essayer en premier si le mouvement bave ou si les "
     "flammes et lumières scintillent."},
    {"Transformer K. The SDK default for DLAA. Sharpest when the vectors are "
     "trustworthy.",
     "Transformer K. Le défaut du SDK pour le DLAA. Le plus net quand les "
     "vecteurs sont fiables."},
    {"Transformer J. The older transformer preset.",
     "Transformer J. L’ancien préréglage transformer."},
    {"Whatever the runtime picks for itself.",
     "Ce que le runtime choisit lui-même."},
    {"Show the HUD",
     "Afficher le HUD"},
    {"Show the overlay on start",
     "Afficher l’overlay au démarrage"},
    {"Reset to defaults",
     "Rétablir les valeurs par défaut"},
    {"%llu earlier line(s) dropped",
     "%llu ligne(s) précédente(s) abandonnée(s)"},
    {"Last error",
     "Dernière erreur"},
    {"The overlay (sidecar.log)",
     "L’overlay (sidecar.log)"},
    {"This manager",
     "Ce gestionnaire"},
    {"The overlay has not written anything yet.",
     "L’overlay n’a encore rien écrit."},
    {"Window class not found.",
     "Classe de fenêtre introuvable."},
    {"World of Warcraft is not running.",
     "World of Warcraft n’est pas lancé."},
    {"World of Warcraft must run in borderless windowed mode.\nExclusive "
     "fullscreen has no compositor surface to capture.",
     "World of Warcraft doit tourner en mode fenêtré sans bordure.\nLe plein "
     "écran exclusif n’a pas de surface de compositeur à capturer."},
    {"%hs is not supported. RTX 40 or RTX 50 required.",
     "%hs n’est pas pris en charge. RTX 40 ou RTX 50 requise."},
    {"Failed to create the pipeline.",
     "Impossible de créer le pipeline."},
    {"An overlay is already running.\nStop it from the manager before starting "
     "another.",
     "Un overlay est déjà lancé.\nArrêtez-le depuis le gestionnaire avant d’en "
     "lancer un autre."},
    {"The graphics device was reset and could not be rebuilt.",
     "Le périphérique graphique a été réinitialisé et n’a pas pu être reconstruit."},
    {"Hotkeys",
     "Raccourcis clavier"},
    {"off",
     "désactivé"},
    {"Start or stop the overlay (while this window is open)",
     "Lancer ou arrêter l’overlay (tant que cette fenêtre est ouverte)"},
    {"Show or hide the overlay: instant A/B against the untouched game",
     "Afficher ou masquer l’overlay : A/B instantané avec le jeu intact"},
    {"Show or hide the frame-time HUD",
     "Afficher ou masquer le HUD des temps d’image"},
    {"Panic: take the overlay down, always",
     "Panique : retirer l’overlay, toujours"},
    {"Change them on the Tuning page.",
     "Modifiables dans la page Réglages."},
    {"Written like Ctrl+Alt+D or Shift+Alt+F9. Each needs Ctrl, Alt or Win, "
     "because Windows takes the combination away from the game. Leave one empty "
     "to switch it off.",
     "S’écrivent comme Ctrl+Alt+D ou Shift+Alt+F9. Chacun nécessite Ctrl, Alt ou "
     "Win, car Windows retire la combinaison au jeu. Laissez-en un vide pour le "
     "désactiver."},
    {"Start / stop overlay",
     "Lancer / arrêter l’overlay"},
    {"Show / hide overlay",
     "Afficher / masquer l’overlay"},
    {"Show / hide HUD",
     "Afficher / masquer le HUD"},
    {"not a key combination",
     "pas une combinaison de touches"},
    {"Language",
     "Langue"},
    {"Interface theme",
     "Thème de l’interface"},
    {"Stormwind",
     "Hurlevent"},
    {"Quest log",
     "Journal de quêtes"},
    {"Neural strength",
     "Intensité neuronale"},
    {"How many times DLSS 5 runs over each frame. One pass is subtle. Two or "
     "three push the picture further from the original -- closer to the heavily "
     "processed look in demonstration videos -- and each extra pass costs another "
     "full neural pass of GPU time.",
     "Combien de fois DLSS 5 passe sur chaque image. Une passe est subtile. Deux "
     "ou trois éloignent davantage l’image de l’original — plus proche du rendu "
     "très traité des vidéos de démonstration — et chaque passe supplémentaire "
     "coûte une passe neuronale complète de temps GPU."},
    {"1x  Natural",
     "1x  Naturel"},
    {"2x  Stronger",
     "2x  Plus fort"},
    {"3x  Strongest",
     "3x  Maximum"},
    {"Closest to the game",
     "Le plus proche du jeu"},
    {"About twice the GPU time",
     "Environ deux fois le temps GPU"},
    {"About three times the GPU time",
     "Environ trois fois le temps GPU"},
    {"Four passes, set in sidecar.toml. Pick one above to go back.",
     "Quatre passes, défini dans sidecar.toml. Choisissez-en un ci-dessus pour "
     "revenir."},
    {"The Off preset runs no neural pass, so this has no effect until you pick "
     "another look.",
     "Le préréglage Désactivé n’applique aucune passe neuronale, donc ceci n’a "
     "aucun effet tant que vous n’avez pas choisi un autre rendu."},
};

const size_t kFrenchTableSize = sizeof(kFrenchTable) / sizeof(kFrenchTable[0]);

}  // namespace sidecar
