#include "core/I18nTable.h"

// Chinese interface text. Generated by tools/gen_translation_table.py;
// the conventions are the Russian table's (I18nRu.cpp): keys are the English
// source text exactly, format specifiers keep their order, and file names,
// add-on key names and the log are never translated.

namespace sidecar {

const TranslationPair kChineseTable[] = {
    {"Status",
     "状态"},
    {"Setup",
     "安装"},
    {"Checks",
     "检查"},
    {"Tuning",
     "调校"},
    {"Log",
     "日志"},
    {"Neural rendering for World of Warcraft, from outside the game process",
     "为《魔兽世界》提供神经渲染，全程在游戏进程之外"},
    {"Stop overlay",
     "停止叠加层"},
    {"Start overlay",
     "启动叠加层"},
    {"Before you use this",
     "使用前须知"},
    {"This sidecar never loads code into Wow.exe. That is what makes it safe, and "
     "it is checked automatically every time it is built.\n\nReShade placed next "
     "to Wow.exe is a different thing entirely, and Blizzard bans accounts for "
     "it. This tool will refuse to install there and will refuse to run if it "
     "finds an injector in your WoW folder.\n\nNo third-party tool can promise "
     "you will never be banned. What this one can promise is that it does not do "
     "any of the things Blizzard bans people for.",
     "本工具从不向 Wow.exe 加载任何代码。这正是它安全的原因，而且每次构建都会自动检查这一点。\n\n把 ReShade 放在 Wow.exe "
     "旁边是完全不同的事，暴雪会因此封号。本工具拒绝安装到那里；如果在你的 WoW "
     "文件夹中发现注入器，它也会拒绝运行。\n\n没有任何第三方工具能保证你永远不会被封号。本工具能保证的是：暴雪封号的那些行为，它一样都不做。"},
    {"I understand",
     "我已了解"},
    {"Live",
     "实时"},
    {"OVERLAY FPS",
     "叠加层帧率"},
    {"LATENCY p50",
     "延迟 p50"},
    {"LATENCY p99",
     "延迟 p99"},
    {"CAPTURED FPS",
     "捕获帧率"},
    {"WoW: borderless",
     "WoW：无边框窗口"},
    {"WoW: not borderless",
     "WoW：不是无边框"},
    {"WoW: not running",
     "WoW：未运行"},
    {"Overlay: running",
     "叠加层：运行中"},
    {"Overlay: stopped",
     "叠加层：已停止"},
    {"READY",
     "就绪"},
    {"CHECK",
     "注意"},
    {"BLOCKED",
     "已阻止"},
    {"Hide overlay (A/B compare)",
     "隐藏叠加层（A/B 对比）"},
    {"Show overlay",
     "显示叠加层"},
    {"Hide HUD",
     "隐藏 HUD"},
    {"Show HUD",
     "显示 HUD"},
    {"Hiding the overlay uncovers the untouched game without stopping capture.",
     "隐藏叠加层可显示未经处理的游戏画面，而不会停止捕获。"},
    {"GPU MEMORY USED BY THE SIDECAR",
     "本工具占用的显存"},
    {"  --  SPILLING",
     "  ——  溢出"},
    {"This is the sidecar's own share, not the whole card. More of it would not "
     "be faster -- the pass allocates what it needs. The number that matters is "
     "whether any has spilled.",
     "这是本工具自己的占用，而不是整张显卡。更多显存并不会更快——该处理只分配它需要的量。关键在于是否有显存溢出。"},
    {"WHERE THE FRAME GOES",
     "每帧时间去向"},
    {"Frames",
     "帧"},
    {"%llu presented, %llu dropped",
     "已显示 %llu，已丢弃 %llu"},
    {"Pass",
     "处理"},
    {"Runtime",
     "运行时"},
    {"Verdict",
     "结论"},
    {"playable",
     "可玩"},
    {"marginal",
     "勉强"},
    {"too slow",
     "太慢"},
    {"The overlay is starting. Numbers appear after the first few frames.",
     "叠加层正在启动。前几帧之后会出现数据。"},
    {"Nothing running.",
     "没有运行中的内容。"},
    {"The card is full, so the driver is moving resources to system memory and "
     "every frame waits on the PCIe bus. It shows below as a huge GPU wait with "
     "the GPU nearly idle, which is easy to mistake for a slow neural "
     "pass.\n\nClose what else is using the card -- browsers, streaming and "
     "capture tools, anything compositing a second monitor -- and lower the "
     "game's texture quality. Nothing in this tool can make room.",
     "显卡显存已满，驱动正在把资源移到系统内存，每一帧都在等待 PCIe 总线。下方会显示为巨大的 GPU 等待时间，而 GPU "
     "几乎空闲，很容易被误认为是神经处理太慢。\n\n关闭其他占用显卡的程序——浏览器、直播和录制工具、任何合成第二台显示器的程序——并降低游戏的纹理质量。本"
     "工具无法腾出显存。"},
    {"This is the desktop compositor's rate, not the sidecar's and not the game's "
     "-- the game may well be running far faster. It is usually set by your "
     "monitor's refresh rate and, on a multi-monitor setup with mismatched "
     "refresh rates, by the slowest one. Nothing in this tool can raise it.",
     "这是桌面合成器的速率，不是本工具的，也不是游戏的——游戏本身可能快得多。它通常由显示器刷新率决定；在刷新率不同的多显示器环境中，由最慢的那台决定。本工具"
     "无法提高它。"},
    {"The game is competing for the GPU. Measured on the development machine, the "
     "same scene ran at 11.7 fps with the game focused and 35.2 fps with it in "
     "the background, purely because an unfocused game throttles itself and hands "
     "the card back.\n\nCap the game's frame rate. This costs nothing: the "
     "overlay can never show more than the capture rate above, so every frame the "
     "game renders beyond that is discarded before it reaches here.",
     "游戏正在争抢 GPU。在开发机上实测，同一场景在游戏处于前台时为 11.7 fps，在后台时为 35.2 "
     "fps，仅仅因为失去焦点的游戏会自我限速并把显卡让出来。\n\n请限制游戏帧率。这没有任何代价：叠加层显示的帧数永远不会超过上方的捕获速率，游戏多渲染的"
     "每一帧都会在到达这里之前被丢弃。"},
    {"The overlay is presenting close to every frame Windows hands it, and there "
     "is memory to spare. Nothing to fix here.",
     "叠加层几乎显示了 Windows 交给它的每一帧，而且显存充足。这里没有需要修复的地方。"},
    {"Some checks are failing. Open Checks to see what.",
     "部分检查未通过。打开“检查”查看详情。"},
    {"Files are missing. Open Setup to install them.",
     "缺少文件。打开“安装”进行安装。"},
    {"Start World of Warcraft in borderless windowed mode, then press Start "
     "overlay.",
     "以无边框窗口模式启动《魔兽世界》，然后点击“启动叠加层”。"},
    {"Press Start overlay.",
     "点击“启动叠加层”。"},
    {"Playing with the overlay up",
     "开启叠加层时游玩"},
    {"The overlay covers the game completely and passes every click straight "
     "through to it, so play normally. It never takes focus, so whatever had the "
     "keyboard keeps it -- if the game is not responding, alt-tab to World of "
     "Warcraft once.\n\nCtrl+Alt+Backspace takes the overlay down from anywhere, "
     "without needing this window.",
     "叠加层完全覆盖游戏，并把每一次点击直接传给游戏，所以照常游玩即可。它从不抢占焦点，原来持有键盘的窗口会继续持有——如果游戏没有响应，用 Alt+Tab "
     "切换到《魔兽世界》一次即可。\n\nCtrl+Alt+Backspace 可在任何地方关闭叠加层，无需此窗口。"},
    {"Required files",
     "必需文件"},
    {"Three files have to sit next to the sidecar. None of them is ours to "
     "redistribute and nothing here downloads anything -- neither binary in this "
     "project can reach the network at all. Fetch them yourself, then point this "
     "at them.",
     "有三个文件必须放在本工具旁边。它们都不归我们分发，这里也不会下载任何东西——本项目的两个程序都完全无法联网。请自行获取，然后在这里指定它们。"},
    {"INSTALLED",
     "已安装"},
    {"MISSING",
     "缺失"},
    {"OPTIONAL",
     "可选"},
    {"Wanted as %s   |   Source: %s",
     "目标名称 %s   |   来源：%s"},
    {"Replace...",
     "替换..."},
    {"Choose file...",
     "选择文件..."},
    {"Remove",
     "移除"},
    {"Deletes the files listed above from this folder, and nothing else. It never "
     "touches a WoW installation. The sidecar's own two executables stay; delete "
     "the folder to be rid of them.",
     "仅从此文件夹删除上面列出的文件，不会删除其他任何东西。绝不会触碰 WoW 安装。本工具自己的两个程序会保留；删除整个文件夹即可移除它们。"},
    {"Also remove settings and logs",
     "同时移除设置和日志"},
    {"Yes, remove them",
     "是，移除"},
    {"Remove installed files",
     "移除已安装的文件"},
    {"Stop the overlay first -- the files are in use.",
     "请先停止叠加层——文件正在使用中。"},
    {"%zu file(s) would go.",
     "将移除 %zu 个文件。"},
    {"That file no longer exists.",
     "该文件已不存在。"},
    {"That is not a file.",
     "这不是一个文件。"},
    {"Already installed.",
     "已经安装。"},
    {"Could not copy it in: ",
     "无法复制："},
    {"Installed ",
     "已安装："},
    {"Could not remove ",
     "无法移除："},
    {". Stop the overlay and close anything using it, then try again.",
     "。请停止叠加层并关闭正在使用它的程序，然后重试。"},
    {"Removed ",
     "已移除："},
    {" file(s).",
     " 个文件。"},
    {"DLSS 5 neural rendering runtime",
     "DLSS 5 神经渲染运行时"},
    {"The neural network itself. On an RTX 40 card this must be a build patched "
     "for Ada; the stock runtime is Blackwell-only and fails at feature creation "
     "with no diagnostic.",
     "神经网络本体。在 RTX 40 显卡上必须使用为 Ada 打过补丁的版本；原版运行时仅支持 Blackwell，会在创建功能时失败且没有任何诊断信息。"},
    {"ReShade, with add-on support",
     "支持插件的 ReShade"},
    {"Hosts the add-on inside the sidecar's own process. The add-on-enabled build "
     "is required; the plain one loads no add-ons at all.",
     "在本工具自己的进程中承载插件。需要支持插件的版本；普通版本不会加载任何插件。"},
    {"RenoDX DLSS 5 add-on",
     "RenoDX DLSS 5 插件"},
    {"Detours the sidecar's own NGX calls and substitutes neural-rendered output. "
     "This is what makes the pass neural rather than a plain DLAA.",
     "拦截本工具自己的 NGX 调用，并替换为神经渲染的输出。正是它让处理成为神经渲染，而不只是普通的 DLAA。"},
    {"DLSS upscaling runtime",
     "DLSS 超分辨率运行时"},
    {"Optional. Only consulted if the add-on's work-in-progress upscaling path is "
     "switched on; neural rendering itself does not need it.",
     "可选。仅在开启插件尚未完成的超分辨率功能时使用；神经渲染本身不需要它。"},
    {"System checks",
     "系统检查"},
    {"Nothing here opens, reads, writes or hooks the game process. The import "
     "table of every binary is checked against that claim at build time.",
     "这里的任何内容都不会打开、读取、写入或挂钩游戏进程。每个程序的导入表都会在构建时对照这一点进行检查。"},
    {"WoW folder (used only to scan filenames for injectors)",
     "WoW 文件夹（仅用于按文件名扫描注入器）"},
    {"Browse...",
     "浏览..."},
    {"Detect",
     "检测"},
    {"Re-run checks",
     "重新检查"},
    {"Detected from Battle.net's own uninstall entry. Point this at the folder "
     "Wow.exe sits in, not its parent: an injector has to be next to the "
     "executable to be loaded by it. Nothing inside is opened -- only the file "
     "names are read.",
     "根据 Battle.net 自己的卸载记录检测到。请指向 Wow.exe "
     "所在的文件夹，而不是它的上级：注入器必须位于程序旁边才会被加载。不会打开其中任何文件——只读取文件名。"},
    {"Graphics adapter",
     "显卡"},
    {"No NVIDIA adapter found.",
     "未找到 NVIDIA 显卡。"},
    {"This sidecar needs an NVIDIA RTX 40 or RTX 50 card.",
     "本工具需要 NVIDIA RTX 40 或 RTX 50 显卡。"},
    {"RTX 40 (Ada) or RTX 50 (Blackwell) is required. Older cards are refused "
     "rather than run badly.",
     "需要 RTX 40（Ada）或 RTX 50（Blackwell）。较旧的显卡会被直接拒绝，而不是勉强运行。"},
    {"Display driver",
     "显示驱动"},
    {"No NVIDIA adapter to query.",
     "没有可查询的 NVIDIA 显卡。"},
    {"Install an NVIDIA RTX 40 or RTX 50 card.",
     "请安装 NVIDIA RTX 40 或 RTX 50 显卡。"},
    {"User-mode driver ",
     "用户模式驱动 "},
    {"Could not read the driver version.",
     "无法读取驱动版本。"},
    {"Not fatal. Update to a current NVIDIA driver if capture misbehaves.",
     "不严重。如果捕获异常，请更新到最新的 NVIDIA 驱动。"},
    {"Windows version",
     "Windows 版本"},
    {"Could not read the Windows build number.",
     "无法读取 Windows 内部版本号。"},
    {"Not fatal, but this project is only supported on Windows 11.",
     "不严重，但本项目仅支持 Windows 11。"},
    {"Build ",
     "版本 "},
    {"Windows 11 is required: the overlay depends on compositor behaviour that "
     "Windows 10 does not provide.",
     "需要 Windows 11：叠加层依赖 Windows 10 不具备的合成器行为。"},
    {"Display refresh rate",
     "显示器刷新率"},
    {"Could not read the current display mode.",
     "无法读取当前显示模式。"},
    {"Not fatal. Check your monitor settings if pacing looks wrong.",
     "不严重。如果帧节奏看起来不对，请检查显示器设置。"},
    {"Below 120 Hz the overlay's added latency is a larger share of the frame. It "
     "will still run.",
     "低于 120 Hz 时，叠加层增加的延迟在每帧中所占比例更大。仍然可以运行。"},
    {"Neural runtime",
     "神经运行时"},
    {"nvngx_dlssnr.dll not found next to the sidecar.",
     "在本工具旁边未找到 nvngx_dlssnr.dll。"},
    {"Optional until the neural pass ships. Without it the pipeline runs the "
     "passthrough pass.",
     "在神经处理推出前为可选。没有它时，流水线运行直通处理。"},
    {"Check the file is not locked by another process, and that the sidecar has "
     "permission to read it.",
     "请检查该文件是否被其他进程锁定，以及本工具是否有权限读取它。"},
    {"Supply a runtime built for this GPU, or the neural pass will fall back to "
     "passthrough.",
     "请提供为此 GPU 构建的运行时，否则神经处理将回退为直通。"},
    {"The pass will still try this build. If it fails, quote the SHA-256 above "
     "when reporting it.",
     "处理仍会尝试使用此版本。如果失败，报告时请附上上面的 SHA-256。"},
    {"ReShade host (optional)",
     "ReShade 宿主（可选）"},
    {"No ReShade host alongside the sidecar.",
     "本工具旁边没有 ReShade 宿主。"},
    {"Only needed for the ReShade-hosted neural pass. Install ReShade against the "
     "sidecar so it lands as dxgi.dll. Never place ReShade next to Wow.exe.",
     "仅在 ReShade 承载的神经处理中需要。请将 ReShade 安装到本工具上，使其成为 dxgi.dll。切勿把 ReShade 放在 "
     "Wow.exe 旁边。"},
    {"World of Warcraft window",
     "《魔兽世界》窗口"},
    {"WoW is not running.",
     "WoW 未运行。"},
    {"Start the game, then run the probes again.",
     "请启动游戏，然后重新运行检查。"},
    {" borderless windowed",
     " 无边框窗口"},
    {" windowed with a border, or exclusive fullscreen",
     " 带边框窗口或独占全屏"},
    {"Set WoW to borderless windowed. Exclusive fullscreen has no compositor "
     "surface to capture and yields black frames.",
     "请将 WoW 设置为无边框窗口。独占全屏没有可供捕获的合成器表面，只会得到黑屏。"},
    {"Injector scan of the WoW folder",
     "WoW 文件夹注入器扫描"},
    {"No WoW folder set, so nothing was scanned.",
     "未设置 WoW 文件夹，因此没有扫描任何内容。"},
    {"Point the manager at your WoW folder so it can check for injectors before "
     "launching.",
     "请为管理器指定 WoW 文件夹，以便它在启动前检查注入器。"},
    {"No injector loaders found.",
     "未发现注入加载器。"},
    {"Found: ",
     "发现："},
    {"Remove these from your WoW folder. Blizzard bans accounts for in-process "
     "injectors, and this tool refuses to run alongside one.",
     "请将它们从 WoW 文件夹中移除。暴雪会因进程内注入器封号，本工具拒绝与注入器一同运行。"},
    {"Sidecar install location",
     "本工具安装位置"},
    {"Move the sidecar outside your WoW folder. Anything sitting next to Wow.exe "
     "looks like an injector, which is the one thing this design exists to avoid.",
     "请把本工具移到 WoW 文件夹之外。任何位于 Wow.exe 旁边的东西看起来都像注入器——而这正是本设计要避免的。"},
    {" is the ",
     " 是 "},
    {" runtime, version ",
     " 运行时，版本 "},
    {" could not be read, so it has no digest.",
     " 无法读取，因此没有摘要。"},
    {" is not a build this manifest knows. Its SHA-256 is ",
     " 不是此清单已知的版本。其 SHA-256 为 "},
    {" -- quote that when reporting it.",
     "——报告时请附上它。"},
    {"This GPU (",
     "此 GPU（"},
    {") is outside the supported matrix; neural rendering needs Ada or Blackwell.",
     "）不在支持范围内；神经渲染需要 Ada 或 Blackwell。"},
    {"This is the stock runtime, which is built for Blackwell. On an Ada card "
     "neural-rendering feature creation fails with no explanation. An "
     "Ada-compatible build of nvngx_dlssnr.dll is required.",
     "这是原版运行时，专为 Blackwell 构建。在 Ada 显卡上创建神经渲染功能会无故失败。需要兼容 Ada 的 nvngx_dlssnr.dll "
     "版本。"},
    {" runtime does not run on ",
     " 运行时无法在此运行："},
    {"Choose a look",
     "选择风格"},
    {"IN USE",
     "使用中"},
    {"Custom -- your settings do not match any preset.",
     "自定义——你的设置与任何预设都不匹配。"},
    {"Click one above to go back to a tested combination. Nothing is selected "
     "because the individual settings below have been moved away from all four.",
     "点击上方任一项即可回到经过测试的组合。之所以没有选中任何一项，是因为下方的单项设置已偏离全部四个预设。"},
    {"Pick one. Every setting below is chosen for you, and the combinations here "
     "are ones that have actually been run -- unlike most of the arrangements you "
     "can reach by moving sliders individually.",
     "选一个即可。下方的每项设置都会替你选好，这些组合都经过实际运行——而随意拖动单个滑块得到的大多数组合并没有。"},
    {"Recommended",
     "推荐"},
    {"The tuned default. Start here.",
     "调校好的默认值。从这里开始。"},
    {"Full neural intensity with the CNN F render preset, which clamps temporal "
     "history hard -- the right choice when motion vectors are estimated from "
     "colour rather than rendered by the game.",
     "使用 CNN F 渲染预设的完整神经强度，它会强力限制时间历史——当运动向量是根据颜色估算而非由游戏渲染时，这是正确的选择。"},
    {"Softer",
     "柔和"},
    {"Half strength. Use if the picture looks over-processed.",
     "一半强度。如果画面看起来处理过度，请使用它。"},
    {"The same pipeline with the neural result mixed in at 60%. Cheaper on the "
     "eyes for interface-heavy scenes, and the first thing to try if faces or "
     "text look waxy.",
     "同样的流水线，神经结果以 60% 混合。在界面较多的场景中更耐看；如果人脸或文字看起来像蜡像，首先尝试它。"},
    {"Most stable",
     "最稳定"},
    {"For smearing, or flicker on flames and lights.",
     "用于拖影，或火焰与灯光闪烁。"},
    {"Switches to CNN E, which clamps temporal history hardest, and eases the "
     "intensity. This is the preset for when motion looks smeared -- the "
     "estimated motion vectors are being confidently wrong and this contains them.",
     "切换到 CNN E（对时间历史限制最强），并降低强度。当运动出现拖影时使用此预设——估算的运动向量自信地出错，而它能加以约束。"},
    {"Off (A/B baseline)",
     "关闭（A/B 基准）"},
    {"Capture and present, untouched.",
     "捕获并显示，不做处理。"},
    {"No neural work at all, on the same capture and present path. This is the "
     "honest comparison: whatever you see here is what the overlay costs you "
     "before any neural rendering happens.",
     "完全没有神经处理，捕获与显示路径相同。这是诚实的对比：你在这里看到的，就是任何神经渲染之前叠加层本身的开销。"},
    {"Save settings",
     "保存设置"},
    {"Changes are not saved yet.",
     "更改尚未保存。"},
    {"Nothing here reaches the picture until it is written to sidecar.toml.",
     "在写入 sidecar.toml 之前，这些都不会影响画面。"},
    {"Restart the overlay to apply.",
     "重启叠加层后生效。"},
    {"Every individual setting",
     "全部单项设置"},
    {"Nothing in here is needed for normal use.",
     "正常使用无需这里的任何内容。"},
    {"Pipeline",
     "流水线"},
    {"These are written to sidecar.toml, and the neural ones are projected into "
     "ReShade.ini where the add-on reads them. The add-on reads that file once, "
     "when it loads, so a change reaches the picture at the overlay's next start "
     "-- not while it runs.",
     "这些会写入 sidecar.toml，其中的神经设置会同步到插件读取的 "
     "ReShade.ini。插件只在加载时读取一次该文件，因此更改会在叠加层下次启动时生效，而不是在运行中生效。"},
    {"Neural pass",
     "神经处理"},
    {"passthrough -- capture and present, untouched",
     "passthrough —— 捕获并显示，不做处理"},
    {"reshade -- DLSS 5 neural rendering",
     "reshade —— DLSS 5 神经渲染"},
    {"Passthrough is the honest A/B baseline: the same capture and present path "
     "with no neural work in it at all.",
     "直通是诚实的 A/B 基准：同样的捕获与显示路径，完全没有神经处理。"},
    {"DLSS preset",
     "DLSS 预设"},
    {"Optical flow grid",
     "光流网格"},
    {"1 -- finest, most expensive",
     "1 —— 最精细，开销最大"},
    {"4 -- default",
     "4 —— 默认"},
    {"Pixels per estimated motion vector. Finer costs more and is not obviously "
     "better: the vectors are estimated from colour, so a finer grid can sharpen "
     "the estimate or the error equally.",
     "每个估算运动向量对应的像素数。更精细开销更大，却不一定更好：向量是根据颜色估算的，更精细的网格可能让估算更准，也可能让误差更明显。"},
    {"Synthetic depth",
     "合成深度"},
    {"There is no real depth buffer to capture out of the composited frame, so a "
     "constant plane is bound instead. It costs temporal stability under motion "
     "rather than preventing NR from running; this dial is worth a try if motion "
     "smears.",
     "合成后的画面中没有真实的深度缓冲可供捕获，因此改为绑定一个恒定平面。这会牺牲运动时的时间稳定性，但不会阻止神经渲染运行；如果运动出现拖影，值得试试这个参"
     "数。"},
    {"Neural rendering strength",
     "神经渲染强度"},
    {"Passed straight through to the RenoDX add-on. The add-on owns what these "
     "mean; we only carry them.",
     "直接传给 RenoDX 插件。这些参数的含义由插件决定；我们只负责传递。"},
    {"Intensity",
     "强度"},
    {"How much of the neural result is mixed in. Start here.",
     "混入多少神经结果。从这里开始。"},
    {"Add-on preset",
     "插件预设"},
    {"Style",
     "风格"},
    {"Colour strength",
     "色彩强度"},
    {"At zero the add-on's colour handling collapses to black, so this is not a "
     "subtle dial.",
     "为零时插件的色彩处理会塌缩为黑色，所以这不是一个细微的参数。"},
    {"HDR transfer strength",
     "HDR 传递强度"},
    {"Paper-white scale",
     "纸白缩放"},
    {"Both only matter on an HDR display. The sidecar captures SDR today, so "
     "leave them at 1.00 unless you are experimenting.",
     "两者只在 HDR 显示器上有意义。本工具目前以 SDR 捕获，除非你在做实验，否则保持 1.00。"},
    {"These three have no documented default, so they are written only once you "
     "move them. Clearing the box returns them to untouched, which leaves "
     "whatever the add-on does by itself.",
     "这三项没有公开的默认值，因此只有在你调整后才会写入。清空输入框会恢复为不干预，由插件自行决定。"},
    {"Enable the add-on's upscaling (work in progress)",
     "启用插件的超分辨率（开发中）"},
    {"The add-on marks this unfinished, and the sidecar feeds it a "
     "native-resolution DLAA contract, so it usually reports that it fell back to "
     "native. Off is the tested path.",
     "插件将其标记为未完成，而本工具提供的是原生分辨率的 DLAA 约定，所以它通常会报告已回退到原生。关闭是经过测试的方式。"},
    {"Hook mode",
     "挂钩模式"},
    {"0 turns neural rendering off entirely, 1 adds Streamline hooks, 2 is NGX "
     "only. Two is what this sidecar wants: it makes the NGX calls itself and "
     "there is no Streamline in the process.",
     "0 完全关闭神经渲染，1 添加 Streamline 挂钩，2 仅 NGX。本工具需要的是 2：它自己发起 NGX 调用，进程中没有 "
     "Streamline。"},
    {"Overlay",
     "叠加层"},
    {"Advanced",
     "高级"},
    {"Local structure",
     "局部结构"},
    {"How hard the model works on fine surface detail -- stonework, cloth weave, "
     "wood grain. Raising it sharpens texture and also sharpens whatever the "
     "model got wrong about it.",
     "模型对表面细节的处理力度——石砌、织物纹理、木纹。调高会让纹理更锐利，也会让模型理解错的地方更锐利。"},
    {"Local tone",
     "局部色调"},
    {"Local contrast: how far the model pushes light against dark within a small "
     "area. This is the dial most likely to change the mood of a scene rather "
     "than its detail.",
     "局部对比度：模型在小区域内把明暗推开的程度。这个参数最可能改变场景的氛围，而不是细节。"},
    {"Skin structure",
     "皮肤结构"},
    {"Faces and skin specifically. The one people reach for after watching a "
     "comparison video, and the one most likely to look wrong when overdone -- "
     "skin is where anybody spots a mistake.",
     "专门针对人脸和皮肤。看完对比视频后大家最想调的参数，也是调过头时最容易出问题的——皮肤上的错误谁都看得出来。"},
    {"The strip of numbers the overlay draws in its own top-left corner: frame "
     "rate, latency, which pass is running and how many frames were dropped. It "
     "is drawn by the overlay, not by the game, so it never reaches a screenshot "
     "the game takes.",
     "叠加层在自己左上角绘制的一排数字：帧率、延迟、当前运行的处理以及丢弃的帧数。它由叠加层绘制而非游戏，因此永远不会出现在游戏截图中。"},
    {"Whether the overlay covers the game the moment it launches. Off starts it "
     "hidden, which is the honest way to look at the untouched frame first and "
     "then bring the neural pass in over the top of it.",
     "叠加层启动时是否立即覆盖游戏。关闭则以隐藏状态启动——这是先看未处理画面、再把神经处理叠加上去的诚实方式。"},
    {"CNN F. The default here: clamps history hard, which suits estimated motion "
     "vectors.",
     "CNN F。此处的默认值：强力限制历史，适合估算的运动向量。"},
    {"CNN E. Clamps hardest. Try this first if motion smears or flames and lights "
     "flicker.",
     "CNN E。限制最强。如果运动出现拖影或火焰灯光闪烁，先试这个。"},
    {"Transformer K. The SDK default for DLAA. Sharpest when the vectors are "
     "trustworthy.",
     "Transformer K。SDK 的 DLAA 默认值。运动向量可靠时最锐利。"},
    {"Transformer J. The older transformer preset.",
     "Transformer J。较早的 Transformer 预设。"},
    {"Whatever the runtime picks for itself.",
     "由运行时自行选择。"},
    {"Show the HUD",
     "显示 HUD"},
    {"Show the overlay on start",
     "启动时显示叠加层"},
    {"Reset to defaults",
     "恢复默认值"},
    {"%llu earlier line(s) dropped",
     "已丢弃之前的 %llu 行"},
    {"Last error",
     "最近的错误"},
    {"The overlay (sidecar.log)",
     "叠加层（sidecar.log）"},
    {"This manager",
     "本管理器"},
    {"The overlay has not written anything yet.",
     "叠加层尚未写入任何内容。"},
    {"Window class not found.",
     "未找到窗口类。"},
    {"World of Warcraft is not running.",
     "《魔兽世界》未运行。"},
    {"World of Warcraft must run in borderless windowed mode.\nExclusive "
     "fullscreen has no compositor surface to capture.",
     "《魔兽世界》必须以无边框窗口模式运行。\n独占全屏没有可供捕获的合成器表面。"},
    {"%hs is not supported. RTX 40 or RTX 50 required.",
     "不支持 %hs。需要 RTX 40 或 RTX 50。"},
    {"Failed to create the pipeline.",
     "无法创建流水线。"},
    {"An overlay is already running.\nStop it from the manager before starting "
     "another.",
     "已有一个叠加层在运行。\n请先在管理器中停止它，再启动新的。"},
    {"The graphics device was reset and could not be rebuilt.",
     "图形设备已重置，且无法重建。"},
    {"Hotkeys",
     "快捷键"},
    {"off",
     "关闭"},
    {"Start or stop the overlay (while this window is open)",
     "启动或停止叠加层（此窗口打开时）"},
    {"Show or hide the overlay: instant A/B against the untouched game",
     "显示或隐藏叠加层：与未处理画面即时 A/B 对比"},
    {"Show or hide the frame-time HUD",
     "显示或隐藏帧时间 HUD"},
    {"Panic: take the overlay down, always",
     "紧急：随时关闭叠加层"},
    {"Change them on the Tuning page.",
     "可在“调校”页面中修改。"},
    {"Written like Ctrl+Alt+D or Shift+Alt+F9. Each needs Ctrl, Alt or Win, "
     "because Windows takes the combination away from the game. Leave one empty "
     "to switch it off.",
     "写法如 Ctrl+Alt+D 或 Shift+Alt+F9。每个都需要 Ctrl、Alt 或 Win，因为 Windows "
     "会把该组合键从游戏中截走。留空即可关闭该快捷键。"},
    {"Start / stop overlay",
     "启动 / 停止叠加层"},
    {"Show / hide overlay",
     "显示 / 隐藏叠加层"},
    {"Show / hide HUD",
     "显示 / 隐藏 HUD"},
    {"not a key combination",
     "不是有效的组合键"},
    {"Language",
     "语言"},
    {"Interface theme",
     "界面主题"},
    {"Stormwind",
     "暴风城"},
    {"Quest log",
     "任务日志"},
    {"Dragonflight",
     "巨龙时代"},
    {"Neural strength",
     "神经强度"},
    {"How many times DLSS 5 runs over each frame. One pass is subtle. Two or "
     "three push the picture further from the original -- closer to the heavily "
     "processed look in demonstration videos -- and each extra pass costs another "
     "full neural pass of GPU time.",
     "DLSS 5 "
     "在每帧上运行的次数。一次很细微。两次或三次会让画面离原作更远——更接近演示视频中那种重度处理的效果——每多一次，就多消耗一次完整神经处理的 GPU "
     "时间。"},
    {"1x  Natural",
     "1x  自然"},
    {"2x  Stronger",
     "2x  更强"},
    {"3x  Strongest",
     "3x  最强"},
    {"Closest to the game",
     "最接近原游戏"},
    {"About twice the GPU time",
     "约两倍 GPU 时间"},
    {"About three times the GPU time",
     "约三倍 GPU 时间"},
    {"Four passes, set in sidecar.toml. Pick one above to go back.",
     "四次处理，在 sidecar.toml 中设置。选择上方任一项即可恢复。"},
    {"The Off preset runs no neural pass, so this has no effect until you pick "
     "another look.",
     "“关闭”预设不运行神经处理，因此在你选择其他风格之前，这一项不起作用。"},
};

const size_t kChineseTableSize = sizeof(kChineseTable) / sizeof(kChineseTable[0]);

}  // namespace sidecar
