#include "core/I18nTable.h"

// Arabic interface text. Generated by tools/gen_translation_table.py;
// the conventions are the Russian table's (I18nRu.cpp): keys are the English
// source text exactly, format specifiers keep their order, and file names,
// add-on key names and the log are never translated.

namespace sidecar {

const TranslationPair kArabicTable[] = {
    {"Status",
     "الحالة"},
    {"Setup",
     "الإعداد"},
    {"Checks",
     "الفحوصات"},
    {"Tuning",
     "الضبط"},
    {"Log",
     "السجل"},
    {"Neural rendering for World of Warcraft, from outside the game process",
     "عرض عصبي لـ World of Warcraft من خارج عملية اللعبة"},
    {"Stop overlay",
     "إيقاف الطبقة"},
    {"Start overlay",
     "تشغيل الطبقة"},
    {"Before you use this",
     "قبل الاستخدام"},
    {"This sidecar never loads code into Wow.exe. That is what makes it safe, and "
     "it is checked automatically every time it is built.\n\nReShade placed next "
     "to Wow.exe is a different thing entirely, and Blizzard bans accounts for "
     "it. This tool will refuse to install there and will refuse to run if it "
     "finds an injector in your WoW folder.\n\nNo third-party tool can promise "
     "you will never be banned. What this one can promise is that it does not do "
     "any of the things Blizzard bans people for.",
     "لا يحمّل هذا البرنامج المرافق أي شيفرة داخل Wow.exe أبدًا. هذا ما يجعله "
     "آمنًا، ويُتحقق منه تلقائيًا في كل بناء.\n\nوضع ReShade بجانب Wow.exe أمر "
     "مختلف تمامًا، وتحظر Blizzard الحسابات بسببه. ترفض هذه الأداة التثبيت هناك "
     "وترفض العمل إذا وجدت حاقنًا في مجلد WoW.\n\nلا تستطيع أي أداة خارجية أن "
     "تعدك بأنك لن تُحظر أبدًا. ما تعد به هذه الأداة هو أنها لا تفعل أيًا مما "
     "تحظر Blizzard الناس بسببه."},
    {"I understand",
     "فهمت"},
    {"Live",
     "مباشر"},
    {"OVERLAY FPS",
     "إطارات الطبقة"},
    {"LATENCY p50",
     "زمن الاستجابة p50"},
    {"LATENCY p99",
     "زمن الاستجابة p99"},
    {"CAPTURED FPS",
     "الإطارات الملتقطة"},
    {"WoW: borderless",
     "WoW: نافذة بلا حدود"},
    {"WoW: not borderless",
     "WoW: ليست بلا حدود"},
    {"WoW: not running",
     "WoW: لا تعمل"},
    {"Overlay: running",
     "الطبقة: تعمل"},
    {"Overlay: stopped",
     "الطبقة: متوقفة"},
    {"READY",
     "جاهز"},
    {"CHECK",
     "تحقق"},
    {"BLOCKED",
     "محظور"},
    {"Hide overlay (A/B compare)",
     "إخفاء الطبقة (مقارنة A/B)"},
    {"Show overlay",
     "إظهار الطبقة"},
    {"Hide HUD",
     "إخفاء HUD"},
    {"Show HUD",
     "إظهار HUD"},
    {"Hiding the overlay uncovers the untouched game without stopping capture.",
     "إخفاء الطبقة يكشف اللعبة دون معالجة من غير إيقاف الالتقاط."},
    {"GPU MEMORY USED BY THE SIDECAR",
     "ذاكرة الرسوميات التي يستخدمها البرنامج المرافق"},
    {"  --  SPILLING",
     "  —  فيضان"},
    {"This is the sidecar's own share, not the whole card. More of it would not "
     "be faster -- the pass allocates what it needs. The number that matters is "
     "whether any has spilled.",
     "هذه حصة البرنامج المرافق وحده، لا البطاقة كلها. المزيد منها لن يجعله أسرع؛ "
     "فالمرور يحجز ما يحتاجه. المهم هو هل فاض شيء منها."},
    {"WHERE THE FRAME GOES",
     "أين يذهب الإطار"},
    {"Frames",
     "الإطارات"},
    {"%llu presented, %llu dropped",
     "%llu معروضة، %llu مُسقطة"},
    {"Pass",
     "المرور"},
    {"Runtime",
     "بيئة التشغيل"},
    {"Verdict",
     "الحكم"},
    {"playable",
     "قابل للعب"},
    {"marginal",
     "على الحد"},
    {"too slow",
     "بطيء جدًا"},
    {"The overlay is starting. Numbers appear after the first few frames.",
     "الطبقة تبدأ. تظهر الأرقام بعد الإطارات الأولى."},
    {"Nothing running.",
     "لا شيء يعمل."},
    {"The card is full, so the driver is moving resources to system memory and "
     "every frame waits on the PCIe bus. It shows below as a huge GPU wait with "
     "the GPU nearly idle, which is easy to mistake for a slow neural "
     "pass.\n\nClose what else is using the card -- browsers, streaming and "
     "capture tools, anything compositing a second monitor -- and lower the "
     "game's texture quality. Nothing in this tool can make room.",
     "البطاقة ممتلئة، لذا ينقل التعريف الموارد إلى ذاكرة النظام وينتظر كل إطار "
     "ناقل PCIe. يظهر ذلك في الأسفل كانتظار هائل لمعالج الرسوميات وهو شبه خامل، "
     "ومن السهل الخلط بينه وبين مرور عصبي بطيء.\n\nأغلق ما يستخدم البطاقة أيضًا — "
     "المتصفحات وأدوات البث والتسجيل وأي شيء يركّب شاشة ثانية — وخفّض جودة "
     "الأنسجة في اللعبة. لا شيء في هذه الأداة يستطيع إفساح المجال."},
    {"This is the desktop compositor's rate, not the sidecar's and not the game's "
     "-- the game may well be running far faster. It is usually set by your "
     "monitor's refresh rate and, on a multi-monitor setup with mismatched "
     "refresh rates, by the slowest one. Nothing in this tool can raise it.",
     "هذا معدل مركّب سطح المكتب، لا معدل البرنامج المرافق ولا اللعبة — فقد تعمل "
     "اللعبة أسرع بكثير. يحدده عادة معدل تحديث شاشتك، ومع شاشات متعددة بمعدلات "
     "مختلفة أبطؤها. لا شيء في هذه الأداة يستطيع رفعه."},
    {"The game is competing for the GPU. Measured on the development machine, the "
     "same scene ran at 11.7 fps with the game focused and 35.2 fps with it in "
     "the background, purely because an unfocused game throttles itself and hands "
     "the card back.\n\nCap the game's frame rate. This costs nothing: the "
     "overlay can never show more than the capture rate above, so every frame the "
     "game renders beyond that is discarded before it reaches here.",
     "اللعبة تنافس على معالج الرسوميات. على جهاز التطوير عملت المشهد نفسه بسرعة "
     "11.7 إطارًا في الثانية واللعبة في المقدمة، و35.2 وهي في الخلفية، فقط لأن "
     "اللعبة غير المركّز عليها تحدّ من نفسها وتعيد البطاقة.\n\nحدّد معدل إطارات "
     "اللعبة. لا كلفة لذلك: لا يمكن للطبقة عرض أكثر من معدل الالتقاط أعلاه، لذا "
     "يُهمل كل إطار ترسمه اللعبة فوقه قبل أن يصل إلى هنا."},
    {"The overlay is presenting close to every frame Windows hands it, and there "
     "is memory to spare. Nothing to fix here.",
     "تعرض الطبقة تقريبًا كل إطار يسلّمه Windows، والذاكرة كافية. لا شيء يحتاج "
     "إلى إصلاح هنا."},
    {"Some checks are failing. Open Checks to see what.",
     "بعض الفحوصات تفشل. افتح الفحوصات لمعرفة أيها."},
    {"Files are missing. Open Setup to install them.",
     "هناك ملفات مفقودة. افتح الإعداد لتثبيتها."},
    {"Start World of Warcraft in borderless windowed mode, then press Start "
     "overlay.",
     "شغّل World of Warcraft في وضع نافذة بلا حدود، ثم اضغط تشغيل الطبقة."},
    {"Press Start overlay.",
     "اضغط تشغيل الطبقة."},
    {"Playing with the overlay up",
     "اللعب والطبقة مفعّلة"},
    {"The overlay covers the game completely and passes every click straight "
     "through to it, so play normally. It never takes focus, so whatever had the "
     "keyboard keeps it -- if the game is not responding, alt-tab to World of "
     "Warcraft once.\n\nCtrl+Alt+Backspace takes the overlay down from anywhere, "
     "without needing this window.",
     "تغطي الطبقة اللعبة بالكامل وتمرر كل نقرة إليها مباشرة، فالعب كالمعتاد. لا "
     "تأخذ التركيز أبدًا، فما كان يملك لوحة المفاتيح يحتفظ بها — إذا لم تستجب "
     "اللعبة فانتقل إلى World of Warcraft مرة واحدة بـ Alt+Tab.\n\nيزيل "
     "Ctrl+Alt+Backspace الطبقة من أي مكان دون الحاجة إلى هذه النافذة."},
    {"Required files",
     "الملفات المطلوبة"},
    {"Three files have to sit next to the sidecar. None of them is ours to "
     "redistribute and nothing here downloads anything -- neither binary in this "
     "project can reach the network at all. Fetch them yourself, then point this "
     "at them.",
     "يجب أن توجد ثلاثة ملفات بجانب البرنامج المرافق. لا يحق لنا إعادة توزيع أي "
     "منها ولا يُنزَّل هنا شيء — لا يستطيع أي من برنامجي المشروع الوصول إلى "
     "الشبكة إطلاقًا. احصل عليها بنفسك ثم أشر إليها هنا."},
    {"INSTALLED",
     "مثبّت"},
    {"MISSING",
     "مفقود"},
    {"OPTIONAL",
     "اختياري"},
    {"Wanted as %s   |   Source: %s",
     "المطلوب باسم %s   |   المصدر: %s"},
    {"Replace...",
     "استبدال..."},
    {"Choose file...",
     "اختيار ملف..."},
    {"Remove",
     "إزالة"},
    {"Deletes the files listed above from this folder, and nothing else. It never "
     "touches a WoW installation. The sidecar's own two executables stay; delete "
     "the folder to be rid of them.",
     "يحذف الملفات المذكورة أعلاه من هذا المجلد ولا شيء غيرها. لا يلمس أي تثبيت "
     "لـ WoW أبدًا. يبقى برنامجا البرنامج المرافق؛ احذف المجلد للتخلص منهما."},
    {"Also remove settings and logs",
     "إزالة الإعدادات والسجلات أيضًا"},
    {"Yes, remove them",
     "نعم، أزلها"},
    {"Remove installed files",
     "إزالة الملفات المثبتة"},
    {"Stop the overlay first -- the files are in use.",
     "أوقف الطبقة أولًا — الملفات قيد الاستخدام."},
    {"%zu file(s) would go.",
     "سيُزال %zu ملف."},
    {"That file no longer exists.",
     "ذلك الملف لم يعد موجودًا."},
    {"That is not a file.",
     "هذا ليس ملفًا."},
    {"Already installed.",
     "مثبّت بالفعل."},
    {"DLSS 5 neural rendering runtime",
     "بيئة تشغيل العرض العصبي DLSS 5"},
    {"The neural network itself. On an RTX 40 card this must be a build patched "
     "for Ada; the stock runtime is Blackwell-only and fails at feature creation "
     "with no diagnostic.",
     "الشبكة العصبية نفسها. على بطاقة RTX 40 يجب أن تكون نسخة معدّلة لـ Ada؛ "
     "فبيئة التشغيل الأصلية لـ Blackwell فقط وتفشل عند إنشاء الميزة دون أي تشخيص."},
    {"ReShade, with add-on support",
     "ReShade مع دعم الإضافات"},
    {"Hosts the add-on inside the sidecar's own process. The add-on-enabled build "
     "is required; the plain one loads no add-ons at all.",
     "يستضيف الإضافة داخل عملية البرنامج المرافق نفسها. تلزم النسخة الداعمة "
     "للإضافات؛ فالعادية لا تحمّل أي إضافة."},
    {"RenoDX DLSS 5 add-on",
     "إضافة RenoDX DLSS 5"},
    {"Detours the sidecar's own NGX calls and substitutes neural-rendered output. "
     "This is what makes the pass neural rather than a plain DLAA.",
     "تحوّل استدعاءات NGX الخاصة بالبرنامج المرافق وتستبدل المخرجات بأخرى معروضة "
     "عصبيًا. هذا ما يجعل المرور عصبيًا لا مجرد DLAA."},
    {"DLSS upscaling runtime",
     "بيئة تشغيل التكبير DLSS"},
    {"Optional. Only consulted if the add-on's work-in-progress upscaling path is "
     "switched on; neural rendering itself does not need it.",
     "اختيارية. لا تُستخدم إلا إذا فُعّل مسار التكبير التجريبي في الإضافة؛ العرض "
     "العصبي نفسه لا يحتاجها."},
    {"System checks",
     "فحوصات النظام"},
    {"Nothing here opens, reads, writes or hooks the game process. The import "
     "table of every binary is checked against that claim at build time.",
     "لا شيء هنا يفتح عملية اللعبة أو يقرؤها أو يكتب فيها أو يعترضها. يُفحص جدول "
     "الاستيراد لكل برنامج مقابل هذا الادعاء عند البناء."},
    {"WoW folder (used only to scan filenames for injectors)",
     "مجلد WoW (يُستخدم فقط لفحص أسماء الملفات بحثًا عن حاقنات)"},
    {"Browse...",
     "استعراض..."},
    {"Detect",
     "اكتشاف"},
    {"Re-run checks",
     "إعادة الفحوصات"},
    {"Detected from Battle.net's own uninstall entry. Point this at the folder "
     "Wow.exe sits in, not its parent: an injector has to be next to the "
     "executable to be loaded by it. Nothing inside is opened -- only the file "
     "names are read.",
     "اكتُشف من مدخل إلغاء التثبيت الخاص بـ Battle.net. أشر إلى المجلد الذي يوجد "
     "فيه Wow.exe لا إلى المجلد الأعلى: يجب أن يكون الحاقن بجانب البرنامج كي "
     "يُحمَّل. لا يُفتح شيء في الداخل — تُقرأ أسماء الملفات فقط."},
    {"Graphics adapter",
     "محول الرسوميات"},
    {"No NVIDIA adapter found.",
     "لم يُعثر على محول NVIDIA."},
    {"This sidecar needs an NVIDIA RTX 40 or RTX 50 card.",
     "يحتاج هذا البرنامج المرافق إلى بطاقة NVIDIA RTX 40 أو RTX 50."},
    {"RTX 40 (Ada) or RTX 50 (Blackwell) is required. Older cards are refused "
     "rather than run badly.",
     "تلزم RTX 40 (Ada) أو RTX 50 (Blackwell). تُرفض البطاقات الأقدم بدل أن تعمل "
     "بشكل سيئ."},
    {"Display driver",
     "تعريف الشاشة"},
    {"No NVIDIA adapter to query.",
     "لا يوجد محول NVIDIA للاستعلام."},
    {"Install an NVIDIA RTX 40 or RTX 50 card.",
     "ركّب بطاقة NVIDIA RTX 40 أو RTX 50."},
    {"Could not read the driver version.",
     "تعذرت قراءة إصدار التعريف."},
    {"Not fatal. Update to a current NVIDIA driver if capture misbehaves.",
     "ليس خطيرًا. حدّث إلى تعريف NVIDIA حديث إذا أساء الالتقاط التصرف."},
    {"Windows version",
     "إصدار Windows"},
    {"Could not read the Windows build number.",
     "تعذرت قراءة رقم بناء Windows."},
    {"Not fatal, but this project is only supported on Windows 11.",
     "ليس خطيرًا، لكن هذا المشروع مدعوم على Windows 11 فقط."},
    {"Windows 11 is required: the overlay depends on compositor behaviour that "
     "Windows 10 does not provide.",
     "يلزم Windows 11: تعتمد الطبقة على سلوك في المركّب لا يوفره Windows 10."},
    {"Display refresh rate",
     "معدل تحديث الشاشة"},
    {"Could not read the current display mode.",
     "تعذرت قراءة وضع العرض الحالي."},
    {"Not fatal. Check your monitor settings if pacing looks wrong.",
     "ليس خطيرًا. راجع إعدادات الشاشة إذا بدا التوقيت خاطئًا."},
    {"Below 120 Hz the overlay's added latency is a larger share of the frame. It "
     "will still run.",
     "تحت 120 هرتز يصبح التأخير الذي تضيفه الطبقة نسبة أكبر من الإطار. ستعمل مع "
     "ذلك."},
    {"Neural runtime",
     "بيئة التشغيل العصبية"},
    {"nvngx_dlssnr.dll not found next to the sidecar.",
     "لم يُعثر على nvngx_dlssnr.dll بجانب البرنامج المرافق."},
    {"Optional until the neural pass ships. Without it the pipeline runs the "
     "passthrough pass.",
     "اختيارية حتى يصدر المرور العصبي. بدونها يعمل خط المعالجة بالمرور المباشر."},
    {"Check the file is not locked by another process, and that the sidecar has "
     "permission to read it.",
     "تحقق من أن الملف غير مقفل من عملية أخرى وأن للبرنامج المرافق إذن قراءته."},
    {"Supply a runtime built for this GPU, or the neural pass will fall back to "
     "passthrough.",
     "وفّر بيئة تشغيل مبنية لهذا المعالج، وإلا عاد المرور العصبي إلى المرور "
     "المباشر."},
    {"The pass will still try this build. If it fails, quote the SHA-256 above "
     "when reporting it.",
     "سيحاول المرور مع هذه النسخة على أي حال. إن فشل فاذكر قيمة SHA-256 أعلاه عند "
     "الإبلاغ."},
    {"ReShade host (optional)",
     "مضيف ReShade (اختياري)"},
    {"No ReShade host alongside the sidecar.",
     "لا يوجد مضيف ReShade بجانب البرنامج المرافق."},
    {"Only needed for the ReShade-hosted neural pass. Install ReShade against the "
     "sidecar so it lands as dxgi.dll. Never place ReShade next to Wow.exe.",
     "لا يلزم إلا للمرور العصبي المستضاف في ReShade. ثبّت ReShade على البرنامج "
     "المرافق ليصبح dxgi.dll. لا تضع ReShade بجانب Wow.exe أبدًا."},
    {"World of Warcraft window",
     "نافذة World of Warcraft"},
    {"WoW is not running.",
     "WoW لا تعمل."},
    {"Start the game, then run the probes again.",
     "شغّل اللعبة ثم أعد الفحوصات."},
    {"Set WoW to borderless windowed. Exclusive fullscreen has no compositor "
     "surface to capture and yields black frames.",
     "اضبط WoW على نافذة بلا حدود. ملء الشاشة الحصري لا يملك سطح مركّب يمكن "
     "التقاطه ويعطي إطارات سوداء."},
    {"Injector scan of the WoW folder",
     "فحص الحاقنات في مجلد WoW"},
    {"No WoW folder set, so nothing was scanned.",
     "لم يُحدد مجلد WoW، لذا لم يُفحص شيء."},
    {"Point the manager at your WoW folder so it can check for injectors before "
     "launching.",
     "أشر المدير إلى مجلد WoW ليفحص الحاقنات قبل التشغيل."},
    {"No injector loaders found.",
     "لم يُعثر على محمّلات حقن."},
    {"Remove these from your WoW folder. Blizzard bans accounts for in-process "
     "injectors, and this tool refuses to run alongside one.",
     "أزلها من مجلد WoW. تحظر Blizzard الحسابات بسبب الحاقنات داخل العملية، وترفض "
     "هذه الأداة العمل بجانب أي منها."},
    {"Sidecar install location",
     "موقع تثبيت البرنامج المرافق"},
    {"Move the sidecar outside your WoW folder. Anything sitting next to Wow.exe "
     "looks like an injector, which is the one thing this design exists to avoid.",
     "انقل البرنامج المرافق خارج مجلد WoW. كل ما يوجد بجانب Wow.exe يبدو حاقنًا، "
     "وهو بالضبط ما صُمم هذا البرنامج لتجنبه."},
    {"Choose a look",
     "اختر مظهرًا"},
    {"IN USE",
     "مستخدم"},
    {"Custom -- your settings do not match any preset.",
     "مخصص — إعداداتك لا تطابق أي إعداد مسبق."},
    {"Click one above to go back to a tested combination. Nothing is selected "
     "because the individual settings below have been moved away from all four.",
     "انقر أحدها أعلاه للعودة إلى تركيبة مجربة. لا شيء محدد لأن الإعدادات الفردية "
     "أدناه ابتعدت عن الأربعة."},
    {"Pick one. Every setting below is chosen for you, and the combinations here "
     "are ones that have actually been run -- unlike most of the arrangements you "
     "can reach by moving sliders individually.",
     "اختر واحدًا. كل إعداد أدناه يُختار لك، وهذه التركيبات جُربت فعلًا — بخلاف "
     "معظم ما يمكن الوصول إليه بتحريك المنزلقات منفردة."},
    {"Recommended",
     "موصى به"},
    {"The tuned default. Start here.",
     "الافتراضي المضبوط. ابدأ من هنا."},
    {"Full neural intensity with the CNN F render preset, which clamps temporal "
     "history hard -- the right choice when motion vectors are estimated from "
     "colour rather than rendered by the game.",
     "شدة عصبية كاملة مع إعداد العرض CNN F الذي يقيّد السجل الزمني بقوة — الخيار "
     "الصحيح عندما تُقدّر متجهات الحركة من اللون بدل أن ترسمها اللعبة."},
    {"Softer",
     "أنعم"},
    {"Half strength. Use if the picture looks over-processed.",
     "نصف الشدة. استخدمه إذا بدت الصورة مفرطة المعالجة."},
    {"The same pipeline with the neural result mixed in at 60%. Cheaper on the "
     "eyes for interface-heavy scenes, and the first thing to try if faces or "
     "text look waxy.",
     "خط المعالجة نفسه مع مزج النتيجة العصبية بنسبة 60%. أريح للعين في المشاهد "
     "المزدحمة بالواجهة، وأول ما يُجرّب إذا بدت الوجوه أو النصوص شمعية."},
    {"Most stable",
     "الأكثر ثباتًا"},
    {"For smearing, or flicker on flames and lights.",
     "للتلطخ أو الوميض في اللهب والأضواء."},
    {"Switches to CNN E, which clamps temporal history hardest, and eases the "
     "intensity. This is the preset for when motion looks smeared -- the "
     "estimated motion vectors are being confidently wrong and this contains them.",
     "ينتقل إلى CNN E الذي يقيّد السجل الزمني أقصى تقييد، ويخفف الشدة. هذا "
     "الإعداد لحين تبدو الحركة ملطخة — متجهات الحركة المقدّرة مخطئة بثقة وهذا "
     "يحتويها."},
    {"Off (A/B baseline)",
     "إيقاف (مرجع A/B)"},
    {"Capture and present, untouched.",
     "التقاط وعرض دون مساس."},
    {"No neural work at all, on the same capture and present path. This is the "
     "honest comparison: whatever you see here is what the overlay costs you "
     "before any neural rendering happens.",
     "لا عمل عصبي إطلاقًا، على مسار الالتقاط والعرض نفسه. هذه هي المقارنة "
     "الصادقة: ما تراه هنا هو كلفة الطبقة قبل أي عرض عصبي."},
    {"Save settings",
     "حفظ الإعدادات"},
    {"Changes are not saved yet.",
     "لم تُحفظ التغييرات بعد."},
    {"Nothing here reaches the picture until it is written to sidecar.toml.",
     "لا يصل شيء من هذا إلى الصورة حتى يُكتب في sidecar.toml."},
    {"Restart the overlay to apply.",
     "أعد تشغيل الطبقة للتطبيق."},
    {"Every individual setting",
     "كل الإعدادات الفردية"},
    {"Nothing in here is needed for normal use.",
     "لا شيء هنا لازم للاستخدام العادي."},
    {"Pipeline",
     "خط المعالجة"},
    {"These are written to sidecar.toml, and the neural ones are projected into "
     "ReShade.ini where the add-on reads them. The add-on reads that file once, "
     "when it loads, so a change reaches the picture at the overlay's next start "
     "-- not while it runs.",
     "تُكتب هذه في sidecar.toml، وتُنقل العصبية منها إلى ReShade.ini حيث تقرؤها "
     "الإضافة. تقرأ الإضافة ذلك الملف مرة واحدة عند تحميلها، لذا يصل التغيير إلى "
     "الصورة عند التشغيل التالي للطبقة لا أثناء عملها."},
    {"Neural pass",
     "المرور العصبي"},
    {"passthrough -- capture and present, untouched",
     "passthrough — التقاط وعرض دون مساس"},
    {"reshade -- DLSS 5 neural rendering",
     "reshade — عرض DLSS 5 العصبي"},
    {"Passthrough is the honest A/B baseline: the same capture and present path "
     "with no neural work in it at all.",
     "المرور المباشر هو مرجع A/B الصادق: مسار الالتقاط والعرض نفسه دون أي عمل "
     "عصبي."},
    {"DLSS preset",
     "إعداد DLSS المسبق"},
    {"Optical flow grid",
     "شبكة التدفق البصري"},
    {"1 -- finest, most expensive",
     "1 — الأدق والأعلى كلفة"},
    {"4 -- default",
     "4 — الافتراضي"},
    {"Pixels per estimated motion vector. Finer costs more and is not obviously "
     "better: the vectors are estimated from colour, so a finer grid can sharpen "
     "the estimate or the error equally.",
     "بكسلات لكل متجه حركة مقدّر. الأدق أعلى كلفة وليس أفضل بالضرورة: تُقدّر "
     "المتجهات من اللون، فقد تزيد الشبكة الأدق حدة التقدير والخطأ بالقدر نفسه."},
    {"Synthetic depth",
     "عمق اصطناعي"},
    {"There is no real depth buffer to capture out of the composited frame, so a "
     "constant plane is bound instead. It costs temporal stability under motion "
     "rather than preventing NR from running; this dial is worth a try if motion "
     "smears.",
     "لا يوجد مخزن عمق حقيقي يمكن التقاطه من الإطار المركّب، لذا يُربط مستوى ثابت "
     "بدلًا منه. يكلّف ذلك ثباتًا زمنيًا أثناء الحركة دون أن يمنع العرض العصبي؛ "
     "هذا المقبض يستحق التجربة إذا تلطخت الحركة."},
    {"Neural rendering strength",
     "قوة العرض العصبي"},
    {"Passed straight through to the RenoDX add-on. The add-on owns what these "
     "mean; we only carry them.",
     "تُمرر مباشرة إلى إضافة RenoDX. الإضافة تحدد معناها؛ نحن نحملها فقط."},
    {"Intensity",
     "الشدة"},
    {"How much of the neural result is mixed in. Start here.",
     "مقدار ما يُمزج من النتيجة العصبية. ابدأ من هنا."},
    {"Add-on preset",
     "إعداد الإضافة المسبق"},
    {"Style",
     "النمط"},
    {"Colour strength",
     "قوة اللون"},
    {"At zero the add-on's colour handling collapses to black, so this is not a "
     "subtle dial.",
     "عند الصفر تنهار معالجة الألوان في الإضافة إلى الأسود، فهذا ليس مقبضًا "
     "دقيقًا."},
    {"HDR transfer strength",
     "قوة نقل HDR"},
    {"Paper-white scale",
     "مقياس الأبيض الورقي"},
    {"Both only matter on an HDR display. The sidecar captures SDR today, so "
     "leave them at 1.00 unless you are experimenting.",
     "كلاهما يهم على شاشات HDR فقط. يلتقط البرنامج المرافق SDR حاليًا، فاتركهما "
     "على 1.00 إلا إن كنت تجرب."},
    {"These three have no documented default, so they are written only once you "
     "move them. Clearing the box returns them to untouched, which leaves "
     "whatever the add-on does by itself.",
     "هذه الثلاثة بلا قيمة افتراضية موثقة، لذا لا تُكتب إلا عندما تحركها. إفراغ "
     "الخانة يعيدها دون مساس، فتفعل الإضافة ما تفعله من تلقاء نفسها."},
    {"Enable the add-on's upscaling (work in progress)",
     "تفعيل تكبير الإضافة (قيد التطوير)"},
    {"The add-on marks this unfinished, and the sidecar feeds it a "
     "native-resolution DLAA contract, so it usually reports that it fell back to "
     "native. Off is the tested path.",
     "تصف الإضافة هذا بأنه غير مكتمل، ويعطيها البرنامج المرافق عقد DLAA بالدقة "
     "الأصلية، لذا تبلغ عادة أنها عادت إلى الدقة الأصلية. الإيقاف هو المسار "
     "المجرّب."},
    {"Hook mode",
     "وضع الاعتراض"},
    {"0 turns neural rendering off entirely, 1 adds Streamline hooks, 2 is NGX "
     "only. Two is what this sidecar wants: it makes the NGX calls itself and "
     "there is no Streamline in the process.",
     "0 يوقف العرض العصبي كليًا، و1 يضيف اعتراضات Streamline، و2 هو NGX فقط. "
     "اثنان هو ما يريده هذا البرنامج المرافق: يجري استدعاءات NGX بنفسه ولا يوجد "
     "Streamline في العملية."},
    {"Overlay",
     "الطبقة"},
    {"Advanced",
     "متقدم"},
    {"Local structure",
     "البنية المحلية"},
    {"How hard the model works on fine surface detail -- stonework, cloth weave, "
     "wood grain. Raising it sharpens texture and also sharpens whatever the "
     "model got wrong about it.",
     "مدى اشتغال النموذج على تفاصيل الأسطح الدقيقة — الحجارة ونسيج القماش وعروق "
     "الخشب. رفعه يزيد حدة النسيج ويزيد حدة ما أخطأ فيه النموذج أيضًا."},
    {"Local tone",
     "النغمة المحلية"},
    {"Local contrast: how far the model pushes light against dark within a small "
     "area. This is the dial most likely to change the mood of a scene rather "
     "than its detail.",
     "التباين المحلي: مدى دفع النموذج للضوء مقابل الظل في منطقة صغيرة. هذا المقبض "
     "الأرجح أن يغيّر أجواء المشهد لا تفاصيله."},
    {"Skin structure",
     "بنية البشرة"},
    {"Faces and skin specifically. The one people reach for after watching a "
     "comparison video, and the one most likely to look wrong when overdone -- "
     "skin is where anybody spots a mistake.",
     "الوجوه والبشرة تحديدًا. ما يمد الجميع أيديهم إليه بعد مشاهدة فيديو مقارنة، "
     "والأرجح أن يبدو خاطئًا عند المبالغة — فالجميع يلاحظ الخطأ في البشرة."},
    {"The strip of numbers the overlay draws in its own top-left corner: frame "
     "rate, latency, which pass is running and how many frames were dropped. It "
     "is drawn by the overlay, not by the game, so it never reaches a screenshot "
     "the game takes.",
     "شريط الأرقام الذي ترسمه الطبقة في زاويتها العليا اليسرى: معدل الإطارات وزمن "
     "الاستجابة وأي مرور يعمل وعدد الإطارات المُسقطة. ترسمه الطبقة لا اللعبة، فلا "
     "يظهر أبدًا في لقطة شاشة تأخذها اللعبة."},
    {"Whether the overlay covers the game the moment it launches. Off starts it "
     "hidden, which is the honest way to look at the untouched frame first and "
     "then bring the neural pass in over the top of it.",
     "هل تغطي الطبقة اللعبة لحظة تشغيلها. الإيقاف يبدؤها مخفية، وهي الطريقة "
     "الصادقة لرؤية الإطار دون مساس أولًا ثم إدخال المرور العصبي فوقه."},
    {"CNN F. The default here: clamps history hard, which suits estimated motion "
     "vectors.",
     "CNN F. الافتراضي هنا: يقيّد السجل بقوة، ما يناسب متجهات الحركة المقدّرة."},
    {"CNN E. Clamps hardest. Try this first if motion smears or flames and lights "
     "flicker.",
     "CNN E. الأشد تقييدًا. جرّبه أولًا إذا تلطخت الحركة أو ومضت اللهب والأضواء."},
    {"Transformer K. The SDK default for DLAA. Sharpest when the vectors are "
     "trustworthy.",
     "Transformer K. افتراضي SDK لـ DLAA. الأحدّ عندما تكون المتجهات موثوقة."},
    {"Transformer J. The older transformer preset.",
     "Transformer J. إعداد المحوّل الأقدم."},
    {"Whatever the runtime picks for itself.",
     "ما تختاره بيئة التشغيل بنفسها."},
    {"Show the HUD",
     "إظهار HUD"},
    {"Show the overlay on start",
     "إظهار الطبقة عند البدء"},
    {"Reset to defaults",
     "استعادة الافتراضيات"},
    {"%llu earlier line(s) dropped",
     "أُسقط %llu سطر سابق"},
    {"Last error",
     "آخر خطأ"},
    {"The overlay (sidecar.log)",
     "الطبقة (sidecar.log)"},
    {"This manager",
     "هذا المدير"},
    {"The overlay has not written anything yet.",
     "لم تكتب الطبقة شيئًا بعد."},
    {"Window class not found.",
     "لم يُعثر على فئة النافذة."},
    {"World of Warcraft is not running.",
     "World of Warcraft لا تعمل."},
    {"World of Warcraft must run in borderless windowed mode.\nExclusive "
     "fullscreen has no compositor surface to capture.",
     "يجب أن تعمل World of Warcraft في وضع نافذة بلا حدود.\nملء الشاشة الحصري لا "
     "يملك سطح مركّب يمكن التقاطه."},
    {"%hs is not supported. RTX 40 or RTX 50 required.",
     "%hs غير مدعوم. تلزم RTX 40 أو RTX 50."},
    {"Failed to create the pipeline.",
     "تعذر إنشاء خط المعالجة."},
    {"An overlay is already running.\nStop it from the manager before starting "
     "another.",
     "هناك طبقة تعمل بالفعل.\nأوقفها من المدير قبل تشغيل أخرى."},
    {"The graphics device was reset and could not be rebuilt.",
     "أُعيد ضبط جهاز الرسوميات وتعذرت إعادة بنائه."},
    {"Hotkeys",
     "اختصارات لوحة المفاتيح"},
    {"off",
     "معطّل"},
    {"Start or stop the overlay (while this window is open)",
     "تشغيل الطبقة أو إيقافها (ما دامت هذه النافذة مفتوحة)"},
    {"Show or hide the overlay: instant A/B against the untouched game",
     "إظهار الطبقة أو إخفاؤها: مقارنة A/B فورية مع اللعبة دون مساس"},
    {"Show or hide the frame-time HUD",
     "إظهار HUD زمن الإطار أو إخفاؤه"},
    {"Panic: take the overlay down, always",
     "طوارئ: إزالة الطبقة دائمًا"},
    {"Change them on the Tuning page.",
     "غيّرها من صفحة الضبط."},
    {"Written like Ctrl+Alt+D or Shift+Alt+F9. Each needs Ctrl, Alt or Win, "
     "because Windows takes the combination away from the game. Leave one empty "
     "to switch it off.",
     "تُكتب مثل Ctrl+Alt+D أو Shift+Alt+F9. يحتاج كل منها إلى Ctrl أو Alt أو Win، "
     "لأن Windows يأخذ التركيبة من اللعبة. اترك أحدها فارغًا لتعطيله."},
    {"Start / stop overlay",
     "تشغيل / إيقاف الطبقة"},
    {"Show / hide overlay",
     "إظهار / إخفاء الطبقة"},
    {"Show / hide HUD",
     "إظهار / إخفاء HUD"},
    {"not a key combination",
     "ليست تركيبة مفاتيح"},
    {"Language",
     "اللغة"},
    {"Interface theme",
     "سمة الواجهة"},
    {"Stormwind",
     "ستورمويند"},
    {"Quest log",
     "سجل المهام"},
    {"Dragonflight",
     "دراغونفلايت"},
    {"Neural strength",
     "القوة العصبية"},
    {"How many times DLSS 5 runs over each frame. One pass is subtle. Two or "
     "three push the picture further from the original -- closer to the heavily "
     "processed look in demonstration videos -- and each extra pass costs another "
     "full neural pass of GPU time.",
     "عدد مرات تشغيل DLSS 5 على كل إطار. مرور واحد خفيف. مروران أو ثلاثة يبعدان "
     "الصورة أكثر عن الأصل — أقرب إلى المظهر شديد المعالجة في فيديوهات العرض — "
     "وكل مرور إضافي يكلّف مرورًا عصبيًا كاملًا آخر من وقت معالج الرسوميات."},
    {"1x  Natural",
     "1x  طبيعي"},
    {"2x  Stronger",
     "2x  أقوى"},
    {"3x  Strongest",
     "3x  الأقوى"},
    {"Closest to the game",
     "الأقرب إلى اللعبة"},
    {"About twice the GPU time",
     "نحو ضعف وقت معالج الرسوميات"},
    {"About three times the GPU time",
     "نحو ثلاثة أضعاف وقت معالج الرسوميات"},
    {"Four passes, set in sidecar.toml. Pick one above to go back.",
     "أربعة مرورات، مضبوطة في sidecar.toml. اختر واحدًا أعلاه للعودة."},
    {"The Off preset runs no neural pass, so this has no effect until you pick "
     "another look.",
     "إعداد الإيقاف لا يشغّل أي مرور عصبي، لذا لا أثر لهذا حتى تختار مظهرًا آخر."},
};

const size_t kArabicTableSize = sizeof(kArabicTable) / sizeof(kArabicTable[0]);

}  // namespace sidecar
