#include "flow/FlowToMotionVec.h"

#include "gpu/Shaders/FlowToMotionVec.cs.h"   // generated by dxc at build time

using Microsoft::WRL::ComPtr;

namespace sidecar {

ComPtr<ID3D12Resource> FlowToMotionVec::CreateMotionTarget(ID3D12Device* device,
                                                           uint32_t width,
                                                           uint32_t height) {
  D3D12_HEAP_PROPERTIES heap{};
  heap.Type = D3D12_HEAP_TYPE_DEFAULT;

  D3D12_RESOURCE_DESC rd{};
  rd.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
  rd.Width = width;
  rd.Height = height;
  rd.DepthOrArraySize = 1;
  rd.MipLevels = 1;
  rd.Format = DXGI_FORMAT_R16G16_FLOAT;   // typed, two channels, NDC motion
  rd.SampleDesc.Count = 1;
  rd.Flags = D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;

  ComPtr<ID3D12Resource> tex;
  if (FAILED(device->CreateCommittedResource(
          &heap, D3D12_HEAP_FLAG_NONE, &rd,
          D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr, IID_PPV_ARGS(&tex)))) {
    return nullptr;
  }
  return tex;
}

std::unique_ptr<FlowToMotionVec> FlowToMotionVec::Create(ID3D12Device* device,
                                                         uint32_t fullWidth,
                                                         uint32_t fullHeight) {
  std::unique_ptr<FlowToMotionVec> f(new FlowToMotionVec());
  f->device_ = device;
  f->fullWidth_ = fullWidth;
  f->fullHeight_ = fullHeight;

  D3D12_DESCRIPTOR_RANGE ranges[2]{};
  ranges[0].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;   // flow buffer
  ranges[0].NumDescriptors = 1;
  ranges[0].BaseShaderRegister = 0;
  ranges[1].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;   // motion target
  ranges[1].NumDescriptors = 1;
  ranges[1].BaseShaderRegister = 0;
  ranges[1].OffsetInDescriptorsFromTableStart = 1;

  D3D12_ROOT_PARAMETER params[2]{};
  params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
  params[0].DescriptorTable.NumDescriptorRanges = 2;
  params[0].DescriptorTable.pDescriptorRanges = ranges;
  params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
  params[1].Constants.Num32BitValues = 6;   // fullSize.xy, gridSize.xy, factor, pad
  params[1].Constants.ShaderRegister = 0;

  D3D12_ROOT_SIGNATURE_DESC rsd{};
  rsd.NumParameters = 2;
  rsd.pParameters = params;

  ComPtr<ID3DBlob> blob, error;
  if (FAILED(D3D12SerializeRootSignature(&rsd, D3D_ROOT_SIGNATURE_VERSION_1,
                                         &blob, &error))) {
    return nullptr;
  }
  if (FAILED(device->CreateRootSignature(0, blob->GetBufferPointer(),
                                         blob->GetBufferSize(),
                                         IID_PPV_ARGS(&f->rootSignature_)))) {
    return nullptr;
  }

  D3D12_COMPUTE_PIPELINE_STATE_DESC psd{};
  psd.pRootSignature = f->rootSignature_.Get();
  psd.CS.pShaderBytecode = g_FlowToMotionVecCS;
  psd.CS.BytecodeLength = sizeof(g_FlowToMotionVecCS);
  if (FAILED(device->CreateComputePipelineState(&psd, IID_PPV_ARGS(&f->pipeline_)))) {
    return nullptr;
  }

  D3D12_DESCRIPTOR_HEAP_DESC hd{};
  hd.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
  hd.NumDescriptors = 2;
  hd.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
  if (FAILED(device->CreateDescriptorHeap(&hd, IID_PPV_ARGS(&f->heap_)))) {
    return nullptr;
  }
  f->descriptorSize_ =
      device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
  return f;
}

void FlowToMotionVec::Record(ID3D12GraphicsCommandList* cl,
                             const FlowOutput& flow,
                             ID3D12Resource* dstRg16f) {
  if (!cl || !flow.grid || !dstRg16f) return;

  auto cpu = heap_->GetCPUDescriptorHandleForHeapStart();

  // The flow grid is a raw buffer of int16 pairs, so it is bound as a
  // ByteAddressBuffer rather than a typed view.
  D3D12_SHADER_RESOURCE_VIEW_DESC srv{};
  srv.Format = DXGI_FORMAT_R32_TYPELESS;
  srv.ViewDimension = D3D12_SRV_DIMENSION_BUFFER;
  srv.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
  srv.Buffer.NumElements = flow.gridWidth * flow.gridHeight;   // one uint per cell
  srv.Buffer.Flags = D3D12_BUFFER_SRV_FLAG_RAW;
  device_->CreateShaderResourceView(flow.grid, &srv, cpu);

  cpu.ptr += descriptorSize_;
  D3D12_UNORDERED_ACCESS_VIEW_DESC uav{};
  uav.Format = DXGI_FORMAT_R16G16_FLOAT;
  uav.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
  device_->CreateUnorderedAccessView(dstRg16f, nullptr, &uav, cpu);

  ID3D12DescriptorHeap* heaps[] = {heap_.Get()};
  cl->SetDescriptorHeaps(1, heaps);
  cl->SetComputeRootSignature(rootSignature_.Get());
  cl->SetPipelineState(pipeline_.Get());
  cl->SetComputeRootDescriptorTable(0, heap_->GetGPUDescriptorHandleForHeapStart());

  const uint32_t constants[6] = {fullWidth_, fullHeight_,
                                 flow.gridWidth, flow.gridHeight,
                                 flow.gridSize, 0};
  cl->SetComputeRoot32BitConstants(1, 6, constants, 0);
  cl->Dispatch((fullWidth_ + 7) / 8, (fullHeight_ + 7) / 8, 1);
}

}  // namespace sidecar
