#!/usr/bin/env python3
"""Write a translation table (src/common/core/I18nXx.cpp) from a key list and a
translation file.

Translations are kept by key number rather than by retyping each English key,
so a long paragraph cannot be copied into a table with one word different --
which would make it a key no call site ever looks up.

    python tools/gen_translation_table.py KEYS.json LANG.py Xx TableName "Language"

KEYS.json is a JSON list of the English source strings, in order. LANG.py
defines T = {index: "translation", ...}; indices it leaves out stay English at
runtime, which is the documented fallback. A translation identical to its key
is dropped, because it carries no information and the CI check warns on it.

Refuses to write a table whose format specifiers differ from the key's: that is
a crash, not a typo.
"""

from __future__ import annotations

import json
import pathlib
import re
import runpy
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SPECIFIER = re.compile(r"%[-+ #0-9.]*(?:ll|z|h)?[sdfuxzp]")


def literal(text: str, indent: str) -> str:
    """A C++ string literal, split into adjacent pieces of about 76 columns."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    pieces: list[str] = []
    while len(escaped) > 76:
        space = escaped.rfind(" ", 0, 76)
        # After a space where there is one (a space is never part of an escape);
        # otherwise -- CJK has no spaces -- at 76, stepped back off any escape.
        cut = space + 1 if space > 0 else 76
        if space <= 0:
            run = 0
            while cut - 1 - run >= 0 and escaped[cut - 1 - run] == "\\":
                run += 1
            if run % 2 == 1:
                cut -= 1
        pieces.append(escaped[:cut])
        escaped = escaped[cut:]
    pieces.append(escaped)
    return ("\n" + indent).join(f'"{p}"' for p in pieces)


def main() -> int:
    keys_path, lang_path, suffix, table, language = sys.argv[1:6]
    keys = json.loads(pathlib.Path(keys_path).read_text(encoding="utf-8"))
    translations = runpy.run_path(lang_path)["T"]

    rows: list[str] = []
    errors = 0
    for index, english in enumerate(keys):
        if index not in translations:
            continue
        translated = translations[index]
        if not translated or translated == english:
            continue
        if SPECIFIER.findall(english) != SPECIFIER.findall(translated):
            print(f"{language} #{index}: specifiers differ: {english[:50]!r}", file=sys.stderr)
            errors += 1
            continue
        rows.append("    {" + literal(english, "     ") + ",\n     " +
                    literal(translated, "     ") + "},")
    unknown = set(translations) - set(range(len(keys)))
    if unknown:
        print(f"{language}: indices past the key list: {sorted(unknown)}", file=sys.stderr)
        errors += 1
    if errors:
        return 1

    out = REPO / "src" / "common" / "core" / f"I18n{suffix}.cpp"
    out.write_text(
        '#include "core/I18nTable.h"\n\n'
        f"// {language} interface text. Generated by tools/gen_translation_table.py;\n"
        "// the conventions are the Russian table's (I18nRu.cpp): keys are the English\n"
        "// source text exactly, format specifiers keep their order, and file names,\n"
        "// add-on key names and the log are never translated.\n\n"
        "namespace sidecar {\n\n"
        f"const TranslationPair k{table}Table[] = {{\n" + "\n".join(rows) + "\n};\n\n"
        f"const size_t k{table}TableSize = sizeof(k{table}Table) / sizeof(k{table}Table[0]);\n\n"
        "}  // namespace sidecar\n",
        encoding="utf-8",
    )
    print(f"wrote {out.name}: {len(rows)} of {len(keys)} strings")
    return 0


if __name__ == "__main__":
    sys.exit(main())
